Repository BCSDLab/KOIN_API_V2, pull requests merged in 2024-05, with the labels that each got.

#497 refactor: 상점 운영중 여부 로직 변경
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
Labels: 리팩터링, Team Business

#502 feat: 상점 이벤트 알림에 썸네일이미지 추가
  src/main/java/in/koreatech/koin/domain/ownershop/EventArticleCreateShopEvent.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopEventListener.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
Labels: 기능, Team Business

#495 feat: GET /admin/members api 추가
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
  src/main/java/in/koreatech/koin/admin/member/dto/AdminMembersResponse.java
  src/main/java/in/koreatech/koin/admin/member/enums/TrackTag.java
  src/main/java/in/koreatech/koin/admin/member/repository/AdminMemberRepository.java
  src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
Labels: 기능

#504 hotfix: 버스 API 응답시간 개선 및 응답 스키마 불일치 해결(develop)
  src/main/java/in/koreatech/koin/domain/bus/dto/BusTimetableResponse.java
  src/main/java/in/koreatech/koin/domain/bus/model/SchoolBusTimetable.java
  src/main/java/in/koreatech/koin/domain/bus/model/city/CityBusCache.java
  src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusCache.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/main/java/in/koreatech/koin/domain/bus/util/BusScheduler.java
  src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
Labels: 버그

#501 fix : 품절 알림 발송 여부, 시간대 조건, 경로 추가
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopApi.java
  src/main/java/in/koreatech/koin/domain/coop/dto/SoldOutRequest.java
  src/main/java/in/koreatech/koin/domain/coop/exception/DiningCacheNotFoundException.java
  src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
  src/main/java/in/koreatech/koin/domain/coop/model/DiningSoldOutCache.java
  src/main/java/in/koreatech/koin/domain/coop/model/DiningSoldOutEvent.java
  src/main/java/in/koreatech/koin/domain/coop/repository/DiningSoldOutCacheRepository.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
  src/main/java/in/koreatech/koin/domain/dining/model/DiningType.java
  src/main/java/in/koreatech/koin/domain/kakao/service/KakaoBotService.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/global/fcm/MobileAppPath.java
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
  src/test/java/in/koreatech/koin/fixture/DiningFixture.java
Labels: Team Campus

#505 Feat: 어드민 복덕방 생성 API
  src/main/java/in/koreatech/koin/admin/land/controller/AdminLandApi.java
  src/main/java/in/koreatech/koin/admin/land/controller/AdminLandController.java
  src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
  src/main/java/in/koreatech/koin/admin/land/execption/LandNameDuplicationException.java
  src/main/java/in/koreatech/koin/admin/land/repository/AdminLandRepository.java
  src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
  src/main/java/in/koreatech/koin/domain/land/model/Land.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
  src/test/java/in/koreatech/koin/fixture/LandFixture.java
Labels: 기능

#506 feat : 품절 알림 구독 아침, 점심, 저녁 분리
  src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
  src/main/java/in/koreatech/koin/domain/coop/model/DiningSoldOutEvent.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopEventListener.java
  src/main/java/in/koreatech/koin/global/domain/notification/controller/NotificationApi.java
  src/main/java/in/koreatech/koin/global/domain/notification/controller/NotificationController.java
  src/main/java/in/koreatech/koin/global/domain/notification/dto/NotificationStatusResponse.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationDetailSubscribeType.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationSubscribe.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationSubscribeType.java
  src/main/java/in/koreatech/koin/global/domain/notification/repository/NotificationSubscribeRepository.java
  src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
  src/main/resources/db/migration/V13__add_notification_detail_subscribe_table.sql
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
  src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
Labels: 기능, Team Campus

#511 fix : notification_subscrdibe 복합 unique 추가
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationSubscribe.java
  src/main/resources/db/migration/V14__alter_notification_subscribe_unique.sql
Labels: 버그

#514 fix : notification FK 회원 삭제 오류 수정
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/resources/db/migration/V15__delete_notification_subscribe.sql
Labels: 버그, Team User

#517 fix: 에러 반환값 수정
  src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
  src/main/resources/logback-spring.xml
Labels: 버그

#521 feat: admin으로 BCSDLab 트랙 리스트 조회
  src/main/java/in/koreatech/koin/admin/member/controller/AdminTrackApi.java
  src/main/java/in/koreatech/koin/admin/member/controller/AdminTrackController.java
  src/main/java/in/koreatech/koin/admin/member/dto/AdminTrackResponse.java
  src/main/java/in/koreatech/koin/admin/member/repository/AdminTrackRepository.java
  src/main/java/in/koreatech/koin/admin/member/service/AdminTrackService.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminTrackApiTest.java
Labels: 기능, 온보딩

#524 feat: 사장님 비밀번호 변경 휴대폰 인증api 추가
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerEmailVerifyRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordResetVerifyEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordResetVerifySmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordUpdateEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordUpdateSmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerSendSmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerSmsVerifyRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/VerifyEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/VerifySmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/exception/DuplicationPhoneNumberException.java
  src/main/java/in/koreatech/koin/domain/owner/exception/VerificationDailyLimitExceededException.java
  src/main/java/in/koreatech/koin/domain/owner/model/EmailVerifyRequest.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerInVerification.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerSmsRequestEvent.java
  src/main/java/in/koreatech/koin/domain/owner/model/redis/DailyVerificationLimit.java
  src/main/java/in/koreatech/koin/domain/owner/model/redis/OwnerVerificationStatus.java
  src/main/java/in/koreatech/koin/domain/owner/repository/EmailVerifyRequestRedisRepository.java
  src/main/java/in/koreatech/koin/domain/owner/repository/OwnerInVerificationRedisRepository.java
  src/main/java/in/koreatech/koin/domain/owner/repository/redis/DailyVerificationLimitRepository.java
  src/main/java/in/koreatech/koin/domain/owner/repository/redis/OwnerVerificationStatusRepository.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
Labels: 기능, Team Business

#532 refactor: sms인증시 슬랙 알림 포멧 변경
  src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotificationFactory.java
Labels: 리팩터링, Team Business

#536 feat: swagger 인증번호 발송 관련 api명세 추가
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
Labels: 기능

#540 fix: 삭제된 멤버 조회 수정
  src/main/java/in/koreatech/koin/domain/member/repository/MemberRepository.java
  src/main/java/in/koreatech/koin/domain/member/service/TrackService.java
  src/test/java/in/koreatech/koin/acceptance/TrackApiTest.java
  src/test/java/in/koreatech/koin/fixture/MemberFixture.java
Labels: 버그

#528 feat: 어드민 계정으로 특정 학생 조회
  src/main/java/in/koreatech/koin/admin/land/controller/AdminLandApi.java
  src/main/java/in/koreatech/koin/admin/land/controller/AdminLandController.java
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentResponse.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentUpdateResponse.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
Labels: 기능

#533 feat: 특정 사장님 조회(어드민 계정)
  src/main/java/in/koreatech/koin/admin/land/repository/AdminLandRepository.java
  src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
  src/main/java/in/koreatech/koin/admin/member/dto/AdminMembersResponse.java
  src/main/java/in/koreatech/koin/admin/member/dto/AdminTrackResponse.java
  src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminOwnerResponse.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminOwnerRepository.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminShopRepository.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
Labels: 기능

#547 feat: 데이터독 APM설정 추가
  Dockerfile
Labels: 기능

#548 refactor: docker 파일 wget설치 명령어 추가
  Dockerfile
Labels: 기능

#543 feat: 커스텀 시간표 API
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableUpdateRequest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: 기능

#541 feat: POST /admin/members API 추가
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
  src/main/java/in/koreatech/koin/admin/member/dto/AdminMemberRequest.java
  src/main/java/in/koreatech/koin/admin/member/repository/AdminMemberRepository.java
  src/main/java/in/koreatech/koin/admin/member/repository/AdminTrackRepository.java
  src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
Labels: 기능, Team Business

#549 refactor: GET /shops api 성능최적화
  src/main/java/in/koreatech/koin/domain/shop/repository/redis/ShopsRedisRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/main/java/in/koreatech/koin/global/config/RedisConfig.java
  src/main/java/in/koreatech/koin/global/scheduler/CacheShopsScheduler.java
Labels: 리팩터링, Team Business

#564 feat: 상점 사장님 휴대폰번호로 회원가입 api작성
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerRegisterByPhoneRequest.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
Labels: 기능, Team Business

#565 버스 openApi 에러 수정
  src/main/java/in/koreatech/koin/domain/bus/util/BusScheduler.java
Labels: 버그

#572 feat : 티머니 시외버스 API 구현
  src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusCache.java
  src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusStationNode.java
  src/main/java/in/koreatech/koin/domain/bus/model/express/PublicOpenApiExpressBusArrival.java
  src/main/java/in/koreatech/koin/domain/bus/model/express/TmoneyOpenApiExpressBusArrival.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/main/java/in/koreatech/koin/domain/bus/util/BusScheduler.java
  src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/PublicExpressBusOpenApiClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/TmoneyExpressBusOpenApiClient.java
  src/test/resources/application.yml
Labels: 기능, Team Campus

#562 fix: 회원가입 동시성 이슈 처리
  src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 버그

#559 fix: 사장님 탈퇴 이슈 예외 처리
  src/main/java/in/koreatech/koin/domain/owner/model/Owner.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerAttachment.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
  src/test/java/in/koreatech/koin/fixture/UserFixture.java
Labels: 버그

#577 fix: is_open로직 변경
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopsResponse.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopOpen.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/fixture/ShopFixture.java
Labels: 버그

#567 feat: GET /admin/members/{id} api 추가
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
  src/main/java/in/koreatech/koin/admin/member/dto/AdminMemberResponse.java
  src/main/java/in/koreatech/koin/admin/member/repository/AdminMemberRepository.java
  src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
Labels: 기능, Team Business
