Repository BCSDLab/KOIN_API_V2, pull requests merged in 2024-12, with the labels that each got.

#1065 fix: lecutre 테이블 컬럼 수정
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
  src/main/java/in/koreatech/koin/domain/timetable/model/Lecture.java
  src/main/java/in/koreatech/koin/domain/timetable/model/Semester.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/LectureRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/LectureRepositoryV2.java
  src/main/resources/db/migration/V104__alter_lecture_class_time.sql
  src/main/resources/db/migration/V105__add_semester_id_column.sql
  src/main/resources/db/migration/V106__update_semester_id.sql
  src/main/resources/db/migration/V107__alter_fk_lectures_on_semester.sql
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
  src/test/java/in/koreatech/koin/fixture/LectureFixture.java
Labels: 버그, Team User

#1112 fix: 강의 시간 NPE 예외 처리
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/exception/TimetableLectureClassTimeNullException.java
Labels: 버그, Team User

#1104 fix: AB테스트 토큰 발급용 API 추가
  src/main/java/in/koreatech/koin/admin/abtest/controller/AbtestApi.java
  src/main/java/in/koreatech/koin/admin/abtest/controller/AbtestController.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/response/AbtestAccessHistoryResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/response/AbtestDevicesResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/model/AccessHistory.java
  src/main/java/in/koreatech/koin/admin/abtest/service/AbtestService.java
  src/main/java/in/koreatech/koin/admin/history/aop/AdminActivityHistoryAspect.java
Labels: 버그

#1109 fix: V1 시간표에서 6시 이후 시간은 제외하고 조회되도록 수정
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
Labels: 버그

#1110 feat: 삭제된 시간표 강의 복구
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableLectureRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableFrameService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
  src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
  src/test/java/in/koreatech/koin/fixture/TimeTableV2Fixture.java
Labels: 기능

#1114 fix: 데이터베이스 롤백을 위한 작업 삭제
  src/main/java/in/koreatech/koin/domain/timetable/model/Lecture.java
  src/main/java/in/koreatech/koin/domain/timetable/model/Semester.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/LectureRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/LectureRepositoryV2.java
  src/main/resources/db/migration/V104__alter_lecture_class_time.sql
  src/main/resources/db/migration/V105__add_semester_id_column.sql
  src/main/resources/db/migration/V106__update_semester_id.sql
  src/main/resources/db/migration/V107__alter_fk_lectures_on_semester.sql
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
  src/test/java/in/koreatech/koin/fixture/LectureFixture.java
Labels: 버그

#1115 refactor: 6시 이후 시간도 보이게 다시 수정
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
Labels: 리팩터링

#1117 fix: PUT/v2/timetables/lecture 검증 로직 추가
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureUpdateRequest.java
Labels: 버그

#1123 feat: 상점 혜택 상세보기 필드 추가
  src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitApi.java
  src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitController.java
  src/main/java/in/koreatech/koin/admin/benefit/dto/AdminBenefitCategoriesResponse.java
  src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
  src/main/java/in/koreatech/koin/domain/benefit/dto/BenefitShopsResponse.java
  src/main/java/in/koreatech/koin/domain/benefit/repository/BenefitCategoryMapRepository.java
  src/main/java/in/koreatech/koin/domain/benefit/service/ShopBenefitService.java
  src/test/java/in/koreatech/koin/acceptance/BenefitApiTest.java
Labels: 기능, Team Business

#1041 refactor: 엑셀 메서드 분리
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
Labels: 리팩터링

#1099 feat: 버스 교통편 조회 API
  src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/dto/BusRouteCommand.java
  src/main/java/in/koreatech/koin/domain/bus/dto/BusScheduleResponse.java
  src/main/java/in/koreatech/koin/domain/bus/model/enums/BusRouteType.java
  src/main/java/in/koreatech/koin/domain/bus/model/enums/BusStation.java
  src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusSchedule.java
  src/main/java/in/koreatech/koin/domain/bus/model/mongo/CityBusTimetable.java
  src/main/java/in/koreatech/koin/domain/bus/model/mongo/Route.java
  src/main/java/in/koreatech/koin/domain/bus/repository/BusRepository.java
  src/main/java/in/koreatech/koin/domain/bus/repository/CityBusTimetableRepository.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/main/java/in/koreatech/koin/domain/bus/service/route/BusRouteStrategy.java
  src/main/java/in/koreatech/koin/domain/bus/service/route/CityBusRouteStrategy.java
  src/main/java/in/koreatech/koin/domain/bus/service/route/CommutingBusRouteStrategy.java
  src/main/java/in/koreatech/koin/domain/bus/service/route/ExpressBusRouteStrategy.java
  src/main/java/in/koreatech/koin/domain/bus/service/route/ShuttleBusRouteStrategy.java
Labels: 기능, Team Campus

#1119 feat: 학교버스 시간표 관련 API
  src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/dto/ShuttleBusRoutesResponse.java
  src/main/java/in/koreatech/koin/domain/bus/dto/ShuttleBusTimetableResponse.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusIllegalRegionException.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusIllegalRouteTypeException.java
  src/main/java/in/koreatech/koin/domain/bus/model/enums/ShuttleBusRegion.java
  src/main/java/in/koreatech/koin/domain/bus/model/enums/ShuttleRouteType.java
  src/main/java/in/koreatech/koin/domain/bus/model/mongo/ShuttleBusRoute.java
  src/main/java/in/koreatech/koin/domain/bus/repository/ShuttleBusRepository.java
  src/main/java/in/koreatech/koin/domain/bus/service/ShuttleBusService.java
Labels: 기능, Team Campus

#1131 fix: 어드민 히스토리 기능 수정
  src/main/java/in/koreatech/koin/admin/history/aop/AdminActivityHistoryAspect.java
  src/main/java/in/koreatech/koin/admin/history/controller/HistoryApi.java
  src/main/java/in/koreatech/koin/admin/history/controller/HistoryController.java
  src/main/java/in/koreatech/koin/admin/history/dto/AdminHistoriesCondition.java
  src/main/java/in/koreatech/koin/admin/history/dto/AdminHistoriesResponse.java
  src/main/java/in/koreatech/koin/admin/history/dto/AdminHistoryResponse.java
  src/main/java/in/koreatech/koin/admin/history/model/AdminActivityHistory.java
  src/main/java/in/koreatech/koin/admin/history/repository/AdminActivityHistoryRepository.java
  src/main/java/in/koreatech/koin/admin/history/service/HistoryService.java
Labels: 버그, Team User

#1124 refactor: 이미지 업로드 알림 로직 분리
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopApi.java
  src/main/java/in/koreatech/koin/domain/coop/model/DiningNotifyCache.java
  src/main/java/in/koreatech/koin/domain/coop/repository/DiningNotifyCacheRepository.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/coop/util/CoopScheduler.java
  src/main/java/in/koreatech/koin/domain/coopshop/exception/DiningTypeNotFoundException.java
  src/main/java/in/koreatech/koin/domain/coopshop/service/CoopShopService.java
  src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
  src/test/java/in/koreatech/koin/fixture/DiningFixture.java
Labels: 리팩터링

#1136 feat : 버스 긴급 공지 API 구현
  src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/dto/BusNoticeResponse.java
  src/main/java/in/koreatech/koin/domain/bus/repository/BusNoticeRepository.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/main/java/in/koreatech/koin/domain/community/article/model/redis/BusNoticeArticle.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/redis/BusArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/scheduler/ArticleScheduler.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/main/java/in/koreatech/koin/global/config/RedisConfig.java
Labels: 기능, Team Campus

#1133 refactor: 엑셀 다운로드 따닥 방지
  src/main/java/in/koreatech/koin/domain/coop/exception/DuplicateExcelRequestException.java
  src/main/java/in/koreatech/koin/domain/coop/model/ExcelDownloadCache.java
  src/main/java/in/koreatech/koin/domain/coop/repository/ExcelDownloadCacheRepository.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
Labels: 리팩터링

#1137 fix : 버스 긴급공지 조회 테이블 수정(koreatech_articles -> new_articles)
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
Labels: 버그, Team Campus

#1126 fix: 시간표 프레임 롤백 로직 수정
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
Labels: 버그, Team User

#1139 fix: 버스 교통편 조회 대성 시간표 오류 수정
  src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusSchedule.java
  src/main/java/in/koreatech/koin/domain/bus/service/route/ExpressBusRouteStrategy.java
Labels: 버그

#1142 fix: 계절학기 삽입을 위한 lecture 컬럼 크기 변경
  src/main/resources/db/migration/V105__alter_lecture_semester_date_size.sql
  src/main/resources/db/migration/V106__alter_lecture_class_time_size.sql
Labels: 버그, Team User

#1145 fix: 식단 이미지 알림 롤백
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/coop/util/CoopScheduler.java
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
Labels: 버그, Team Campus

#1144 fix : 동계방학 생협 운영시간 업데이트
  src/main/resources/db/migration/V107__update_coop_shop.sql
Labels: 버그, Team Campus

#1138 feat: 스웨거 그룹화
  src/main/java/in/koreatech/koin/global/config/swagger/SwaggerConfig.java
  src/main/java/in/koreatech/koin/global/config/swagger/SwaggerGroupConfig.java
Labels: 기능

#1151 fix : 생협 운영장 추가 및 운영시간 오타 수정
  src/main/resources/db/migration/V108__add_coopshops.sql
Labels: 버그, Team Campus

#1150 feat: 시간표 조회 API 이수 구분 반환 추가
  src/main/java/in/koreatech/koin/domain/graduation/exception/CatalogNotFoundException.java
  src/main/java/in/koreatech/koin/domain/graduation/exception/CourseTypeNotFoundException.java
  src/main/java/in/koreatech/koin/domain/graduation/exception/DepartmentNotFoundException.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CourseTypeRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/DepartmentRepository.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableLectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
  src/test/java/in/koreatech/koin/fixture/CourseTypeFixture.java
  src/test/java/in/koreatech/koin/fixture/TimeTableV2Fixture.java
Labels: 기능, Team User

#1153 feat : 엑셀 파일로 과거 시간표 추가하기
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationApi.java
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationController.java
  src/main/java/in/koreatech/koin/domain/graduation/exception/ExcelFileCheckException.java
  src/main/java/in/koreatech/koin/domain/graduation/exception/ExcelFileNotFoundException.java
  src/main/java/in/koreatech/koin/domain/graduation/model/GradeExcelData.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CourseTypeRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/exception/ExcelFileCheckException.java
  src/main/java/in/koreatech/koin/domain/timetableV2/exception/ExcelFileNotFoundException.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
Labels: 기능, Team User
