Repository BCSDLab/KOIN_API_V2, pull requests merged in 2024-04, with the labels that each got.

#269 feat : 알림 구독 Api 구현
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/NotificationPermitRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/NotificationStatusResponse.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/global/domain/notification/NotificationService.java
  src/main/java/in/koreatech/koin/global/domain/notification/NotificationType.java
  src/main/java/in/koreatech/koin/global/domain/notification/controller/NotificationApi.java
  src/main/java/in/koreatech/koin/global/domain/notification/controller/NotificationController.java
  src/main/java/in/koreatech/koin/global/domain/notification/dto/NotificationPermitRequest.java
  src/main/java/in/koreatech/koin/global/domain/notification/dto/NotificationStatusResponse.java
  src/main/java/in/koreatech/koin/global/domain/notification/dto/NotificationSubscribePermitRequest.java
  src/main/java/in/koreatech/koin/global/domain/notification/exception/NotificationSubscribeNotFoundException.java
  src/main/java/in/koreatech/koin/global/domain/notification/exception/SubscribeNotFoundException.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/Notification.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationSubscribe.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationSubscribeType.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationType.java
  src/main/java/in/koreatech/koin/global/domain/notification/repository/NotificationRepository.java
  src/main/java/in/koreatech/koin/global/domain/notification/repository/NotificationSubscribeRepository.java
  src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
  src/main/resources/application-test.yml
  src/main/resources/db/migration/V5__add_notification_subscribe_table.sql
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
  src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
  src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
Labels: 기능

#250 feat: 메뉴 변경 여부 추가
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
  src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
  src/main/resources/db/migration/V6__alter_diningmenus_updated.sql
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
Labels: 기능, Team Campus

#274 refactor: 메뉴 변경 여부 컬럼명 통일
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
  src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
  src/main/resources/db/migration/V6__alter_diningmenus_updated.sql
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
Labels: Team Campus

#284 refactor: 조회 방식 수정
  src/main/java/in/koreatech/koin/domain/user/model/Student.java
  src/main/java/in/koreatech/koin/domain/user/repository/StudentRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
Labels: 버그

#286 fix: student Entity 필드 수정
  src/main/java/in/koreatech/koin/domain/user/model/Student.java
  src/main/java/in/koreatech/koin/domain/user/repository/StudentRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
Labels: 버그

#288 refactor: 로그아웃, 탈퇴에 대한 권한 수정
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
Labels: 버그

#293 feat: lecture blank error
  src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: 버그

#298 feat: 가게 이벤트 정보 조회
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopEventsResponse.java
  src/main/java/in/koreatech/koin/domain/shop/model/EventArticle.java
  src/main/java/in/koreatech/koin/domain/shop/repository/EventArticleRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
Labels: 기능, Team Business

#300 feat: stage logback 적용
  .gitignore
  build.gradle
  src/main/java/in/koreatech/koin/global/exception/ErrorResponse.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
  src/main/java/in/koreatech/koin/global/log/RequestLoggingFilter.java
  src/main/java/in/koreatech/koin/global/log/WebLogConfig.java
  src/main/resources/application-test.yml
  src/main/resources/logback-spring.xml
Labels: 기능

#311 feat: get member
  src/main/java/in/koreatech/koin/domain/land/service/LandService.java
  src/main/java/in/koreatech/koin/domain/member/controller/MemberApi.java
  src/main/java/in/koreatech/koin/domain/member/controller/MemberController.java
  src/main/java/in/koreatech/koin/domain/member/controller/TrackApi.java
  src/main/java/in/koreatech/koin/domain/member/controller/TrackController.java
  src/main/java/in/koreatech/koin/domain/member/dto/MemberResponse.java
  src/main/java/in/koreatech/koin/domain/member/dto/TrackResponse.java
  src/main/java/in/koreatech/koin/domain/member/dto/TrackSingleResponse.java
  src/main/java/in/koreatech/koin/domain/member/exception/MemberNotFoundException.java
  src/main/java/in/koreatech/koin/domain/member/exception/TrackNotFoundException.java
  src/main/java/in/koreatech/koin/domain/member/model/Member.java
  src/main/java/in/koreatech/koin/domain/member/model/TechStack.java
  src/main/java/in/koreatech/koin/domain/member/model/Track.java
  src/main/java/in/koreatech/koin/domain/member/repository/MemberRepository.java
  src/main/java/in/koreatech/koin/domain/member/repository/TechStackRepository.java
  src/main/java/in/koreatech/koin/domain/member/repository/TrackRepository.java
  src/main/java/in/koreatech/koin/domain/member/service/MemberService.java
  src/main/java/in/koreatech/koin/domain/member/service/TrackService.java
  src/main/java/in/koreatech/koin/domain/track/repository/MemberRepository.java
  src/test/java/in/koreatech/koin/acceptance/MemberApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TrackApiTest.java
Labels: 기능

#302 feat: is_event값 추가
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
  src/main/java/in/koreatech/koin/domain/shop/repository/EventArticleRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/support/JsonAssertions.java
Labels: 기능, Team Business

#319 fix: 사장님 가게정보 수정 오류
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
Labels: 버그

#320 fix: menu 정보 수정 시에도 flush 추가
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/Menu.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
Labels: 버그

#310 refactor: 식단 품절, 변경 여부 (Boolean -> 시간)으로 변경
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopController.java
  src/main/java/in/koreatech/koin/domain/coop/dto/SoldOutRequest.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
  src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
  src/main/resources/db/migration/V7__alter_diningmenus_change_field_type.sql
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
Labels: 리팩터링, Team Campus

#322 feat: 유저 권한 조회 API 작성
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/AuthResponse.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 기능

#324 refactor: 식단 조회 API DTO 필드명 변경
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
Labels: 리팩터링, Team Campus

#333 feat: FCM 발송방식 수정
  .github/pr-labeler.yml
  .github/workflows/pr-labeler.yml
  src/main/java/in/koreatech/koin/global/domain/notification/model/Notification.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
  src/main/java/in/koreatech/koin/global/fcm/FcmClient.java
  src/main/java/in/koreatech/koin/global/fcm/MobileAppPath.java
  src/main/resources/db/migration/V8__alter_notificaion_change_column_name.sql
Labels: 기능

#342 feat: 비밀번호 변경 로직 구현
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopController.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/AuthTokenRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/FindPasswordRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordChangeRequest.java
  src/main/java/in/koreatech/koin/domain/user/exception/UserResetTokenExpiredException.java
  src/main/java/in/koreatech/koin/domain/user/model/AuthResult.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
  src/main/java/in/koreatech/koin/global/config/LocalDateTimeAttributeConverter.java
  src/main/java/in/koreatech/koin/global/config/WebConfig.java
  src/main/java/in/koreatech/koin/global/domain/email/form/StudentPasswordChangeData.java
  src/main/java/in/koreatech/koin/global/host/ServerURLArgumentResolver.java
  src/main/resources/mail/change_password_config.html
  src/main/resources/mail/student_change_password_certificate_button.html
  src/main/resources/static/js/password.check.js
  src/main/resources/static/js/sha256.min.js
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 기능, Team User

#345 Fix : POST /user/find/password 메일 미발송
  src/main/java/in/koreatech/koin/domain/user/dto/FindPasswordRequest.java
Labels: 버그, Team User

#348 fix: attributeConverter milli second 길이가 두개인 경우도 반영
  src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
  src/main/java/in/koreatech/koin/global/config/LocalDateTimeAttributeConverter.java
Labels: 버그

#357 fix : 삭제된 userGender null 로직 추가
  src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateResponse.java
Labels: 버그, Team User

#355 fix: isAuthed 검증 추가
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/global/auth/AuthArgumentResolver.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 버그

#360 feat: 회원 탈퇴시 유저타입 추가
  src/main/java/in/koreatech/koin/domain/user/model/UserDeleteEvent.java
  src/main/java/in/koreatech/koin/domain/user/model/UserEventListener.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotificationFactory.java
Labels: 기능

#366 fix: soft delete메뉴 조회시 서버에러 해결
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
  src/main/java/in/koreatech/koin/domain/shop/model/Menu.java
  src/main/java/in/koreatech/koin/domain/shop/model/MenuCategoryMap.java
  src/main/java/in/koreatech/koin/domain/shop/repository/MenuRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
Labels: 버그

#358 feat : 버스 코스 조회 구현
  src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/dto/BusCourseResponse.java
  src/main/java/in/koreatech/koin/domain/bus/repository/BusRepository.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
Labels: 기능, Team Campus

#328 fix: 버스 노드 도착 시간이 시간이 아닌 경우 처리
  src/main/java/in/koreatech/koin/domain/bus/dto/ExpressBusRemainTime.java
  src/main/java/in/koreatech/koin/domain/bus/model/BusRemainTime.java
  src/main/java/in/koreatech/koin/domain/bus/model/city/CityBusRemainTime.java
  src/main/java/in/koreatech/koin/domain/bus/model/mongo/Route.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
Labels: 버그, Team Campus

#374 refactor: 예외형태 수정
  src/main/java/in/koreatech/koin/global/exception/ErrorResponse.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
Labels: 리팩터링

#368 fix: 메뉴 삭제 시 연관 데이터 삭제 수정
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/Menu.java
Labels: 버그

#377 fix: Repository Named Query수정
  src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
Labels: 버그

#381 fix: upload memberId 자료형 수정
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadController.java
Labels: 버그, Team Campus

#382 feat: CORS 설정 추가
  src/main/java/in/koreatech/koin/KoinApplication.java
  src/main/java/in/koreatech/koin/global/config/CorsProperties.java
  src/main/java/in/koreatech/koin/global/config/WebConfig.java
  src/main/resources/application-test.yml
Labels: 기능

#383 refactor: 비밀번호가 틀렸을 때 반환하는 메시지 간략화
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
Labels: 리팩터링

#385 refactor: 유저 로그인에서 swagger에 400에러 표시
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
Labels: 리팩터링

#369 feat: 버스 시간표 불러오기
  src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/dto/ExpressBusTimeTable.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusTypeNotSupportException.java
  src/main/java/in/koreatech/koin/domain/bus/model/BusTimetable.java
  src/main/java/in/koreatech/koin/domain/bus/model/SchoolBusTimetable.java
  src/main/java/in/koreatech/koin/domain/bus/model/city/CityBusRemainTime.java
  src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusCacheInfo.java
  src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusTimetable.java
  src/main/java/in/koreatech/koin/domain/bus/repository/BusRepository.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
Labels: 기능, Team Campus

#386 fix: flush 추가 및 unique 설정
  src/main/java/in/koreatech/koin/domain/community/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/model/ArticleViewLog.java
  src/main/java/in/koreatech/koin/domain/community/model/Board.java
  src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
  src/main/java/in/koreatech/koin/domain/land/model/Land.java
  src/main/java/in/koreatech/koin/domain/owner/model/Owner.java
  src/main/java/in/koreatech/koin/domain/shop/model/Menu.java
  src/main/java/in/koreatech/koin/domain/shop/model/MenuCategory.java
  src/main/java/in/koreatech/koin/domain/shop/model/MenuCategoryMap.java
  src/main/java/in/koreatech/koin/domain/shop/model/MenuImage.java
  src/main/java/in/koreatech/koin/domain/shop/model/MenuOption.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopCategoryMap.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopImage.java
  src/main/java/in/koreatech/koin/domain/timetable/model/Semester.java
  src/main/java/in/koreatech/koin/domain/user/model/Student.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/version/model/Version.java
  src/main/resources/db/migration/V9__alter_notificaion_modify_auditing.sql
  src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 버그, 기능, 리팩터링

#387 feat: 상점 이벤트 생성, 조회 기능 구현
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/model/BusTimetable.java
  src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopApi.java
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopController.java
  src/main/java/in/koreatech/koin/domain/ownershop/dto/CreateEventRequest.java
  src/main/java/in/koreatech/koin/domain/ownershop/dto/ModifyEventRequest.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopEventsResponse.java
  src/main/java/in/koreatech/koin/domain/shop/model/EventArticle.java
  src/main/java/in/koreatech/koin/domain/shop/model/EventArticleImage.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
  src/main/java/in/koreatech/koin/domain/shop/repository/EventArticleImageRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/EventArticleRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/resources/db/migration/V10__add_event_article_thumbnail_images_table.sql
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
Labels: 기능, Team Business

#389 feat: 사장님 가게 생성 시 알림 발송하도록 추가
  src/main/java/in/koreatech/koin/domain/ownershop/ShopEventCreateEvent.java
  src/main/java/in/koreatech/koin/domain/ownershop/dto/CreateEventRequest.java
  src/main/java/in/koreatech/koin/domain/ownershop/dto/ModifyEventRequest.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopEventListener.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/Notification.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
  src/main/java/in/koreatech/koin/global/fcm/MobileAppPath.java
  src/main/resources/db/migration/V11__alter_notification_column_nullable.sql
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
Labels: 기능

#393 fix: 임시토큰 비교 자료형 불일치 수정
  src/main/java/in/koreatech/koin/domain/user/model/UserType.java
Labels: 버그

#395 fix: 사장님 이벤트 날짜조건 제거한 DTO 추가
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopApi.java
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopController.java
  src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopEventsResponse.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
Labels: 버그, Team Business

#397 fix: 로그인에 권한 확인 로직 추가
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
Labels: 버그

#391 feat : PUT user/student/me 현재 사용 닉네임 처리 로직 추가
  src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
Labels: 기능, Team User

#402 feat : depart json 네이밍 변경
  src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusTimetable.java
Labels: 기능

#399 fix: POST/user/refresh 반환코드 수정
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/test/java/in/koreatech/koin/acceptance/AuthApiTest.java
Labels: 버그

#404 fix: 건축, 기계, 메카 커리큘럼 링크 수정
  src/main/java/in/koreatech/koin/domain/dept/model/Dept.java
Labels: 버그

#417 refactor: 메뉴, 메뉴카테고리 Soft Delete로 변경
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/Menu.java
  src/main/java/in/koreatech/koin/domain/shop/model/MenuCategory.java
Labels: 리팩터링

#415 refactor: 스웨거 DTO 예시 수정
  src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopsResponse.java
Labels: 리팩터링

#414 fix: 코인 인증 메일 폼 만료 시간 수정
  src/main/resources/mail/student_register_certificate_number.html
Labels: Team User

#372 feat : 품절 알림 발송 구현
  src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
  src/main/java/in/koreatech/koin/domain/coop/model/DiningSoldOutEvent.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/global/domain/notification/repository/NotificationSubscribeRepository.java
  src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
  src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
Labels: 기능, Team Campus

#427 fix : 품절 알림 문구 수정
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
Labels: 버그, Team Campus

#430 fix: ClientAbortException handle
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
Labels: 버그

#431 feat: 리프레시 토큰 만료 기한을 14일에서 20초로 변경
  src/main/java/in/koreatech/koin/domain/user/model/UserToken.java
Labels: 기능

#432 feat: 리프레시 토큰 만료 기한 14일로 원상 복구
  src/main/java/in/koreatech/koin/domain/user/model/UserToken.java
Labels: 기능

#434 fix: 사장님 이메일 중복요청시 재요청 시간제한
  src/main/java/in/koreatech/koin/domain/owner/model/EmailVerifyRequest.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerInVerification.java
  src/main/java/in/koreatech/koin/domain/owner/repository/EmailVerifyRequestRedisRepository.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
  src/main/java/in/koreatech/koin/global/exception/RequestTooFastException.java
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
  src/test/java/in/koreatech/koin/support/DBInitializer.java
Labels: 버그

#443 fix: 상점 이벤트 알림을 구독한 유저에게만 알림
  src/main/java/in/koreatech/koin/domain/ownershop/EventArticleCreateShopEvent.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopEventListener.java
Labels: 버그

#438 feat: GET /admin/lands 기능 구현
  src/main/java/in/koreatech/koin/domain/admin/land/controller/AdminLandApi.java
  src/main/java/in/koreatech/koin/domain/admin/land/controller/AdminLandController.java
  src/main/java/in/koreatech/koin/domain/admin/land/dto/AdminLandResponse.java
  src/main/java/in/koreatech/koin/domain/admin/land/dto/AdminLandsResponse.java
  src/main/java/in/koreatech/koin/domain/admin/land/repository/AdminLandRepository.java
  src/main/java/in/koreatech/koin/domain/admin/land/service/AdminLandService.java
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
  src/main/java/in/koreatech/koin/domain/community/model/Criteria.java
  src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
  src/main/java/in/koreatech/koin/global/model/Criteria.java
  src/test/java/in/koreatech/koin/acceptance/AdminLandApiTest.java
Labels: 기능

#440 feat: 시간표 총 학점 조회
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: 기능

#454 Fix : 버스 남은시간 수정, 캐시만료로직 수정
  src/main/java/in/koreatech/koin/domain/bus/repository/ExpressBusCacheRepository.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
Labels: 리팩터링, Team Campus

#446 feat : 버스 버저닝 V2 updated_at 추가
  src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/dto/BusTimetableResponse.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
Labels: 기능, Team Campus

#457 fix: 시외버스 시간표 캐시확인로직 변경
  src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
Labels: 리팩터링, Team Campus

#445 feat: 도커파일 추가
  Dockerfile
Labels: 기능

#464 refactor: dto 수정
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerVerifyRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/VerifyPhoneRequest.java
Labels: 리팩터링

#466 fix: land dto 자료형 수정
  src/main/java/in/koreatech/koin/domain/land/dto/LandResponse.java
  src/main/java/in/koreatech/koin/domain/land/dto/LandsGroupResponse.java
  src/main/java/in/koreatech/koin/domain/land/dto/LandsResponse.java
  src/main/java/in/koreatech/koin/domain/land/model/Land.java
  src/test/java/in/koreatech/koin/acceptance/LandApiTest.java
Labels: 버그

#460 refactor: 사용자에게는 기본 메시지만 보이도록 예외 수정
  src/main/java/in/koreatech/koin/domain/bus/exception/ApiTypeNotFoundException.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusArrivalNodeNotFoundException.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusCacheNotFoundException.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusNotFoundException.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusOpenApiException.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusStationNotFoundException.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusTypeNotFoundException.java
  src/main/java/in/koreatech/koin/domain/community/exception/ArticleNotFoundException.java
  src/main/java/in/koreatech/koin/domain/coop/exception/MenuNotFoundException.java
  src/main/java/in/koreatech/koin/domain/land/exception/LandNotFoundException.java
  src/main/java/in/koreatech/koin/domain/member/exception/MemberNotFoundException.java
  src/main/java/in/koreatech/koin/domain/member/exception/TrackNotFoundException.java
  src/main/java/in/koreatech/koin/domain/owner/exception/AttachmentNotFoundException.java
  src/main/java/in/koreatech/koin/domain/owner/exception/DuplicationCertificationException.java
  src/main/java/in/koreatech/koin/domain/owner/exception/DuplicationCompanyNumberException.java
  src/main/java/in/koreatech/koin/domain/owner/exception/OwnerAttachmentNotFoundException.java
  src/main/java/in/koreatech/koin/domain/owner/exception/OwnerNotFoundException.java
  src/main/java/in/koreatech/koin/domain/owner/repository/OwnerAttachmentRepository.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/main/java/in/koreatech/koin/domain/ownershop/exception/EventArticleNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/exception/MenuCategoryNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/exception/MenuNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/exception/ShopCategoryMapNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/exception/ShopCategoryNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/exception/ShopImageNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/exception/ShopNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/exception/ShopOpenNotFoundException.java
  src/main/java/in/koreatech/koin/domain/timetable/exception/SemesterNotFoundException.java
  src/main/java/in/koreatech/koin/domain/timetable/exception/TimeTableNotFoundException.java
  src/main/java/in/koreatech/koin/domain/user/exception/DuplicationNicknameException.java
  src/main/java/in/koreatech/koin/domain/user/exception/UserNotFoundException.java
  src/main/java/in/koreatech/koin/domain/version/exception/VersionTypeNotFoundException.java
  src/main/java/in/koreatech/koin/global/auth/exception/AuthenticationException.java
  src/main/java/in/koreatech/koin/global/auth/exception/AuthorizationException.java
  src/main/java/in/koreatech/koin/global/domain/email/exception/DuplicationEmailException.java
  src/main/java/in/koreatech/koin/global/domain/email/exception/VerifyNotFoundException.java
  src/main/java/in/koreatech/koin/global/domain/notification/exception/NotificationSubscribeNotFoundException.java
  src/main/java/in/koreatech/koin/global/domain/notification/exception/SubscribeNotFoundException.java
  src/main/java/in/koreatech/koin/global/domain/upload/exception/ImageUploadDomainNotFoundException.java
  src/main/java/in/koreatech/koin/global/exception/DataNotFoundException.java
  src/main/java/in/koreatech/koin/global/exception/DuplicationException.java
  src/main/java/in/koreatech/koin/global/exception/ExternalServiceException.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
  src/main/java/in/koreatech/koin/global/naver/exception/DuplicationPhoneException.java
  src/main/java/in/koreatech/koin/global/naver/sms/NaverSmsException.java
Labels: 리팩터링

#476 fix: DB의 상점 설명이 null인 경우 예외처리
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
Labels: 버그

#477 feat : 회원 정보 수정에 비밀번호 수정 추가
  src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 기능, Team User

#480 fix : kcal, menu nullable 여부 수정
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
Labels: 버그

#475 fix: /bus/search 천안역에서 출발할 경우 Exception 발생 버그 수정
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
Labels: 버그, Team Campus

#479 feat: 상점 운영중 기준으로 정렬 및 is_event 필드 추가
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopsResponse.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopOpenRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
Labels: 기능, Team Business

#482 fix: 상점 수정시 배달금액 언더플로우 해결
  src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
  src/main/java/in/koreatech/koin/domain/shop/model/MenuOption.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
Labels: 버그, 기능, Team Business

#478 feat: 비밀번호 검증 api 작성
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordCheckRequest.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 기능, Team User

#489 fix: handler 추가 및 IAE 변경
  src/main/java/in/koreatech/koin/domain/user/repository/UserTokenRepository.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
Labels: 버그

#487 refactor: 모든 상점 조회 api 성능개선
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopOpen.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopOpenRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
Labels: 리팩터링

#493 fix: timezone 설정
  Dockerfile
Labels: 버그
