Repository BCSDLab/KOIN_API_V2, pull requests merged in 2024-07, with the labels that each got.

#642 Refactor: 사장님/어드민 상점 수정시 은행,계좌번호 추가
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopResponse.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
  src/main/resources/db/migration/V28__add_shop_bank_account_number.sql
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
  src/test/java/in/koreatech/koin/fixture/ShopFixture.java
Labels: 리팩터링

#651 Fix: 이모지 검증 추가
  src/main/java/in/koreatech/koin/domain/user/dto/StudentLoginRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserLoginRequest.java
  src/main/java/in/koreatech/koin/global/validation/EmojiValidator.java
  src/main/java/in/koreatech/koin/global/validation/NotEmoji.java
Labels: 버그

#660 fix: post timteable 조회 조건 변경
  src/main/java/in/koreatech/koin/domain/timetable/repository/LectureRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
Labels: 버그

#668 fix: 이모지 어노테이션 검증 수정
  src/main/java/in/koreatech/koin/global/validation/EmojiValidator.java
Labels: 버그

#654 fix: 어드민 사장님 페이지네이션 수정
  src/main/java/in/koreatech/koin/admin/user/dto/AdminNewOwnersResponse.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminOwnersResponse.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminOwnerRepository.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminUserRepository.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerIncludingShop.java
  src/main/java/in/koreatech/koin/domain/user/dto/StudentLoginRequest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
Labels: 버그

#671 feat: github workflow 추가
  .github/workflows/pick-reviewer.yml
  .github/workflows/pr-merged.yml
  .github/workflows/reviewer.json
Labels: 기능

#680 main<-develop 충돌 해결
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
Labels: 버그

#687 fix : timetableResponse 복구 및 LectureResponse Lecture id 삭제
  src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: 버그

#688 chore : Repository 수정 및 수정 코드 복구
  src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/LectureRepositoryV2.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: 버그

#689 feat: 조회시 프레임 없으면 생성
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: 기능

#639 feat: 이미지 업로드 시 알림
  src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
  src/main/java/in/koreatech/koin/domain/coop/model/DiningImageUploadEvent.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationSubscribeType.java
  src/main/java/in/koreatech/koin/global/domain/notification/repository/NotificationSubscribeRepository.java
  src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
Labels: Team Campus

#693 fix: 인증 요청 사장님 페이지네이션
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
Labels: 버그

#643 feat : 생협 운영시간 API 구현
  src/main/java/in/koreatech/koin/admin/coopShop/controller/AdminCoopShopApi.java
  src/main/java/in/koreatech/koin/admin/coopShop/controller/AdminCoopShopController.java
  src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopShopResponse.java
  src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopShopsResponse.java
  src/main/java/in/koreatech/koin/admin/coopShop/repository/AdminCoopShopRepository.java
  src/main/java/in/koreatech/koin/admin/coopShop/service/AdminCoopShopService.java
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopApi.java
  src/main/java/in/koreatech/koin/domain/coopshop/controller/CoopShopApi.java
  src/main/java/in/koreatech/koin/domain/coopshop/controller/CoopShopController.java
  src/main/java/in/koreatech/koin/domain/coopshop/dto/CoopShopResponse.java
  src/main/java/in/koreatech/koin/domain/coopshop/exception/CoopShopNotFoundException.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopOpen.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShop.java
  src/main/java/in/koreatech/koin/domain/coopshop/repository/CoopShopRepository.java
  src/main/java/in/koreatech/koin/domain/coopshop/service/CoopShopService.java
  src/main/resources/db/migration/V29__add_coop_shop_table.sql
  src/test/java/in/koreatech/koin/acceptance/CoopShopTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminCoopShopTest.java
  src/test/java/in/koreatech/koin/fixture/CoopShopFixture.java
Labels: 기능, Team Campus

#675 feat: 리뷰관련 기능 작성
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
  src/main/java/in/koreatech/koin/domain/shop/dto/CreateReviewRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyReviewRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewReportCategoryResponse.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewReportRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewResponse.java
  src/main/java/in/koreatech/koin/domain/shop/exception/ReviewNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopReview.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopReviewImage.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopReviewMenu.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopReviewReport.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopReviewReportCategory.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ReviewImageRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ReviewMenuRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopReviewImageRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopReviewMenuRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopReviewReportCategoryRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopReviewReportRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopReviewRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableCreateRequest.java
  src/main/resources/db/migration/V29__add_shop_review.sql
  src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
  src/test/java/in/koreatech/koin/fixture/ShopReviewFixture.java
  src/test/java/in/koreatech/koin/fixture/ShopReviewReportCategoryFixture.java
  src/test/java/in/koreatech/koin/fixture/ShopReviewReportFixture.java
  src/test/java/in/koreatech/koin/fixture/UserFixture.java
Labels: 기능, Team Business

#698 fix: flyway 버전 수정
  src/main/resources/db/migration/V30__add_shop_review.sql
Labels: 버그, Team Business

#709 fix : 생협 운영시간 정보에 학기 필드 semester 추가
  src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopShopResponse.java
  src/main/java/in/koreatech/koin/domain/coopshop/dto/CoopShopResponse.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShop.java
  src/main/resources/db/migration/V31__add_coopshop_semester.sql
  src/test/java/in/koreatech/koin/acceptance/CoopShopTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminCoopShopTest.java
  src/test/java/in/koreatech/koin/fixture/CoopShopFixture.java
Labels: 버그, Team Campus

#703 fix: User 인코딩 설정
  src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateRequest.java
  src/main/resources/db/migration/V32__alter_users_collation.sql
Labels: 버그

#710 fix : CoopShop 조회 시 CoopOpen 즉시로딩 수정
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopOpen.java
Labels: 버그

#711 fix : coopShop 조회 시 모든 CoopOpen이 즉시 조회되도록 수정
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopOpen.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShop.java
Labels: 버그, Team Campus

#708 fix: 시간표 프레임 삭제 관련 에러 수정
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
  src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
Labels: 버그, Team User

#714 feat: 시내버스 시간표
  src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/dto/CityBusTimetableResponse.java
  src/main/java/in/koreatech/koin/domain/bus/model/enums/CityBusDirection.java
  src/main/java/in/koreatech/koin/domain/bus/model/mongo/CityBusTimetable.java
  src/main/java/in/koreatech/koin/domain/bus/repository/CityBusTimetableRepository.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
  src/test/java/in/koreatech/koin/fixture/BusFixture.java
Labels: 기능, Team Business

#716 feat: 식단 좋아요/취소 기능 구현
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningLikeRequest.java
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
  src/main/java/in/koreatech/koin/domain/dining/exception/DuplicateLikeException.java
  src/main/java/in/koreatech/koin/domain/dining/exception/LikeNotFoundException.java
  src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
  src/main/java/in/koreatech/koin/domain/dining/model/DiningLikes.java
  src/main/java/in/koreatech/koin/domain/dining/repository/DiningLikesRepository.java
  src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
  src/main/resources/db/migration/V33_add_dining_like_table.sql
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
  src/test/java/in/koreatech/koin/fixture/DiningFixture.java
Labels: 기능, Team Campus

#719 fix: 식단 좋아요 사용자 인증 추가
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
  src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
  src/main/resources/db/migration/V33_add_dining_like_table.sql
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
Labels: 버그

#720 feat: 좋아요 여부 판단 isLiked 추가
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
  src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
Labels: 기능

#722 feat : shop_review 관련 FK 조건 CASCADE 수정
  src/main/resources/db/migration/V34__shop_reviews_restrict_change_cascade_.sql
  src/main/resources/db/migration/V35__shop_review_reports_restrict_change_cascade_.sql
  src/main/resources/db/migration/V36__shop_review_images_restrict_change_cascade_.sql
  src/main/resources/db/migration/V37__shop_review_menus_restrict_change_cascade_.sql
Labels: 버그

#641 refactor : 버스 API restTemplate 수정
  src/main/java/in/koreatech/koin/domain/bus/dto/CityBusApiResponse.java
  src/main/java/in/koreatech/koin/domain/bus/dto/CityBusRouteApiResponse.java
  src/main/java/in/koreatech/koin/domain/bus/dto/PublicOpenApiResponse.java
  src/main/java/in/koreatech/koin/domain/bus/dto/TmoneyOpenApiResponse.java
  src/main/java/in/koreatech/koin/domain/bus/util/CityBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/CityBusRouteClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/PublicExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/TmoneyExpressBusClient.java
  src/main/java/in/koreatech/koin/global/config/Resilience4jConfig.java
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
  src/test/java/in/koreatech/koin/acceptance/CircuitBreakerApiTest.java
Labels: 리팩터링, Team Campus

#726 feat: imageUrls가 null인 경우 빈 리스트로 초기화한다.
  src/main/java/in/koreatech/koin/domain/shop/dto/CreateReviewRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyReviewRequest.java
Labels: 기능, 리팩터링, Team Business

#727 fix: not main, main 시간표 프레임 동시 삭제 문제 해결
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
  src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
Labels: 버그

#731 fix : 시간표 프레임 삭제 동시성
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
Labels: 버그

#735 fix: 시간표 프레임 삭제 로직 수정
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
Labels: 버그

#744 fix: 식단 이미지 업로드 알림 운영시간 검사 추가
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
Labels: 버그
