Repository BCSDLab/KOIN_API_V2, pull requests merged in 2024-06, with the labels that each got.

#584 refactor: 전화번호 하이픈 제거
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordResetVerifySmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordUpdateSmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerRegisterByPhoneRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerSendSmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerSmsVerifyRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/VerifySmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
Labels: 리팩터링

#581 feat: Delete /admin/members/{id} api 추가
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
  src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
  src/main/java/in/koreatech/koin/domain/member/model/Member.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
Labels: 기능, Team Business

#585 feat: Admin으로 BCSDLab 기술스택 수정 기능
  src/main/java/in/koreatech/koin/admin/member/controller/AdminTrackApi.java
  src/main/java/in/koreatech/koin/admin/member/controller/AdminTrackController.java
  src/main/java/in/koreatech/koin/admin/member/dto/AdminTechStackRequest.java
  src/main/java/in/koreatech/koin/admin/member/dto/AdminTechStackResponse.java
  src/main/java/in/koreatech/koin/admin/member/exception/TechStackNotFoundException.java
  src/main/java/in/koreatech/koin/admin/member/repository/AdminTechStackRepository.java
  src/main/java/in/koreatech/koin/admin/member/service/AdminTrackService.java
  src/main/java/in/koreatech/koin/domain/member/model/TechStack.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminTrackApiTest.java
Labels: 기능, 온보딩

#591 Refactor: 대성 고속(Express) 천안역 확인 조건문 제거
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
Labels: 리팩터링, Team Campus

#589 Refactor : 도커 이미지 크기 간소화
  Dockerfile
Labels: 리팩터링

#579 feat : 서킷브레이커 구현
  build.gradle
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/main/java/in/koreatech/koin/domain/bus/util/BusScheduler.java
  src/main/java/in/koreatech/koin/domain/bus/util/CityBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/PublicExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/TmoneyExpressBusClient.java
  src/main/java/in/koreatech/koin/global/config/Resilience4jConfig.java
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
  src/test/java/in/koreatech/koin/acceptance/CircuitBreakerApiTest.java
  src/test/java/in/koreatech/koin/config/TestResilience4jConfig.java
  src/test/java/in/koreatech/koin/util/TestCircuitBreakerClient.java
Labels: 기능, Team Campus

#597 fix: 메뉴 리스트 파싱 로직 수정
  src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
Labels: 버그, Team Campus

#593 refactor: 기존 로그인 api 이메일 형식 검증 제거
  src/main/java/in/koreatech/koin/domain/user/dto/UserLoginRequest.java
Labels: 리팩터링

#588 fix: dto @NotNull 어노테이션 추가
  src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
Labels: 버그

#599 fix : 품절 알림 문구 점(.) 삭제
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
Labels: 버그, 리팩터링

#595 feat : put /admin/members/{id} api 추가
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
  src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
  src/main/java/in/koreatech/koin/domain/member/model/Member.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
Labels: Team Business

#605 hotfix: 비밀번호 검증 api 비밀번호 틀렸을시에 400 반환하는 것으로 수정
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 버그

#592 feat: timetable frame api 중 post, get, delete 구현
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableFrameCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableFrameResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/exception/TimetableFrameNotFoundException.java
  src/main/java/in/koreatech/koin/domain/timetable/model/TimetableFrame.java
  src/main/java/in/koreatech/koin/domain/timetable/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableFrameRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableLectureRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
  src/test/java/in/koreatech/koin/fixture/TimeTableV2Fixture.java
Labels: 기능

#594 feat: timetableFrame put, timetableLecture delete 구현 & reafactor: 기존 timetable delete, get 수정
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableControllerV2.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableFrameUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableFrameUpdateResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetable/exception/TimeTableNotFoundException.java
  src/main/java/in/koreatech/koin/domain/timetable/exception/TimetableLectureNotFoundException.java
  src/main/java/in/koreatech/koin/domain/timetable/exception/TimetableNotFoundException.java
  src/main/java/in/koreatech/koin/domain/timetable/model/Timetable.java
  src/main/java/in/koreatech/koin/domain/timetable/model/TimetableFrame.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/LectureRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableFrameRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableLectureRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/main/resources/db/migration/V16__add_timetable_frame.sql
  src/main/resources/db/migration/V17__insert_timetable_frame.sql
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
  src/test/java/in/koreatech/koin/fixture/TimetableFixture.java
Labels: 기능

#600 feat: POST /admin/members/{id}/undelete API 추가
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
  src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
  src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
  src/main/java/in/koreatech/koin/domain/member/model/Member.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
  src/test/java/in/koreatech/koin/fixture/MemberFixture.java
Labels: 기능, Team Business

#606 feat: Admin BCSDLab 트랙 API 구현
  src/main/java/in/koreatech/koin/admin/member/controller/AdminTrackApi.java
  src/main/java/in/koreatech/koin/admin/member/controller/AdminTrackController.java
  src/main/java/in/koreatech/koin/admin/member/dto/AdminTechStackRequest.java
  src/main/java/in/koreatech/koin/admin/member/dto/AdminTrackRequest.java
  src/main/java/in/koreatech/koin/admin/member/dto/AdminTrackSingleResponse.java
  src/main/java/in/koreatech/koin/admin/member/exception/TrackNameDuplicationException.java
  src/main/java/in/koreatech/koin/admin/member/repository/AdminMemberRepository.java
  src/main/java/in/koreatech/koin/admin/member/repository/AdminTechStackRepository.java
  src/main/java/in/koreatech/koin/admin/member/repository/AdminTrackRepository.java
  src/main/java/in/koreatech/koin/admin/member/service/AdminTrackService.java
  src/main/java/in/koreatech/koin/domain/member/model/TechStack.java
  src/main/java/in/koreatech/koin/domain/member/model/Track.java
  src/main/java/in/koreatech/koin/domain/member/repository/MemberRepository.java
  src/main/java/in/koreatech/koin/domain/member/service/TrackService.java
  src/test/java/in/koreatech/koin/acceptance/TrackApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminTrackApiTest.java
  src/test/java/in/koreatech/koin/fixture/TechStackFixture.java
  src/test/java/in/koreatech/koin/fixture/TrackFixture.java
Labels: 기능

#612 Feature: 어드민 복덕방 삭제
  src/main/java/in/koreatech/koin/admin/land/controller/AdminLandApi.java
  src/main/java/in/koreatech/koin/admin/land/controller/AdminLandController.java
  src/main/java/in/koreatech/koin/admin/land/repository/AdminLandRepository.java
  src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
  src/main/java/in/koreatech/koin/domain/land/model/Land.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
Labels: 기능

#614 refactor: 호환성 유지하기 위한 오너 회원가입 휴대폰번호 양식 롤백
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerRegisterRequest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
Labels: 리팩터링

#618 feat : coop_id 관련 flyway 추가
  src/main/resources/db/migration/V19__update_coop_id_with_user_email.sql
  src/main/resources/db/migration/V20__alter_coop_id_column_not_null.sql
Labels: 기능

#601 refactor: 시내버스 정류장 불일치 해결
  src/main/java/in/koreatech/koin/domain/bus/model/enums/BusStation.java
  src/main/java/in/koreatech/koin/domain/bus/model/enums/BusStationNode.java
  src/main/java/in/koreatech/koin/domain/bus/repository/CityBusRouteCacheRepository.java
  src/main/java/in/koreatech/koin/domain/bus/util/CityBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/CityBusRouteClient.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
Labels: 리팩터링, Team Campus

#611 fix : 품절 알림 처리 순서 수정
  src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
Labels: 버그

#622 refactor: sms회원가입 redis초기화 로직 변경
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerRegisterBySmsEvent.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
Labels: 버그

#624 fix: 상점 수정, 삭제시 운영 요일 형식 검증
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopController.java
  src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
  src/main/java/in/koreatech/koin/global/validation/DayOfWeekValidator.java
  src/main/java/in/koreatech/koin/global/validation/ValidDayOfWeek.java
Labels: 버그

#610 feat: 사업자번호, 아이디 중복검증 추가
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/dto/CompanyNumberCheckRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerAccountCheckExistsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerRegisterRequest.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
  src/test/java/in/koreatech/koin/fixture/UserFixture.java
Labels: 기능

#626 fix : 식단의 Kcal가 null 일 경우 0을 반환하도록 롤백
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
Labels: 버그

#629 fix: CityBusRoute 저장시 null 제외 추가
  src/main/java/in/koreatech/koin/domain/bus/util/CityBusRouteClient.java
Labels: 버그

#619 feat: 어드민권한 상점 관련 api작성
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopApi.java
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopController.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateMenuCategoryRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateMenuRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminMenuCategoriesResponse.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminMenuDetailResponse.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyMenuCategoryRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyMenuRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopMenuResponse.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminMenuCategoryMapRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminMenuCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminMenuDetailRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminMenuImageRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminMenuRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopCategoryMapRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopImageRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopOpenRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopRepository.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminShopRepository.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/main/java/in/koreatech/koin/domain/shop/model/Menu.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdmimShopApiTest.java
Labels: 기능

#621 feat: 어드민 82~86,89,90,93~95
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminLoginRequest.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminLoginResponse.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminOwnerResponse.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminOwnerUpdateRequest.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminOwnerUpdateResponse.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminOwnersResponse.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentUpdateRequest.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentUpdateResponse.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentsResponse.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminTokenRefreshRequest.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminTokenRefreshResponse.java
  src/main/java/in/koreatech/koin/admin/user/dto/OwnersCondition.java
  src/main/java/in/koreatech/koin/admin/user/dto/StudentsCondition.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminOwnerRepository.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminOwnerShopRedisRepository.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminStudentRepository.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminTokenRepository.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminUserRepository.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/main/java/in/koreatech/koin/domain/owner/model/Owner.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
  src/test/java/in/koreatech/koin/fixture/UserFixture.java
Labels: 기능

#627 feat: 어드민권한 상점, 카테고리 api작성
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopApi.java
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopController.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopCategoryRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopCategoryRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopCategoriesResponse.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopCategoryResponse.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopResponse.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopsResponse.java
  src/main/java/in/koreatech/koin/admin/shop/exception/ShopCategoryDuplicationException.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminEventArticleRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminMenuCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopRepository.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/Menu.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopCategory.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
Labels: 기능

#638 refactor: ADMIN 권한 추가
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadController.java
Labels: 버그

#644 fix: 상점 생성,수정 / 메뉴 추가,수정 버그 해결
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateMenuRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyMenuRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopRequest.java
  src/main/java/in/koreatech/koin/global/validation/UniqueIdValidator.java
  src/main/java/in/koreatech/koin/global/validation/UniqueUrlsValidator.java
Labels: 버그

#646 fix : flyway 버저닝 충돌 해결
  src/main/resources/db/migration/V21__add_timetable_frame.sql
  src/main/resources/db/migration/V22__insert_timetable_frame.sql
  src/main/resources/db/migration/V23__add_timetable_lecture.sql
  src/main/resources/db/migration/V24__insert_timetable_lecture.sql
  src/main/resources/db/migration/V25__alter_timetable_lecture_lectures_id.sql
  src/main/resources/db/migration/V26__alter_timetable_lecture_timetable_id.sql
  src/main/resources/db/migration/V27__delete_timetable_lecture_user_id_and_semester_id.sql
Labels: 버그

#648 fix : flyway 오류 수정
  src/main/resources/db/migration/V26__alter_timetable_lecture_timetable_id.sql
Labels: 버그
