Repository BCSDLab/KOIN_API_V2, pull requests merged in 2024-09, with the labels that each got.

#844 fix: searchkeyword 엔티티 컬럼 타입 명시
  src/main/java/in/koreatech/koin/domain/community/article/model/ArticleSearchKeyword.java
  src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
Labels: 버그

#846 fix: registeredAt 기준 정렬 수정
  src/main/java/in/koreatech/koin/domain/community/article/service/CommunityService.java
Labels: 버그

#848 refactor: 키워드 추천 api를 비로그인 api로 변경
  src/main/java/in/koreatech/koin/domain/community/keyword/controller/KeywordApi.java
  src/main/java/in/koreatech/koin/domain/community/keyword/controller/KeywordController.java
  src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
  src/test/java/in/koreatech/koin/acceptance/KeywordApiTest.java
Labels: 리팩터링

#855 fix: 많이 검색한 키워드 추천 api 테스트 응답 값 순서에 상관 없도록 수정
  src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
Labels: 버그

#850 fix : 생협 운영시간 학기를 "학기 중"으로 수정
  src/main/resources/db/migration/V51__update_coopshop_semester.sql
Labels: 버그, Team Campus

#852 feat: 리뷰작성, 리뷰신고 모니터링을 위한 슬랙으로 알림 발송
  src/main/java/in/koreatech/koin/domain/shop/model/ReviewEventListener.java
  src/main/java/in/koreatech/koin/domain/shop/model/ReviewRegisterEvent.java
  src/main/java/in/koreatech/koin/domain/shop/model/ReviewReportEvent.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
  src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotificationFactory.java
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
  src/test/resources/application.yml
Labels: 기능

#857 fix : 생협 운영시간 학기에서 "중" 삭제
  src/main/resources/db/migration/V52__update_coopshop_semester_typo.sql
Labels: 버그, Team Campus

#856 fix: registered_at 업데이트
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/java/in/koreatech/koin/global/config/LocalDateAttributeConverter.java
  src/main/resources/db/migration/V53__update_koreatech_articles_registered_at.sql
Labels: 버그

#859 refactor: 게시글 조회 속도 최적화
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/resources/db/migration/V54__create_index_registered_at_and_id.sql
Labels: 리팩터링

#865 fix: image_urls 에 @NotNull 예외처리
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateMenuRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyMenuRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopRequest.java
  src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/CreateReviewRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyReviewRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
Labels: 버그, Team Business

#866 refactor: 인기 게시글 조회 내부 로직 수정
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/ArticleResponse.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/ArticlesResponse.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/HotArticleItemResponse.java
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/article/model/redis/ArticleHit.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/redis/ArticleHitRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/redis/HotArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/scheduler/ArticleScheduler.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/test/java/in/koreatech/koin/acceptance/ArticleApiTest.java
Labels: 리팩터링

#867 refactor: 테스트 최적화
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/repository/MenuRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/ActivityApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ArticleApiTest.java
  src/test/java/in/koreatech/koin/acceptance/AuthApiTest.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
  src/test/java/in/koreatech/koin/acceptance/CircuitBreakerTest.java
  src/test/java/in/koreatech/koin/acceptance/CoopShopTest.java
  src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
  src/test/java/in/koreatech/koin/acceptance/KeywordApiTest.java
  src/test/java/in/koreatech/koin/acceptance/LandApiTest.java
  src/test/java/in/koreatech/koin/acceptance/MemberApiTest.java
  src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TrackApiTest.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
  src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminCoopShopTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminTrackApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
  src/test/java/in/koreatech/koin/fixture/MenuFixture.java
  src/test/java/in/koreatech/koin/fixture/ShopReviewFixture.java
  src/test/java/in/koreatech/koin/support/DBInitializer.java
  src/test/java/in/koreatech/koin/support/JsonAssertions.java
  src/test/resources/application.yml
Labels: 기능

#843 feat: AB테스트 구현 (완성)
  build.gradle
  src/main/java/in/koreatech/koin/admin/abtest/controller/AbtestApi.java
  src/main/java/in/koreatech/koin/admin/abtest/controller/AbtestController.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/AbtestAdminAssignRequest.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/AbtestAssignRequest.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/AbtestAssignResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/AbtestCloseRequest.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/AbtestDevicesResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/AbtestRequest.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/AbtestResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/AbtestUsersResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/AbtestsResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestAlreadyExistException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestAssignException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestAssignedUserException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestDuplicatedVariableException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestNotAssignedUserException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestNotFoundException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestNotInProgressException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestNotIncludeVariableException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestTitleIllegalArgumentException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestVariableCountNotFoundException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestVariableIllegalArgumentException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestVariableNotFoundException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestWinnerNotDecidedException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AccessHistoryNotFoundException.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/DeviceNotFoundException.java
  src/main/java/in/koreatech/koin/admin/abtest/model/Abtest.java
  src/main/java/in/koreatech/koin/admin/abtest/model/AbtestStatus.java
  src/main/java/in/koreatech/koin/admin/abtest/model/AbtestVariable.java
  src/main/java/in/koreatech/koin/admin/abtest/model/AccessHistory.java
  src/main/java/in/koreatech/koin/admin/abtest/model/AccessHistoryAbtestVariable.java
  src/main/java/in/koreatech/koin/admin/abtest/model/Device.java
  src/main/java/in/koreatech/koin/admin/abtest/model/redis/AbtestVariableAssign.java
  src/main/java/in/koreatech/koin/admin/abtest/model/redis/AbtestVariableCount.java
  src/main/java/in/koreatech/koin/admin/abtest/repository/AbtestRepository.java
  src/main/java/in/koreatech/koin/admin/abtest/repository/AbtestVariableAssignRepository.java
  src/main/java/in/koreatech/koin/admin/abtest/repository/AbtestVariableAssignTemplateRepository.java
  src/main/java/in/koreatech/koin/admin/abtest/repository/AbtestVariableCountRepository.java
  src/main/java/in/koreatech/koin/admin/abtest/repository/AbtestVariableRepository.java
  src/main/java/in/koreatech/koin/admin/abtest/repository/AccessHistoryAbtestVariableCustomRepository.java
  src/main/java/in/koreatech/koin/admin/abtest/repository/AccessHistoryAbtestVariableCustomRepositoryImpl.java
  src/main/java/in/koreatech/koin/admin/abtest/repository/AccessHistoryAbtestVariableRepository.java
  src/main/java/in/koreatech/koin/admin/abtest/repository/AccessHistoryRepository.java
  src/main/java/in/koreatech/koin/admin/abtest/repository/DeviceRepository.java
  src/main/java/in/koreatech/koin/admin/abtest/scheduler/AbtestScheduler.java
  src/main/java/in/koreatech/koin/admin/abtest/service/AbtestService.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/global/config/RedisConfig.java
  src/main/java/in/koreatech/koin/global/config/WebConfig.java
  src/main/java/in/koreatech/koin/global/useragent/UserAgent.java
  src/main/java/in/koreatech/koin/global/useragent/UserAgentArgumentResolver.java
  src/main/java/in/koreatech/koin/global/useragent/UserAgentInfo.java
  src/main/resources/db/migration/V55__add_abtest_tables.sql
  src/main/resources/db/migration/V56__add_abtest_tables_fk.sql
  src/test/java/in/koreatech/koin/acceptance/AbtestApiTest.java
  src/test/java/in/koreatech/koin/fixture/AbtestFixture.java
  src/test/java/in/koreatech/koin/fixture/DeviceFixture.java
  src/test/java/in/koreatech/koin/fixture/UserFixture.java
Labels: 기능

#889 feat : datadog 로깅을 위한 logback 수정
  src/main/resources/logback-spring.xml
Labels: 기능

#891 feat : datadog 로깅을 위한 logback 수정
  build.gradle
  src/main/java/in/koreatech/koin/global/exception/ErrorResponse.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
  src/main/resources/logback-spring.xml
Labels: 기능

#892 refactor: 상점 리뷰 등록, 신고시 알림 채널 변경
  src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotificationFactory.java
  src/test/resources/application.yml
Labels: 리팩터링

#890 fix: 메인시간표 필수로 수정
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
Labels: 버그

#849 feat: 상점 리뷰 어드민 테스트 코드
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopController.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopReviewApiTest.java
Labels: 기능

#898 fix: 쿼리 버그 수정
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
Labels: 버그

#896 feat: 식단 검색 1년 -> 전체기간으로 변경
  src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
  src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
Labels: 기능

#899 fix: Request에 Size Validate 추가
  src/main/java/in/koreatech/koin/admin/abtest/controller/AbtestApi.java
  src/main/java/in/koreatech/koin/admin/abtest/controller/AbtestController.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/request/AbtestAdminAssignRequest.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/request/AbtestAssignRequest.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/request/AbtestCloseRequest.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/request/AbtestRequest.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/response/AbtestAssignResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/response/AbtestDevicesResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/response/AbtestResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/response/AbtestUsersResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/dto/response/AbtestsResponse.java
  src/main/java/in/koreatech/koin/admin/abtest/model/Abtest.java
  src/main/java/in/koreatech/koin/admin/abtest/service/AbtestService.java
Labels: 버그, Team Campus

#832 feat : 호출제어 대체 기능(fallBack) 추가 및 리팩터링
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/main/java/in/koreatech/koin/domain/bus/util/BusScheduler.java
  src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusFactory.java
  src/main/java/in/koreatech/koin/domain/bus/util/city/CityBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/city/CityBusRouteClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/express/ExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/express/ExpressBusService.java
  src/main/java/in/koreatech/koin/domain/bus/util/express/PublicExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/express/StaticExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/express/TmoneyExpressBusClient.java
  src/main/java/in/koreatech/koin/global/config/Resilience4jConfig.java
  src/main/java/in/koreatech/koin/global/domain/callcontoller/CallControllable.java
  src/main/java/in/koreatech/koin/global/domain/callcontoller/CallController.java
  src/main/java/in/koreatech/koin/global/reflection/ReflectionUtils.java
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
  src/test/java/in/koreatech/koin/acceptance/CircuitBreakerApiTest.java
Labels: 기능, Team Campus

#902 refactor: 공지사항 알림 api admin만 호출 할 수 있게 변경
  src/main/java/in/koreatech/koin/domain/community/keyword/controller/KeywordApi.java
  src/main/java/in/koreatech/koin/domain/community/keyword/controller/KeywordController.java
  src/test/java/in/koreatech/koin/acceptance/KeywordApiTest.java
Labels: 기능

#903 refactor: 많이 조회하는 키워드 테이블 제약 조건 추가
  src/main/java/in/koreatech/koin/domain/community/article/model/ArticleSearchKeyword.java
  src/main/java/in/koreatech/koin/domain/community/article/model/ArticleSearchKeywordIpMap.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleSearchKeywordIpMapRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleSearchKeywordRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/main/resources/db/migration/V60__alter_search_keywords_and_ip_map_unique_cascade.sql
Labels: 기능

#907 feat: ab테스트 편입 api 단일화
  src/main/java/in/koreatech/koin/admin/abtest/controller/AbtestApi.java
  src/main/java/in/koreatech/koin/admin/abtest/controller/AbtestController.java
  src/main/java/in/koreatech/koin/admin/abtest/exception/AbtestAssignedUserException.java
  src/main/java/in/koreatech/koin/admin/abtest/repository/AccessHistoryAbtestVariableCustomRepositoryImpl.java
  src/main/java/in/koreatech/koin/admin/abtest/service/AbtestService.java
  src/test/java/in/koreatech/koin/acceptance/AbtestApiTest.java
Labels: 기능

#900 feat : 강제 업데이트 api 구현
  src/main/java/in/koreatech/koin/admin/version/controller/AdminVersionApi.java
  src/main/java/in/koreatech/koin/admin/version/controller/AdminVersionController.java
  src/main/java/in/koreatech/koin/admin/version/dto/AdminVersionHistoryResponse.java
  src/main/java/in/koreatech/koin/admin/version/dto/AdminVersionResponse.java
  src/main/java/in/koreatech/koin/admin/version/dto/AdminVersionUpdateRequest.java
  src/main/java/in/koreatech/koin/admin/version/dto/AdminVersionsResponse.java
  src/main/java/in/koreatech/koin/admin/version/repository/AdminVersionRepository.java
  src/main/java/in/koreatech/koin/admin/version/service/AdminVersionService.java
  src/main/java/in/koreatech/koin/domain/version/controller/VersionApi.java
  src/main/java/in/koreatech/koin/domain/version/controller/VersionController.java
  src/main/java/in/koreatech/koin/domain/version/dto/VersionMessageResponse.java
  src/main/java/in/koreatech/koin/domain/version/model/Version.java
  src/main/java/in/koreatech/koin/domain/version/model/VersionContent.java
  src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
  src/main/java/in/koreatech/koin/domain/version/repository/VersionContentRepository.java
  src/main/java/in/koreatech/koin/domain/version/repository/VersionRepository.java
  src/main/java/in/koreatech/koin/domain/version/service/VersionService.java
  src/main/resources/db/migration/V61__alter_version_table.sql
  src/main/resources/db/migration/V62__insert_version_content.sql
  src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminVersionApiTest.java
  src/test/java/in/koreatech/koin/fixture/VersionFixture.java
Labels: 기능, Team User

#910 fix : version 테이블의 is_previous 컬럼 자료형 수정
  src/main/java/in/koreatech/koin/domain/version/model/Version.java
  src/main/resources/db/migration/V63__alter_table_versions_alter_column_is_previous.sql
Labels: 버그

#912 fix: 혜택카테고리 및 혜택상점 어드민 제한
  src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitApi.java
  src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitController.java
Labels: 버그

#909 refactor: Swagger 한글 Example value 영어로 수정
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureUpdateRequest.java
Labels: 리팩터링, Team User

#915 refactor: ios가 받는 fcm에 schemeUri 추가
  src/main/java/in/koreatech/koin/global/fcm/FcmClient.java
Labels: 기능

#913 feat: 로그인 여부 확인 API
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserAccessTokenRequest.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 기능

#901 refactor: 모든 상점 조회 API 성능최적화
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopsResponse.java
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopsResponseV2.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
  src/main/java/in/koreatech/koin/domain/shop/repository/redis/ShopsRedisRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/dto/ShopCustomRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/dto/ShopInfo.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/main/java/in/koreatech/koin/global/scheduler/CacheShopsScheduler.java
Labels: 리팩터링

#918 feat: 모든 상점 조회 opens필드 제거
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopsResponseV2.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
Labels: 리팩터링

#920 refactor : version의 content 필드를 배열에서 문자열로 변경
  src/main/java/in/koreatech/koin/admin/version/dto/AdminVersionHistoryResponse.java
  src/main/java/in/koreatech/koin/admin/version/dto/AdminVersionResponse.java
  src/main/java/in/koreatech/koin/admin/version/dto/AdminVersionUpdateRequest.java
  src/main/java/in/koreatech/koin/admin/version/dto/AdminVersionsResponse.java
  src/main/java/in/koreatech/koin/domain/version/controller/VersionApi.java
  src/main/java/in/koreatech/koin/domain/version/controller/VersionController.java
  src/main/java/in/koreatech/koin/domain/version/dto/VersionMessageResponse.java
  src/main/java/in/koreatech/koin/domain/version/model/Version.java
  src/main/java/in/koreatech/koin/domain/version/model/VersionContent.java
  src/main/java/in/koreatech/koin/domain/version/repository/VersionContentRepository.java
  src/main/java/in/koreatech/koin/domain/version/service/VersionService.java
  src/main/resources/db/migration/V65__alter_version_table_and_delete_content_table.sql
  src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminVersionApiTest.java
  src/test/java/in/koreatech/koin/fixture/VersionFixture.java
Labels: 리팩터링, Team User

#922 feat : TimetableLecture Response 컬럼 추가 / TimetableFrame 생성 시 이름 지정 가능
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableFrameCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableFrameUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableFrameUpdateResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
  src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
Labels: 기능, Team User

#925 hotfix: 모든 상점 조회시 삭제된 리뷰는 통계에 포함 안되도록 변경
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/dto/ShopCustomRepository.java
Labels: 버그

#926 hotfix내용을 develop브랜치에 적용하기 위한 PR
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/dto/ShopCustomRepository.java
Labels: 버그

#930 refactor: slack 알림발송 추가
  src/main/resources/logback-spring.xml
Labels: 리팩터링
