Repository BCSDLab/KOIN_API_V2, pull requests merged in 2024-08, with the labels that each got.

#743 fix: DELETE/timetable 동시성 에러
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: 버그

#751 refactor: 모든 상점 조회시 필터 유효성 검사 추가
  src/main/java/in/koreatech/koin/domain/shop/dto/CreateReviewRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyReviewRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewReportRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopsFilterCriteria.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopsFilterCriteriaConverter.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopReview.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/main/java/in/koreatech/koin/global/config/WebConfig.java
  src/main/resources/db/migration/V40__alter_review_content_nullable_.sql
  src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
Labels: 리팩터링

#740 feat : API 다중화를 위한 호출 제어 모듈 구현
  src/main/java/in/koreatech/koin/domain/bus/util/BusScheduler.java
  src/main/java/in/koreatech/koin/domain/bus/util/CityBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/CityBusRouteClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusFactory.java
  src/main/java/in/koreatech/koin/domain/bus/util/PublicExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/util/TmoneyExpressBusClient.java
  src/main/java/in/koreatech/koin/global/config/Resilience4jConfig.java
  src/main/java/in/koreatech/koin/global/domain/callcontoller/CallControlInfo.java
  src/main/java/in/koreatech/koin/global/domain/callcontoller/CallControllable.java
  src/main/java/in/koreatech/koin/global/reflection/ReflectionUtils.java
  src/main/java/in/koreatech/koin/global/reflection/exception/ClassNotFoundException.java
  src/main/java/in/koreatech/koin/global/reflection/exception/MethodNotFoundException.java
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
  src/test/java/in/koreatech/koin/acceptance/CircuitBreakerTest.java
Labels: 기능, Team Campus

#756 feat: 리뷰 조회 API 정렬 기능 추가
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ReviewsSortCriteria.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopMyReviewsResponse.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewsResponse.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopReview.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopReviewRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
  src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
  src/test/java/in/koreatech/koin/config/FixedDate.java
  src/test/java/in/koreatech/koin/config/FixedDateAspect.java
  src/test/java/in/koreatech/koin/config/TestTimeConfig.java
  src/test/java/in/koreatech/koin/fixture/ShopReviewFixture.java
Labels: 기능, Team Business

#762 refactor: 상점 조회 V2 삭제된 리뷰는 제외하도록 변경
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopsResponseV2.java
Labels: 리팩터링, Team Business

#767 fix: 캠퍼스팀 안 쓰는 컬럼 삭제 - 식단에 price 컬럼 추가
  src/main/resources/db/migration/V41__add_dining_menus_price_column.sql
Labels: 버그, Team Campus

#764 feat: 계절학기 빈 리스트로 반환
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: 기능, Team User

#778 fix: timetable에 null 처리 로직 추가
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
Labels: 버그

#780 feat: 게시글 조회 api 응답 수정
  src/main/java/in/koreatech/koin/domain/community/dto/ArticleResponse.java
  src/main/java/in/koreatech/koin/domain/community/dto/ArticlesResponse.java
  src/main/java/in/koreatech/koin/domain/community/dto/HotArticleItemResponse.java
  src/main/java/in/koreatech/koin/domain/community/repository/BoardRepository.java
  src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
  src/main/java/in/koreatech/koin/global/model/Criteria.java
  src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
Labels: 리팩터링, Team Campus

#773 feat: 안쓰는 테이블, 컬럼 삭제
  src/main/resources/db/migration/V43__drop_unused_tables_and_column.sql
Labels: 리팩터링

#787 refactor: api path 변경
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
  src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
Labels: 리팩터링

#789 feat: 알림 키워드 생성 삭제
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
  src/main/java/in/koreatech/koin/domain/community/dto/ArticleKeywordCreateRequest.java
  src/main/java/in/koreatech/koin/domain/community/dto/ArticleKeywordResponse.java
  src/main/java/in/koreatech/koin/domain/community/exception/ArticleKeywordUserMapNotFoundException.java
  src/main/java/in/koreatech/koin/domain/community/exception/KeywordDuplicationException.java
  src/main/java/in/koreatech/koin/domain/community/exception/KeywordLimitExceededException.java
  src/main/java/in/koreatech/koin/domain/community/model/ArticleKeyword.java
  src/main/java/in/koreatech/koin/domain/community/model/ArticleKeywordUserMap.java
  src/main/java/in/koreatech/koin/domain/community/repository/ArticleKeywordRepository.java
  src/main/java/in/koreatech/koin/domain/community/repository/ArticleKeywordUserMapRepository.java
  src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
  src/main/resources/db/migration/V44__add_keyword_notification.sql
  src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
  src/test/java/in/koreatech/koin/fixture/ArticleFixture.java
Labels: 기능, Team Campus

#791 fix: last used at 엔티티 상에 타입 명시
  src/main/java/in/koreatech/koin/domain/community/model/ArticleKeyword.java
Labels: 버그

#792 refactor: refreshToken 기간 변경
  src/main/java/in/koreatech/koin/domain/user/model/UserToken.java
Labels: 리팩터링, Team User

#793 fix: v1 시간표 조회 api에서 커스텀 시간표 조회할 때 에러 해결
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
Labels: 버그

#788 feat: 게시글 검색
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
  src/main/java/in/koreatech/koin/domain/community/dto/ArticlesResponse.java
  src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
  src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
Labels: 기능

#806 hotfix: 게시판 페이징 미적용 버그 수정
  src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/repository/BoardRepository.java
  src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
  src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
Labels: 버그

#805 feat: 상점 리뷰 및 신고 조회, 신고에 따른 처리 API
  build.gradle
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopApi.java
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopController.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopReviewReportStatusRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopsReviewsResponse.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopReviewCustomRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopReviewCustomRepositoryImpl.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopReviewRepository.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopReviewReport.java
  src/main/java/in/koreatech/koin/global/config/QueryDslConfig.java
Labels: 기능

#803 feat: 리뷰 조회 API 응답에 신고 여부 필드 추가
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
  src/main/java/in/koreatech/koin/domain/shop/dto/CreateReviewRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyReviewRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewsResponse.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopsResponseV2.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopReviewRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
  src/main/java/in/koreatech/koin/global/validation/NotBlankElement.java
  src/main/java/in/koreatech/koin/global/validation/NotBlankElementValidator.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
Labels: 기능, Team Business

#808 feat: 영양사 월간 조회 검색 기능 구현
  src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsResponse.java
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningSearchResponse.java
  src/main/java/in/koreatech/koin/domain/dining/model/DiningPlace.java
  src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
  src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
  src/test/java/in/koreatech/koin/fixture/DiningFixture.java
Labels: 기능

#810 fix : fcm 알림의 버전 분리
  src/main/java/in/koreatech/koin/global/domain/test/controller/TestController.java
  src/main/java/in/koreatech/koin/global/fcm/FcmClient.java
Labels: 버그

#814 fix: 상점 생성, 수정시 이미지 url의 요소가 공백인 경우 예외처리
  src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
Labels: 버그

#821 fix: 리뷰 신고 변경 API의 dto필드 NotBlank에서 NotNull로 변경
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopReviewReportStatusRequest.java
Labels: 버그

#819 feat: 학기 반환 순서 변경
  src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterCheckResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: Team User

#826 fix: timetable dto에서 유효성 검사 추가
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
Labels: 버그

#829 feat: 게시글 조회 응답 필드 추가 및 로직 오류 수정
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
  src/main/java/in/koreatech/koin/domain/community/dto/ArticleResponse.java
  src/main/java/in/koreatech/koin/domain/community/exception/ArticleBoardMisMatchException.java
  src/main/java/in/koreatech/koin/domain/community/exception/BoardNotFoundException.java
  src/main/java/in/koreatech/koin/domain/community/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/repository/BoardRepository.java
  src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
  src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
Labels: 기능, Team Campus

#823 fix: vaild 처리 안되는 오류 해결
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateMenuRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyMenuRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopRequest.java
  src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
  src/main/java/in/koreatech/koin/domain/shop/exception/MenuIllegalSingleException.java
  src/main/java/in/koreatech/koin/global/validation/SingleMenuPrice.java
  src/main/java/in/koreatech/koin/global/validation/SingleMenuPriceValidator.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
Labels: 버그, Team Business

#833 rollback: 성능 향상을 위해 게시글 조인 쿼리 제거
  src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
Labels: 버그

#830 feat: boards, notice_articles 테이블 수정 flyway 추가
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
  src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
  src/main/java/in/koreatech/koin/domain/community/dto/ArticleResponse.java
  src/main/java/in/koreatech/koin/domain/community/dto/ArticlesResponse.java
  src/main/java/in/koreatech/koin/domain/community/dto/HotArticleItemResponse.java
  src/main/java/in/koreatech/koin/domain/community/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/model/ArticleAttachment.java
  src/main/java/in/koreatech/koin/domain/community/model/ArticleViewLog.java
  src/main/java/in/koreatech/koin/domain/community/model/Board.java
  src/main/java/in/koreatech/koin/domain/community/model/BoardTag.java
  src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/repository/ArticleViewLogRepository.java
  src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
  src/main/java/in/koreatech/koin/global/config/HashAttributeConverter.java
  src/main/java/in/koreatech/koin/global/validation/SingleMenuPrice.java
  src/main/resources/db/migration/V46__alter_boards_and_article_notices.sql
  src/main/resources/db/migration/V47__insert_board_to_boards.sql
  src/main/resources/db/migration/V48__add_article_attachments.sql
  src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
  src/test/java/in/koreatech/koin/fixture/ArticleFixture.java
  src/test/java/in/koreatech/koin/fixture/BoardFixture.java
Labels: 리팩터링

#835 fix: Local Date 컨버터 추가
  src/main/java/in/koreatech/koin/domain/community/model/Article.java
  src/main/java/in/koreatech/koin/global/config/LocalDateAttributeConverter.java
Labels: 버그

#836 fix: column definition 추가
  src/main/java/in/koreatech/koin/domain/community/model/Article.java
Labels: 버그

#838 fix: fomatter 수정
  src/main/java/in/koreatech/koin/global/config/LocalDateAttributeConverter.java
Labels: 버그

#840 fix: is_notice 업데이트 flyway 추가
  src/main/resources/db/migration/V49__update_article_is_notice.sql
Labels: 버그

#842 fix: LocalDateAttributeConverter 포맷 추가
  src/main/java/in/koreatech/koin/domain/community/model/Article.java
  src/main/java/in/koreatech/koin/global/config/LocalDateAttributeConverter.java
Labels: 버그
