Repository BCSDLab/KOIN_API_V2, pull requests merged in 2024-03, with the labels that each got.

#191 fix: 버전 매핑 에러 수정
  src/main/java/in/koreatech/koin/domain/version/dto/VersionResponse.java
  src/main/java/in/koreatech/koin/domain/version/exception/VersionException.java
  src/main/java/in/koreatech/koin/domain/version/exception/VersionTypeNotFoundException.java
  src/main/java/in/koreatech/koin/domain/version/model/Version.java
  src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
  src/main/java/in/koreatech/koin/domain/version/repository/VersionRepository.java
  src/main/java/in/koreatech/koin/domain/version/service/VersionService.java
  src/main/java/in/koreatech/koin/global/config/ClockConfig.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
  src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
Labels: 버그

#194 feat: 이메일 중복 체크
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/EmailCheckExistsRequest.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 기능, 온보딩

#192 feat : 강의 목록 조회(학기별)
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/exception/SemesterNotFoundException.java
  src/main/java/in/koreatech/koin/domain/timetable/model/Lecture.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/LectureRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: 온보딩

#185 feat: 버스 남은 시간 조회 - 셔틀버스, 등하교 버스
  build.gradle
  src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/dto/BusRemainTimeResponse.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusArrivalNodeNotFoundException.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusIllegalArrivalTime.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusIllegalStation.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusNotFoundException.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusStationNotFoundException.java
  src/main/java/in/koreatech/koin/domain/bus/exception/BusTypeNotFoundException.java
  src/main/java/in/koreatech/koin/domain/bus/model/BusCourse.java
  src/main/java/in/koreatech/koin/domain/bus/model/BusRemainTime.java
  src/main/java/in/koreatech/koin/domain/bus/model/BusStation.java
  src/main/java/in/koreatech/koin/domain/bus/model/BusType.java
  src/main/java/in/koreatech/koin/domain/bus/model/Route.java
  src/main/java/in/koreatech/koin/domain/bus/repository/BusRepository.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/main/java/in/koreatech/koin/domain/community/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/model/ArticleViewLog.java
  src/main/java/in/koreatech/koin/domain/community/model/Comment.java
  src/main/java/in/koreatech/koin/domain/owner/model/Owner.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerAttachment.java
  src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
  src/main/java/in/koreatech/koin/domain/user/model/Student.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
Labels: 기능

#196 feat : 학기 조회(전학기)
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/model/Semester.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/SemesterRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: 기능, 온보딩

#199 feat : 사장님 식당 생성, 특정 상점 조회 API구현
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopApi.java
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopContoller.java
  src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
  src/main/java/in/koreatech/koin/domain/shop/exception/ShopCategoryMapNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/exception/ShopCategoryNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/exception/ShopImageNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/exception/ShopNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/exception/ShopOpenNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopCategory.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopCategoryMap.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopImage.java
  src/main/java/in/koreatech/koin/domain/shop/model/ShopOpen.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopCategoryMapRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopCategoryRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopImageRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopOpenRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
Labels: 기능, 온보딩

#189 feat: 닉네임 중복 체크
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/NicknameCheckExistsRequest.java
  src/main/java/in/koreatech/koin/domain/user/exception/DuplicationNicknameException.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 기능, 온보딩

#193 feat : 식단 Api 구현
  build.gradle
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
  src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
  src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
  src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
Labels: 온보딩

#208 feat : 특정상점 전체메뉴조회 api작성
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
  src/main/java/in/koreatech/koin/domain/shop/dto/MenuDetailResponse.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
Labels: 기능

#210 feat: Presigned URL 구현
  build.gradle
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopApi.java
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopController.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
  src/main/java/in/koreatech/koin/domain/timetable/model/Semester.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/global/config/AwsSesConfig.java
  src/main/java/in/koreatech/koin/global/config/S3Config.java
  src/main/java/in/koreatech/koin/global/config/WebConfig.java
  src/main/java/in/koreatech/koin/global/domain/slack/service/SlackService.java
  src/main/java/in/koreatech/koin/global/domain/upload/controller/ImageUploadDomainEnumConverter.java
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadController.java
  src/main/java/in/koreatech/koin/global/domain/upload/dto/UploadUrlRequest.java
  src/main/java/in/koreatech/koin/global/domain/upload/dto/UploadUrlResponse.java
  src/main/java/in/koreatech/koin/global/domain/upload/exception/ImageUploadDomainNotFoundException.java
  src/main/java/in/koreatech/koin/global/domain/upload/model/ImageUploadDomain.java
  src/main/java/in/koreatech/koin/global/domain/upload/service/UploadService.java
  src/main/java/in/koreatech/koin/global/s3/S3Utils.java
  src/main/resources/application-test.yml
  src/test/java/in/koreatech/koin/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
  src/test/java/in/koreatech/koin/global/domain/upload/UploadServiceTest.java
Labels: 기능

#211 refactor: passwordEncoder 활용하도록 수정
  build.gradle
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/global/config/PasswordConfig.java
  src/test/java/in/koreatech/koin/acceptance/AuthApiTest.java
Labels: 버그

#212 feat: 시간표 기능 구현
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetable/exception/TimeTableNotFoundException.java
  src/main/java/in/koreatech/koin/domain/timetable/model/TimeTable.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/SemesterRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
Labels: 기능

#227 feat: 파일 단건 업로드 구현
  src/main/java/in/koreatech/koin/global/auth/JwtProvider.java
  src/main/java/in/koreatech/koin/global/config/AwsSesConfig.java
  src/main/java/in/koreatech/koin/global/config/S3Config.java
  src/main/java/in/koreatech/koin/global/config/SwaggerConfig.java
  src/main/java/in/koreatech/koin/global/domain/slack/service/SlackService.java
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadController.java
  src/main/java/in/koreatech/koin/global/domain/upload/dto/UploadFileResponse.java
  src/main/java/in/koreatech/koin/global/domain/upload/dto/UploadUrlResponse.java
  src/main/java/in/koreatech/koin/global/domain/upload/service/UploadService.java
  src/main/java/in/koreatech/koin/global/s3/S3Utils.java
  src/main/resources/application-test.yml
  src/test/java/in/koreatech/koin/global/domain/upload/UploadServiceTest.java
Labels: 기능

#229 feat: 파일 다중 업로드 구현
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadController.java
  src/main/java/in/koreatech/koin/global/domain/upload/dto/UploadFilesResponse.java
  src/main/java/in/koreatech/koin/global/domain/upload/service/UploadService.java
Labels: 기능

#231 feat: 영양사 권한 추가
  src/main/java/in/koreatech/koin/domain/user/model/UserType.java
Labels: 기능, Team Campus

#215 fix: 복덕방 전제 조회 응답 객체 미스매치 수정
  src/main/java/in/koreatech/koin/domain/activity/dto/ActivitiesResponse.java
  src/main/java/in/koreatech/koin/domain/activity/dto/ActivityResponse.java
  src/main/java/in/koreatech/koin/domain/land/controller/LandApi.java
  src/main/java/in/koreatech/koin/domain/land/controller/LandController.java
  src/main/java/in/koreatech/koin/domain/land/dto/LandResponse.java
  src/main/java/in/koreatech/koin/domain/land/dto/LandsGroupResponse.java
  src/main/java/in/koreatech/koin/domain/land/dto/LandsResponse.java
  src/main/java/in/koreatech/koin/domain/land/service/LandService.java
  src/test/java/in/koreatech/koin/acceptance/LandApiTest.java
  src/test/java/in/koreatech/koin/global/domain/upload/UploadServiceTest.java
Labels: 버그

#232 feat: FCM 설정
  .github/CODEOWNERS
  .gitignore
  build.gradle
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/EmailCheckExistsRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/NicknameCheckExistsRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/NotificationPermitRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/NotificationStatusResponse.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserTokenRefreshRequest.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/global/config/AsyncConfig.java
  src/main/java/in/koreatech/koin/global/domain/notification/Notification.java
  src/main/java/in/koreatech/koin/global/domain/notification/NotificationRepository.java
  src/main/java/in/koreatech/koin/global/domain/notification/NotificationService.java
  src/main/java/in/koreatech/koin/global/domain/notification/NotificationType.java
  src/main/java/in/koreatech/koin/global/fcm/FcmClient.java
  src/main/java/in/koreatech/koin/global/fcm/FcmConfig.java
  src/main/resources/application-test.yml
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__add_notification.sql
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 기능

#240 feat: 상점사장님이 특정 상점을 조회하는 api작성
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopApi.java
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopController.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/global/auth/AuthArgumentResolver.java
  src/main/java/in/koreatech/koin/global/auth/JwtProvider.java
  src/main/java/in/koreatech/koin/global/auth/exception/AuthException.java
  src/main/java/in/koreatech/koin/global/auth/exception/AuthenticationException.java
  src/main/java/in/koreatech/koin/global/auth/exception/AuthorizationException.java
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
Labels: 기능

#238 feat : 영양사 품절 정보 입력
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopApi.java
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopController.java
  src/main/java/in/koreatech/koin/domain/coop/dto/SoldOutRequest.java
  src/main/java/in/koreatech/koin/domain/coop/exception/MenuNotFoundException.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
  src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
  src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
  src/main/resources/db/migration/V3__alter_diningmenus_soldout.sql
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
Labels: 기능, Team Campus

#244 feat: 사장님 회원가입
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerRegisterRequest.java
  src/main/java/in/koreatech/koin/domain/owner/exception/DuplicationCompanyNumberException.java
  src/main/java/in/koreatech/koin/domain/owner/model/Owner.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerAttachment.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerEmailRequestEvent.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerRegisterEvent.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerShop.java
  src/main/java/in/koreatech/koin/domain/owner/repository/OwnerAttachmentRepository.java
  src/main/java/in/koreatech/koin/domain/owner/repository/OwnerInVerificationRedisRepository.java
  src/main/java/in/koreatech/koin/domain/owner/repository/OwnerRepository.java
  src/main/java/in/koreatech/koin/domain/owner/repository/OwnerShopRedisRepository.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/main/java/in/koreatech/koin/global/config/RestTemplateConfig.java
  src/main/java/in/koreatech/koin/global/domain/slack/SlackClient.java
  src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotification.java
  src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotificationFactory.java
  src/main/java/in/koreatech/koin/global/domain/slack/service/SlackService.java
  src/main/resources/application-test.yml
  src/main/resources/db/migration/V5__update_owners_table.sql
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
Labels: 기능

#245 feature: 상점 사장님 관련 모든 GET API를 작성했습니다.
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopApi.java
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopController.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/dto/MenuCategoriesResponse.java
  src/main/java/in/koreatech/koin/domain/shop/dto/MenuDetailResponse.java
  src/main/java/in/koreatech/koin/domain/shop/repository/ShopRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
Labels: 기능, Team Business

#246 fix: 게시판 공지사항 판단 로직 수정
  src/main/java/in/koreatech/koin/domain/community/model/BoardTag.java
  src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
Labels: 버그

#253 feat: 사장님 비밀번호 재발급 구현
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordResetVerifyRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerSendEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerVerifyRequest.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerInVerification.java
  src/main/java/in/koreatech/koin/domain/owner/repository/OwnerRepository.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/global/domain/email/exception/DuplicationEmailException.java
  src/main/java/in/koreatech/koin/global/domain/email/form/MailFormData.java
  src/main/java/in/koreatech/koin/global/domain/email/form/OwnerPasswordChangeData.java
  src/main/java/in/koreatech/koin/global/domain/email/form/OwnerRegistrationData.java
  src/main/java/in/koreatech/koin/global/domain/email/model/MailForm.java
  src/main/java/in/koreatech/koin/global/domain/email/model/MailFormContent.java
  src/main/java/in/koreatech/koin/global/domain/email/service/MailService.java
  src/main/java/in/koreatech/koin/global/domain/random/model/CertificateNumberGenerator.java
  src/main/java/in/koreatech/koin/global/domain/random/model/RandomCertificationNumber.java
  src/main/java/in/koreatech/koin/global/domain/random/model/RandomGenerator.java
  src/main/resources/mail/owner_change_password_certificate_number.html
  src/main/resources/mail/owner_register_certificate_number.html
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
Labels: 기능, Team Business
