Repository BCSDLab/KOIN_API_V2, pull requests merged in 2024-11, with the labels that each got.

#988 feat: VersionType에 ANDROID_OWNER 추가 및 관련 코드 수정
  src/main/java/in/koreatech/koin/admin/version/controller/AdminVersionApi.java
  src/main/java/in/koreatech/koin/admin/version/exception/VersionNotSupportedException.java
  src/main/java/in/koreatech/koin/admin/version/service/AdminVersionService.java
  src/main/java/in/koreatech/koin/domain/version/controller/VersionApi.java
  src/main/java/in/koreatech/koin/domain/version/model/VersionType.java
  src/main/resources/db/migration/V83__insert_owner_version.sql
Labels: 기능

#981 feat: 어드민 계정 분할 API 구현
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminPasswordChangeRequest.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminPermissionUpdateRequest.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminResponse.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminUpdateRequest.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminsCondition.java
  src/main/java/in/koreatech/koin/admin/user/dto/AdminsResponse.java
  src/main/java/in/koreatech/koin/admin/user/dto/CreateAdminRequest.java
  src/main/java/in/koreatech/koin/admin/user/enums/TeamType.java
  src/main/java/in/koreatech/koin/admin/user/enums/TrackType.java
  src/main/java/in/koreatech/koin/admin/user/exception/AdminNotFoundException.java
  src/main/java/in/koreatech/koin/admin/user/exception/AdminTeamNotValidException.java
  src/main/java/in/koreatech/koin/admin/user/exception/AdminTrackNotValidException.java
  src/main/java/in/koreatech/koin/admin/user/model/Admin.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminRepository.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/global/auth/AuthArgumentResolver.java
  src/main/java/in/koreatech/koin/global/domain/email/model/EmailAddress.java
  src/main/resources/db/migration/V84__update_admins_table.sql
  src/main/resources/db/migration/V85__insert_admin_account_date.sql
  src/test/java/in/koreatech/koin/acceptance/AbtestApiTest.java
  src/test/java/in/koreatech/koin/acceptance/KeywordApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBenefitApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminCoopShopApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminNoticeApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopReviewApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminTrackApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminVersionApiTest.java
  src/test/java/in/koreatech/koin/fixture/UserFixture.java
Labels: 기능, Team User

#996 feat: 모바일 정규 강의 삭제 API 추가
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableLectureRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
  src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
Labels: 기능, Team User

#995 chore : Swagger 일관성을 위해 name -> description으로 변경
  src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
  src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableUpdateRequest.java
Labels: 문서, Team User

#1000 feat: timetableLecture id를 리스트로 받아 삭제하는 API 추가
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimeTableLecturesDeleteRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
  src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
Labels: 기능, Team User

#992 feat: 전화하기 리뷰 유도 푸시알림 기능 구현
  src/main/java/in/koreatech/koin/admin/version/service/AdminVersionService.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
  src/main/java/in/koreatech/koin/domain/shop/exception/NotificationMessageNotFoundException.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopCategory.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopMainCategory.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopNotificationBuffer.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopNotificationMessage.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopNotificationBufferRepository.java
  src/main/java/in/koreatech/koin/domain/shop/scheduler/NotificationScheduler.java
  src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/main/java/in/koreatech/koin/domain/student/model/StudentEventListener.java
  src/main/java/in/koreatech/koin/domain/student/model/StudentRegisterEvent.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationSubscribeType.java
  src/main/java/in/koreatech/koin/global/domain/notification/repository/NotificationSubscribeRepository.java
  src/main/resources/db/migration/V87__add_shop_notification_messages_and_insert_data.sql
  src/main/resources/db/migration/V88__add_shop_main_categories_table_and_insert_data.sql
  src/main/resources/db/migration/V89__alter_shop_categories_add_main_category_id_column.sql
  src/main/resources/db/migration/V90__add_shop_notification_queue.sql
  src/main/resources/db/migration/V91__insert_notification_subscribe_review_prompt.sql
  src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
Labels: 기능

#1002 fix: 회원가입 시 강제 구독 삭제
  src/main/java/in/koreatech/koin/domain/student/model/StudentEventListener.java
  src/main/java/in/koreatech/koin/domain/student/model/StudentRegisterEvent.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/resources/db/migration/V92__delete_notification_subscribe_review_prompt.sql
Labels: 버그

#1010 feat: 어드민 상점 카테고리 생성, 수정시 상위 카테고리 선택 기능 추가
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopApi.java
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopController.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopCategoryRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopCategoryRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopReviewReportStatusRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopCategoryResponse.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopParentCategoryResponse.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopsReviewsResponse.java
  src/main/java/in/koreatech/koin/admin/shop/exception/ShopParentCategoryNotFoundException.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopNotificationMessageRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopParentCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopCategory.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopNotificationMessage.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopParentCategory.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopNotificationBufferRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
  src/main/resources/db/migration/V93__alter_shop_main_categories_table_name.sql
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
  src/test/java/in/koreatech/koin/fixture/ShopCategoryFixture.java
  src/test/java/in/koreatech/koin/fixture/ShopNotificationMessageFixture.java
  src/test/java/in/koreatech/koin/fixture/ShopParentCategoryFixture.java
Labels: 기능

#1014 fix : 강제업데이트 히스토리 조회 내림차순으로 수정
  src/main/java/in/koreatech/koin/admin/version/repository/AdminVersionRepository.java
  src/main/java/in/koreatech/koin/admin/version/service/AdminVersionService.java
Labels: 버그

#1017 feat: 로그인 어드민 계정 정보 조회 API 추가
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
Labels: 기능, Team User

#1015 feat: 어드민, 사장님 상점 생성, 수정시 메인 카테고리, 배너 이미지 추가
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopCategoryRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopCategoryRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopCategoryResponse.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopResponse.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
  src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/ModifyShopRequest.java
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopEventsWithBannerUrlResponse.java
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopEventsWithThumbnailUrlResponse.java
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopResponse.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopCategory.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/main/resources/db/migration/V96__alter_shops_add_main_category_id_column.sql
  src/main/resources/db/migration/V97__alter_shop_categories_add_event_banner_image_url_column.sql
  src/test/java/in/koreatech/koin/acceptance/BenefitApiTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopSearchApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBenefitApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopReviewApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
  src/test/java/in/koreatech/koin/fixture/ShopCategoryFixture.java
  src/test/java/in/koreatech/koin/fixture/ShopFixture.java
Labels: 기능

#1019 fix: v2/shops API에서 ShopCategories ID가 잘못 반환되는 에러 수정
  src/main/java/in/koreatech/koin/domain/shop/cache/dto/ShopCategoryCache.java
Labels: 버그, Team Business

#1007 feat: 상점 카테고리 순서 변경 api 추가
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopApi.java
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopController.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopCategoryRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopCategoriesOrderRequest.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopCategoriesResponse.java
  src/main/java/in/koreatech/koin/admin/shop/exception/ShopCategoryIllegalArgumentException.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopCategory.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopCategoryRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/main/resources/db/migration/V98__alter_order_index_to_shop_categories.sql
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
  src/test/java/in/koreatech/koin/fixture/ShopCategoryFixture.java
Labels: 기능

#1021 fix: 강의 시간 null 체크 추가
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureCreateRequest.java
Labels: 버그, Team User

#1025 feat: 게시글 조회수 증가 제한 로직 추가
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
  src/main/java/in/koreatech/koin/domain/community/article/model/redis/ArticleHitUser.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/redis/ArticleHitUserRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
Labels: 기능

#1045 fix: flyway 파일 버전 변경
  src/main/resources/db/migration/V100__add_users_notification_status_table.sql
Labels: 버그

#1044 chore: event_articles 테이블 및 엔티티의 미사용 컬럼 삭제
  src/main/java/in/koreatech/koin/domain/shop/model/article/EventArticle.java
  src/main/resources/db/migration/V99__alter_event_articles_drop_unused_column.sql
Labels: 리팩터링

#1053 chore: flyway 충돌 해결
  .github/workflows/flyway-check.yml
  src/main/resources/db/migration/V101__alter_event_articles_drop_unused_column.sql
Labels: 버그

#1055 chore: flyway 충돌 감지 복구
  .github/workflows/flyway-check.yml
Labels: 버그

#1040 refactor: owner 리팩토링
  src/main/java/in/koreatech/koin/admin/user/repository/AdminUserRepository.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/main/java/in/koreatech/koin/domain/owner/controller/EmailBasedOwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/EmailBasedOwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/controller/SmsBasedOwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/SmsBasedOwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/OwnerEmailVerifyRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/OwnerPasswordResetVerifyEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/OwnerPasswordUpdateEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/OwnerRegisterRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/OwnerSendEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/VerifyEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerAccountCheckExistsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerLoginRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerLoginResponse.java
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerPasswordResetVerifySmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerPasswordUpdateSmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerRegisterByPhoneRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerSendSmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerSmsVerifyRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/VerifySmsRequest.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerRegisterBySmsEvent.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerRegisterEvent.java
  src/main/java/in/koreatech/koin/domain/owner/model/dto/OwnerEmailRequestEvent.java
  src/main/java/in/koreatech/koin/domain/owner/model/dto/OwnerRegisterEvent.java
  src/main/java/in/koreatech/koin/domain/owner/model/dto/OwnerSmsRequestEvent.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerEmailService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerSmsService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerUtilService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerValidator.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerVerificationService.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerEventService.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerMenuService.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopUtilService.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/global/domain/email/model/EmailAddress.java
  src/main/resources/db/migration/V18__alter_user_email_column_nullable.sql
  src/main/resources/db/migration/V1__init.sql
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
Labels: 리팩터링

#1059 fix: flyway version checksum문제 해결
  src/main/resources/db/migration/V18__alter_user_email_column_nullable.sql
  src/main/resources/db/migration/V1__init.sql
Labels: 버그

#1042 refactor: 리뷰 유도 푸시알림 리팩토링
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopNotificationQueryResponse.java
  src/main/java/in/koreatech/koin/domain/shop/model/redis/ShopReviewNotification.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopNotificationBuffer.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopNotificationBufferRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopReviewNotificationRedisRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/resources/db/migration/V102__drop_shop_notification_buffer.sql
Labels: 리팩터링

#1049 fix: timetableLecture DTO swagger 수정
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureUpdateRequest.java
Labels: 버그

#1064 feat: 모든 상점 조회 v2 opens 필드 추가
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/response/ShopsResponseV2.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
Labels: 기능

#1026 refactor: redisson이 관할 하는 부분 및 transaction 범위 최소화
  src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
  src/main/java/in/koreatech/koin/global/concurrent/ConcurrencyGuard.java
Labels: 리팩터링

#1069 fix: 키워드 알림 메시지에서 중괄호 제거
  src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEventListener.java
Labels: 버그

#1068 refactor: 어드민 유저 리팩토링
  src/main/java/in/koreatech/koin/admin/owner/controller/AdminOwnerApi.java
  src/main/java/in/koreatech/koin/admin/owner/controller/AdminOwnerController.java
  src/main/java/in/koreatech/koin/admin/owner/repository/AdminOwnerRepository.java
  src/main/java/in/koreatech/koin/admin/owner/repository/AdminOwnerShopRedisRepository.java
  src/main/java/in/koreatech/koin/admin/owner/service/AdminOwnerService.java
  src/main/java/in/koreatech/koin/admin/student/controller/AdminStudentApi.java
  src/main/java/in/koreatech/koin/admin/student/controller/AdminStudentController.java
  src/main/java/in/koreatech/koin/admin/student/repository/AdminStudentRepository.java
  src/main/java/in/koreatech/koin/admin/student/service/AdminStudentService.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/main/java/in/koreatech/koin/admin/user/validation/AdminUserValidation.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminOwnerApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminStudentApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
Labels: 리팩터링

#1029 refactor: timetableV2 리펙토링
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimeTableLecturesDeleteRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableFrameCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableFrameUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableFrameResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableFrameUpdateResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableLectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableFrameCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableFrameUpdater.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureUpdater.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/SemesterRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableLectureRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableFrameService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/util/GradeCalculator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/validation/TimetableFrameValidate.java
  src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
Labels: 리팩터링, Team User

#1058 refactor : User, Student 패키지 리팩토링
  src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
  src/main/java/in/koreatech/koin/domain/student/dto/StudentLoginRequest.java
  src/main/java/in/koreatech/koin/domain/student/dto/StudentLoginResponse.java
  src/main/java/in/koreatech/koin/domain/student/model/Student.java
  src/main/java/in/koreatech/koin/domain/student/repository/StudentRedisRepository.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentValidationService.java
  src/main/java/in/koreatech/koin/domain/student/util/StudentUtil.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/AuthResponse.java
  src/main/java/in/koreatech/koin/domain/user/dto/CoopResponse.java
  src/main/java/in/koreatech/koin/domain/user/dto/EmailCheckExistsRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/FindPasswordRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/NicknameCheckExistsRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserAccessTokenRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserLoginRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserLoginResponse.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordChangeRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordChangeSubmitRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordCheckRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserTokenRefreshResponse.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserTokenRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserTokenService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
  src/test/java/in/koreatech/koin/acceptance/StudentApiTest.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 리팩터링, Team User

#1083 refactor: 어드민 유저 리팩토링
  src/main/java/in/koreatech/koin/admin/owner/controller/AdminOwnerApi.java
  src/main/java/in/koreatech/koin/admin/owner/controller/AdminOwnerController.java
  src/main/java/in/koreatech/koin/admin/owner/dto/AdminNewOwnersResponse.java
  src/main/java/in/koreatech/koin/admin/owner/dto/AdminOwnerResponse.java
  src/main/java/in/koreatech/koin/admin/owner/dto/AdminOwnerUpdateRequest.java
  src/main/java/in/koreatech/koin/admin/owner/dto/AdminOwnerUpdateResponse.java
  src/main/java/in/koreatech/koin/admin/owner/dto/AdminOwnersResponse.java
  src/main/java/in/koreatech/koin/admin/owner/dto/OwnersCondition.java
  src/main/java/in/koreatech/koin/admin/owner/repository/AdminOwnerRepository.java
  src/main/java/in/koreatech/koin/admin/owner/repository/AdminOwnerShopRedisRepository.java
  src/main/java/in/koreatech/koin/admin/owner/service/AdminOwnerService.java
  src/main/java/in/koreatech/koin/admin/student/controller/AdminStudentApi.java
  src/main/java/in/koreatech/koin/admin/student/controller/AdminStudentController.java
  src/main/java/in/koreatech/koin/admin/student/dto/AdminStudentResponse.java
  src/main/java/in/koreatech/koin/admin/student/dto/AdminStudentUpdateRequest.java
  src/main/java/in/koreatech/koin/admin/student/dto/AdminStudentUpdateResponse.java
  src/main/java/in/koreatech/koin/admin/student/dto/AdminStudentsResponse.java
  src/main/java/in/koreatech/koin/admin/student/dto/StudentsCondition.java
  src/main/java/in/koreatech/koin/admin/student/repository/AdminStudentRepository.java
  src/main/java/in/koreatech/koin/admin/student/service/AdminStudentService.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/main/java/in/koreatech/koin/admin/user/validation/AdminUserValidation.java
  src/main/java/in/koreatech/koin/domain/owner/model/Owner.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminOwnerApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminStudentApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
Labels: 리팩터링

#1085 refactor: timetableV2 리펙토링
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimeTableLecturesDeleteRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableFrameCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableFrameUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableFrameResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableFrameUpdateResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableLectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableFrameCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableFrameUpdater.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureUpdater.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/SemesterRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableLectureRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableFrameService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/util/GradeCalculator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/validation/TimetableFrameValidate.java
  src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
Labels: 리팩터링, Team User

#1086 refactor: User, Student 패키지 리팩토링
  src/main/java/in/koreatech/koin/admin/student/service/AdminStudentService.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
  src/main/java/in/koreatech/koin/domain/student/dto/StudentLoginRequest.java
  src/main/java/in/koreatech/koin/domain/student/dto/StudentLoginResponse.java
  src/main/java/in/koreatech/koin/domain/student/model/Student.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentValidationService.java
  src/main/java/in/koreatech/koin/domain/student/util/StudentUtil.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/AuthResponse.java
  src/main/java/in/koreatech/koin/domain/user/dto/CoopResponse.java
  src/main/java/in/koreatech/koin/domain/user/dto/EmailCheckExistsRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/FindPasswordRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/NicknameCheckExistsRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserAccessTokenRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserLoginRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserLoginResponse.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordChangeRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordChangeSubmitRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserPasswordCheckRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserTokenRefreshRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserTokenRefreshResponse.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserTokenRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserTokenService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
  src/test/java/in/koreatech/koin/acceptance/StudentApiTest.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 리팩터링, Team User

#1089 fix: 학생 비밀번호 수정 메소드 오류처리
  src/main/java/in/koreatech/koin/admin/student/service/AdminStudentService.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
Labels: 버그, Team User

#1070 fix: timetableLecture 클래스 필드 수정
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableLectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureUpdater.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/resources/db/migration/V103__alter_timetable_lecture_class_place_column.sql
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
Labels: 버그, Team User

#1077 feat: 위험한 sql문 체크 로직 추가
  .github/workflows/flyway-check-dangerous-sql.yml
  .github/workflows/flyway-check-version.yml
Labels: 기능

#1098 fix: shop softDelete시에 reviews도 softDelete 되도록 수정
  src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
Labels: 버그

#1096 fix: timetableLecture 오류 수정
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableLectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
Labels: 버그, Team User

#1101 fix : 정적 파일 경로 설정 오류(학생 이메일 비밀번호 수정)
  src/main/java/in/koreatech/koin/global/config/WebConfig.java
  src/main/resources/mail/change_password_config.html
Labels: 버그, Team User
