Repository BCSDLab/KOIN_API_V2, pull requests merged in 2024-10, with the labels that each got.

#931 refactor: 모든 상점 조회 V2 응답시간 최적화
  src/main/java/in/koreatech/koin/domain/benefit/service/ShopBenefitService.java
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopsFilterCriteria.java
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopsResponse.java
  src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopsResponseV2.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/dto/ShopCustomRepository.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/dto/ShopInfoV1.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/dto/ShopInfoV2.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
Labels: 리팩터링

#934 feat: 모든 시간표 프레임 삭제 api 구현
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
  src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
Labels: 기능

#936 fix : timetableLecture class_time 데이터 형식 TEXT로 변경
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/resources/db/migration/V66__modify_column_timetable_lecture_text.sql
Labels: 버그

#942 feat: 어드민 상점 혜택 카테고리 수정 기능 추가
  src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitApi.java
  src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitController.java
  src/main/java/in/koreatech/koin/admin/benefit/dto/AdminModifyBenefitCategoryRequest.java
  src/main/java/in/koreatech/koin/admin/benefit/dto/AdminModifyBenefitCategoryResponse.java
  src/main/java/in/koreatech/koin/admin/benefit/exception/BenefitDuplicationException.java
  src/main/java/in/koreatech/koin/admin/benefit/repository/AdminBenefitCategoryMapRepository.java
  src/main/java/in/koreatech/koin/admin/benefit/repository/AdminBenefitCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
  src/main/java/in/koreatech/koin/domain/benefit/model/BenefitCategory.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBenefitApiTest.java
Labels: 기능, Team Business

#928 feat: 존재하지 않는 api 요청 시 커스텀 응답 반환
  src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
  src/test/resources/application.yml
Labels: 기능

#940 feat: 어드민 게시글 CRUD API 작성
  src/main/java/in/koreatech/koin/admin/notice/controller/AdminNoticeApi.java
  src/main/java/in/koreatech/koin/admin/notice/controller/AdminNoticeController.java
  src/main/java/in/koreatech/koin/admin/notice/dto/AdminNoticeRequest.java
  src/main/java/in/koreatech/koin/admin/notice/dto/AdminNoticeResponse.java
  src/main/java/in/koreatech/koin/admin/notice/dto/AdminNoticesResponse.java
  src/main/java/in/koreatech/koin/admin/notice/service/AdminNoticeService.java
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/article/model/Board.java
  src/main/java/in/koreatech/koin/domain/community/article/model/KoinArticle.java
  src/main/java/in/koreatech/koin/domain/community/article/model/KoreatechArticle.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/KoinArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/KoreatechArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
  src/main/java/in/koreatech/koin/global/domain/upload/model/ImageUploadDomain.java
  src/main/resources/db/migration/V67__create_new_articles_tables.sql
  src/main/resources/db/migration/V68__move_articles_data.sql
  src/main/resources/db/migration/V69__move_koreatech_articles_data.sql
  src/main/resources/db/migration/V70__update_article_attachments_article_id.sql
  src/main/resources/db/migration/V71__update_article_attachments_fk.sql
  src/main/resources/db/migration/V72__add_new_articles_fk.sql
  src/main/resources/db/migration/V73__add_articles_table_fulltext_index.sql
  src/main/resources/db/migration/V74__remove_article_user_id_of_deleted.sql
  src/main/resources/db/migration/V75__remove_deleted_koin_articles.sql
  src/test/java/in/koreatech/koin/acceptance/ArticleApiTest.java
  src/test/java/in/koreatech/koin/acceptance/KeywordApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminNoticeApiTest.java
  src/test/java/in/koreatech/koin/fixture/ArticleFixture.java
  src/test/java/in/koreatech/koin/fixture/BoardFixture.java
Labels: 기능, Team Campus

#946 fix: article 로직 수정
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
Labels: 버그

#948 refactor : 생협 운영시간 API 학기, 기간 정보, 자동 전환 기능 추가
  src/main/java/in/koreatech/koin/admin/coopShop/controller/AdminCoopShopApi.java
  src/main/java/in/koreatech/koin/admin/coopShop/controller/AdminCoopShopController.java
  src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopSemesterResponse.java
  src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopSemestersResponse.java
  src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopShopResponse.java
  src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopShopsResponse.java
  src/main/java/in/koreatech/koin/admin/coopShop/repository/AdminCoopSemesterRepository.java
  src/main/java/in/koreatech/koin/admin/coopShop/repository/AdminCoopShopRepository.java
  src/main/java/in/koreatech/koin/admin/coopShop/service/AdminCoopShopService.java
  src/main/java/in/koreatech/koin/admin/version/dto/AdminVersionResponse.java
  src/main/java/in/koreatech/koin/admin/version/dto/AdminVersionUpdateRequest.java
  src/main/java/in/koreatech/koin/admin/version/dto/AdminVersionsResponse.java
  src/main/java/in/koreatech/koin/domain/coopshop/controller/CoopShopApi.java
  src/main/java/in/koreatech/koin/domain/coopshop/controller/CoopShopController.java
  src/main/java/in/koreatech/koin/domain/coopshop/dto/CoopShopResponse.java
  src/main/java/in/koreatech/koin/domain/coopshop/dto/CoopShopsResponse.java
  src/main/java/in/koreatech/koin/domain/coopshop/exception/CoopSemesterNotFoundException.java
  src/main/java/in/koreatech/koin/domain/coopshop/exception/DayTypeNotFoundException.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopOpen.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopSemester.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShop.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShopType.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/DayType.java
  src/main/java/in/koreatech/koin/domain/coopshop/repository/CoopOpenRepository.java
  src/main/java/in/koreatech/koin/domain/coopshop/repository/CoopSemesterRepository.java
  src/main/java/in/koreatech/koin/domain/coopshop/repository/CoopShopRepository.java
  src/main/java/in/koreatech/koin/domain/coopshop/service/CoopShopService.java
  src/main/java/in/koreatech/koin/domain/coopshop/util/CoopShopScheduler.java
  src/main/java/in/koreatech/koin/domain/version/dto/VersionMessageResponse.java
  src/main/resources/db/migration/V76__add_coop_shop_semester_table.sql
  src/main/resources/db/migration/V77__insert_coop_shop_semester.sql
  src/test/java/in/koreatech/koin/acceptance/CoopShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/CoopShopTest.java
  src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminCoopShopApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminCoopShopTest.java
  src/test/java/in/koreatech/koin/fixture/CoopShopFixture.java
Labels: 리팩터링, Team Campus

#949 fix: 어드민 공지 조회 API 버그 수정
  src/main/java/in/koreatech/koin/admin/notice/dto/AdminNoticeResponse.java
  src/main/java/in/koreatech/koin/admin/notice/dto/AdminNoticesResponse.java
  src/main/java/in/koreatech/koin/admin/notice/repository/AdminKoinArticleRepository.java
  src/main/java/in/koreatech/koin/admin/notice/repository/AdminKoreatechArticleRepository.java
  src/main/java/in/koreatech/koin/admin/notice/repository/AdminNoticeRepository.java
  src/main/java/in/koreatech/koin/admin/notice/service/AdminNoticeService.java
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
Labels: 버그

#947 feat: 영양사님 엑셀 다운로드 기능 구현
  build.gradle
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopApi.java
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopController.java
  src/main/java/in/koreatech/koin/domain/coop/dto/ExcelResponseBuilder.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
Labels: 기능

#954 fix: device, access_history 테이블 외래키 제약조건 수정
  src/main/resources/db/migration/V78__update_device_fk.sql
  src/main/resources/db/migration/V79__update_access_history_fk.sql
Labels: 버그

#956 Refactor/955 ci refactoring
  .github/workflows/backend_ci.yml
  .github/workflows/pick-reviewer.yml
  .github/workflows/pr-merged.yml
Labels: 리팩터링

#957 fix : coopshop 기존 데이터가 없는 로컬에서도 동작하도록 flyway 쿼리 수정
  src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopSemesterResponse.java
  src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopSemestersResponse.java
  src/main/java/in/koreatech/koin/domain/coopshop/dto/CoopShopsResponse.java
  src/main/resources/db/migration/V77__insert_coop_shop_semester.sql
  src/test/java/in/koreatech/koin/acceptance/CoopShopApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminCoopShopApiTest.java
Labels: 버그, Team Campus

#959 Fix: 게시글 첨부파일 복합 키 추가 2차전
  src/main/resources/db/migration/V80__delete_duplicate_article_attachments.sql
  src/main/resources/db/migration/V81__update_article_attachments_uk.sql
Labels: 버그

#962 fix: PUT/timetables/lecture 로직 수정
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
Labels: 버그

#963 fix : 안드로이드 fcm 알림 페이로드 notification → data 로 수정
  src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
  src/main/java/in/koreatech/koin/global/domain/test/controller/TestController.java
  src/main/java/in/koreatech/koin/global/fcm/FcmClient.java
Labels: 버그, 리팩터링

#965 refactor : fcm 스킴 uri의 도메인 명 소문자 통일
  src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEventListener.java
  src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
  src/main/java/in/koreatech/koin/domain/shop/model/event/listener/ShopEventListener.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/global/domain/test/controller/TestController.java
  src/main/java/in/koreatech/koin/global/fcm/FcmClient.java
  src/main/java/in/koreatech/koin/global/fcm/MobileAppPath.java
Labels: 리팩터링

#964 fix: 삭제된 게시판의 게시글 조회 시 예외 반환
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
Labels: 버그

#970 fix: 게시글 조회 api redisson lock 시간 연장
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
Labels: 버그

#971 fix: 코인 게시글은 인기 게시글에 포함되지 않는 쿼리 수정
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
Labels: 버그

#973 fix : 테스트 알림 필드 required로 수정
  src/main/java/in/koreatech/koin/global/domain/test/controller/TestApi.java
  src/main/java/in/koreatech/koin/global/domain/test/controller/TestController.java
Labels: 버그

#974 feat: 키워드 생성 redisson lock 점유 시간 연장, 키워드 삭제 redisson 적용, 학생 인증 redisson 적용
  src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
Labels: 기능

#980 feat: 공지사항 바로가기 url Response 추가
  src/main/java/in/koreatech/koin/domain/community/article/dto/ArticleResponse.java
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
Labels: Team Campus

#984 fix: ShopCategory isDeleted 필드 삭제 및 관련 코드 수정
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopApi.java
  src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopController.java
  src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopCategoryRequest.java
  src/main/java/in/koreatech/koin/admin/shop/exception/ShopCategoryNotEmptyException.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopCategoryMapRepository.java
  src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopCategory.java
  src/main/resources/db/migration/V82__delete_shop_categories_isdeleted.sql
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
  src/test/java/in/koreatech/koin/fixture/ShopCategoryFixture.java
Labels: 버그
