Repository BCSDLab/KOIN_API_V2, pull requests merged in 2025-09, with the labels that each got.

#1906 feat: OrderableShopMenuOptions 단위 테스트 추가
  src/test/java/in/koreatech/koin/unit/domain/order/OrderableShopMenuOptionsTest.java
Labels: Team Business, 테스트

#1900 feat: lecture 복합 인덱스 추가
  src/main/resources/db/cleanup/drop_idx_lecture_code_semester.sql
  src/main/resources/db/migration/V214__add_idx_lecture_semester_code.sql
Labels: DB, Team User

#1915 hotfix: 코인 어드민 로그인 오류 수정 (main)
  src/main/java/in/koreatech/koin/admin/history/aop/AdminActivityHistoryAspect.java
Labels: 버그

#1916 hotfix: 코인 어드민 로그인 오류 수정 (develop)
  src/main/java/in/koreatech/koin/admin/history/aop/AdminActivityHistoryAspect.java
Labels: 버그

#1924 fix: Payment 필드 유효성 검증 어노테이션 수정
  src/main/java/in/koreatech/koin/domain/payment/model/entity/Payment.java
Labels: 버그, Team Business

#1920 fix: 사장님 회원가입 전화번호 검증 수정
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerRegisterByPhoneRequest.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerSmsService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerValidator.java
  src/test/java/in/koreatech/koin/acceptance/domain/OwnerApiTest.java
Labels: 버그, Team Business

#1930 feat: 외부 API 주소 검증 컴포넌트 추가 & 주소 포맷 통일
  src/main/java/in/koreatech/koin/domain/address/client/AddressClient.java
  src/main/java/in/koreatech/koin/domain/address/client/RoadNameAddressApiErrorCodeConverter.java
  src/main/java/in/koreatech/koin/domain/address/client/RoadNameAddressClient.java
  src/main/java/in/koreatech/koin/domain/address/service/AddressValidator.java
  src/main/java/in/koreatech/koin/domain/address/service/RoadNameAddressValidator.java
  src/main/java/in/koreatech/koin/domain/order/address/controller/AddressController.java
  src/main/java/in/koreatech/koin/domain/order/address/dto/RoadNameAddressApiResponse.java
  src/main/java/in/koreatech/koin/domain/order/address/service/AddressSearchOpenApiService.java
  src/main/java/in/koreatech/koin/domain/order/address/service/CampusAddressSearchService.java
  src/main/java/in/koreatech/koin/domain/order/delivery/dto/UserOffCampusDeliveryAddressRequest.java
  src/main/java/in/koreatech/koin/domain/order/delivery/model/OffCampusDeliveryAddress.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
  src/main/java/in/koreatech/koin/global/code/ApiResponseCode.java
  src/main/resources/db/migration/V215__alter_table_add_column_user_delivery_address.sql
  src/main/resources/db/migration/V216__alter_table_shops_add_column_address_detail.sql
  src/test/java/in/koreatech/koin/unit/domain/address/RoadNameAddressValidatorTest.java
  src/test/java/in/koreatech/koin/unit/fixture/AddressFixture.java
Labels: 기능, Team Business

#1939 fix: 결제 취소 로직 수정
  src/main/java/in/koreatech/koin/domain/order/model/Order.java
  src/main/java/in/koreatech/koin/domain/payment/model/entity/Payment.java
  src/main/java/in/koreatech/koin/domain/payment/model/redis/TemporaryPayment.java
  src/main/java/in/koreatech/koin/domain/payment/service/PaymentCancelService.java
Labels: 버그, Team Business

#1942 feat: 주문 내역 리스트 조회 API 추가
  src/main/java/in/koreatech/koin/domain/order/model/Order.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderDelivery.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderInfo.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderSearchCriteria.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderStatus.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderTakeout.java
  src/main/java/in/koreatech/koin/domain/order/order/controller/OrderApi.java
  src/main/java/in/koreatech/koin/domain/order/order/controller/OrderController.java
  src/main/java/in/koreatech/koin/domain/order/order/controller/OrderTestApi.java
  src/main/java/in/koreatech/koin/domain/order/order/controller/OrderTestController.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/request/OrderSearchCondition.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/request/OrderSearchPeriodCriteria.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/request/OrderStatusCriteria.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/request/OrderTypeCriteria.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/response/OrdersResponse.java
  src/main/java/in/koreatech/koin/domain/order/order/service/OrderService.java
  src/main/java/in/koreatech/koin/domain/order/order/service/OrderTestService.java
  src/main/java/in/koreatech/koin/domain/order/repository/OrderRepository.java
  src/main/java/in/koreatech/koin/domain/order/repository/OrderSearchQueryRepository.java
  src/main/java/in/koreatech/koin/domain/payment/repository/PaymentRepository.java
  src/main/java/in/koreatech/koin/global/code/ApiResponseCode.java
Labels: 기능, Team Business

#1945 feat: 주문 조회(배달완료, 취소 제외) API 추가
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartPaymentSummaryResponse.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartResponse.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/Cart.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
  src/main/java/in/koreatech/koin/domain/order/order/controller/OrderApi.java
  src/main/java/in/koreatech/koin/domain/order/order/controller/OrderController.java
  src/main/java/in/koreatech/koin/domain/order/order/controller/OrderTestApi.java
  src/main/java/in/koreatech/koin/domain/order/order/controller/OrderTestController.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/request/OrderSearchPeriodCriteria.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/request/OrderStatusCriteria.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/request/OrderTypeCriteria.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/response/InprogressOrderResponse.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/response/OrdersResponse.java
  src/main/java/in/koreatech/koin/domain/order/order/model/Order.java
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderDelivery.java
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderInfo.java
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderMenu.java
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderMenuOption.java
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderSearchCriteria.java
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderStatus.java
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderTakeout.java
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderType.java
  src/main/java/in/koreatech/koin/domain/order/order/repository/OrderRepository.java
  src/main/java/in/koreatech/koin/domain/order/order/repository/OrderSearchQueryRepository.java
  src/main/java/in/koreatech/koin/domain/order/order/service/OrderService.java
  src/main/java/in/koreatech/koin/domain/order/order/service/OrderTestService.java
  src/main/java/in/koreatech/koin/domain/order/repository/OrderRepository.java
  src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentResponse.java
  src/main/java/in/koreatech/koin/domain/payment/mapper/OrderMenuItemsMapper.java
  src/main/java/in/koreatech/koin/domain/payment/mapper/PaymentMapper.java
  src/main/java/in/koreatech/koin/domain/payment/model/domain/TemporaryMenuItems.java
  src/main/java/in/koreatech/koin/domain/payment/model/domain/TemporaryMenuOption.java
  src/main/java/in/koreatech/koin/domain/payment/model/entity/Payment.java
  src/main/java/in/koreatech/koin/domain/payment/model/redis/TemporaryPayment.java
  src/main/java/in/koreatech/koin/domain/payment/repository/PaymentRepository.java
  src/main/java/in/koreatech/koin/domain/payment/service/PaymentConfirmService.java
  src/main/java/in/koreatech/koin/domain/payment/service/PaymentQueryService.java
  src/test/java/in/koreatech/koin/unit/domain/cart/CartQueryServiceTest.java
Labels: 기능, Team Business

#1960 fix: 활성화된 주문 조회 API 응답값(변수명) 통일
  src/main/java/in/koreatech/koin/domain/order/order/dto/response/InprogressOrderResponse.java
Labels: 버그, Team Business

#1968 fix: confirming이 아닐 때 예상 시각이 null이면 localTime을 넣도록 변경
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderDelivery.java
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderTakeout.java
  src/main/java/in/koreatech/koin/domain/order/order/service/OrderTestService.java
Labels: 버그, Team Business

#1970 feat: 임시 배달 결제 정보 저장 API 배달 타입 요청값 추가
  src/main/java/in/koreatech/koin/domain/payment/controller/PaymentApi.java
  src/main/java/in/koreatech/koin/domain/payment/dto/request/TemporaryDeliveryPaymentSaveRequest.java
  src/main/java/in/koreatech/koin/domain/payment/service/PaymentService.java
Labels: 기능

#1958 feat: 결제 조회 API 응답값 추가
  src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentResponse.java
Labels: 기능, Team Business

#1956 feat: 임시 결제 저장 정보 저장 API 위,경도 요청값 추가
  src/main/java/in/koreatech/koin/domain/order/order/dto/response/OrdersResponse.java
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderDelivery.java
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderInfo.java
  src/main/java/in/koreatech/koin/domain/order/order/repository/OrderSearchQueryRepository.java
  src/main/java/in/koreatech/koin/domain/payment/controller/PaymentApi.java
  src/main/java/in/koreatech/koin/domain/payment/dto/request/TemporaryDeliveryPaymentSaveRequest.java
  src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentResponse.java
  src/main/java/in/koreatech/koin/domain/payment/model/domain/DeliveryPaymentInfo.java
  src/main/java/in/koreatech/koin/domain/payment/model/redis/TemporaryPayment.java
  src/main/java/in/koreatech/koin/domain/payment/service/PaymentService.java
  src/main/java/in/koreatech/koin/domain/payment/service/TemporaryPaymentService.java
  src/main/resources/db/migration/V225__alter_order_delivery_add_column.sql
Labels: 기능, Team Business

#1974 fix: 위도, 경도 유효성 검증 어노테이션 삭제
  src/main/java/in/koreatech/koin/domain/order/order/model/OrderDelivery.java
  src/main/java/in/koreatech/koin/domain/payment/dto/request/TemporaryDeliveryPaymentSaveRequest.java
Labels: 버그, Team Business

#1949 feat: CartQueryServiceTest 작성
  src/main/java/in/koreatech/koin/domain/order/cart/model/CartMenuItem.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
  src/test/java/in/koreatech/koin/unit/domain/cart/CartMenuItemTest.java
  src/test/java/in/koreatech/koin/unit/domain/cart/CartQueryServiceTest.java
  src/test/java/in/koreatech/koin/unit/domain/cart/CartServiceTest.java
Labels: Team Business, 테스트

#1976 feat: paymentId 반환값 추가
  src/main/java/in/koreatech/koin/domain/order/order/dto/response/InprogressOrderResponse.java
Labels: 기능, Team Business

#1991 feat: DeliveryService 단위 테스트 추가
  src/test/java/in/koreatech/koin/unit/domain/order/delivery/service/DeliveryServiceTest.java
Labels: Team Business, 테스트

#2012 refactor: 식단 품절 알림 구독자 조회 로직 개선
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/CoopEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/repository/NotificationSubscribeRepository.java
  src/main/java/in/koreatech/koin/domain/notification/service/NotificationService.java
Labels: 리팩터링, Team Campus

#2016 feat: 주문 진행 상황 조회 시 상점 id 반환, 결제 단건 조회 시 예상시간 및 주문 상태 반환
  src/main/java/in/koreatech/koin/domain/order/order/controller/OrderApi.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/response/InprogressOrderResponse.java
  src/main/java/in/koreatech/koin/domain/payment/controller/PaymentApi.java
  src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentResponse.java
  src/main/java/in/koreatech/koin/domain/payment/service/PaymentQueryService.java
Labels: Team Business
