Repository BCSDLab/KOIN_API_V2, pull requests merged in 2025-06, with the labels that each got.

#1598 feat: 동아리 조회 응답값 좋아요 숨김 여부 추가
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
Labels: 기능, Team Campus

#1603 feat: UserAgentArgumentResolver iOS 판별 추가
  src/main/java/in/koreatech/koin/admin/abtest/useragent/UserAgentArgumentResolver.java
Labels: 기능, Team User

#1606 fix: 코인 동아리 API 요청 DTO 유효성 검증 어노테이션 수정
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubManagerDecideRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubIntroductionUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubManagerEmpowermentRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/club/model/redis/ClubCreateRedis.java
Labels: 버그, Team Campus

#1607 fix: Club 탈퇴한 회원의 Qna 조회 시 NPE 해결
  src/main/java/in/koreatech/koin/domain/club/dto/response/QnasResponse.java
Labels: 버그, Team Campus

#1609 fix: 어드민 동아리 생성 승인 시 SNS 저장 로직 추가
  src/main/java/in/koreatech/koin/admin/club/service/AdminClubService.java
Labels: 버그

#1540 feat: 주문 가능 상점 조회 API 추가
  src/main/java/in/koreatech/koin/domain/shop/controller/OrderShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/OrderShopController.java
  src/main/java/in/koreatech/koin/domain/shop/dto/order/OrderableShopBaseInfo.java
  src/main/java/in/koreatech/koin/domain/shop/dto/order/OrderableShopDetailInfo.java
  src/main/java/in/koreatech/koin/domain/shop/dto/order/OrderableShopOpenStatus.java
  src/main/java/in/koreatech/koin/domain/shop/dto/order/OrderableShopsFilterCriteria.java
  src/main/java/in/koreatech/koin/domain/shop/dto/order/OrderableShopsResponse.java
  src/main/java/in/koreatech/koin/domain/shop/dto/order/OrderableShopsSortCriteria.java
  src/main/java/in/koreatech/koin/domain/shop/model/order/OrderableShop.java
  src/main/java/in/koreatech/koin/domain/shop/model/order/ShopBaseDeliveryTip.java
  src/main/java/in/koreatech/koin/domain/shop/model/order/ShopOperation.java
  src/main/java/in/koreatech/koin/domain/shop/repository/order/OrderableShopCustomRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/OrderableShopService.java
  src/main/resources/db/migration/V158__add_oderable_shop.sql
  src/main/resources/db/migration/V159__add_index_shop_reviews_rating.sql
  src/main/resources/db/migration/V160__add_shop_base_delivery_tip.sql
  src/main/resources/db/migration/V161__add_shop_opens_index.sql
  src/main/resources/db/migration/V162__add_shop_operation.sql
Labels: Team Business

#1616 fix: ShopBaseDeliveryTip 수정
  src/main/java/in/koreatech/koin/domain/shop/model/order/ShopBaseDeliveryTip.java
Labels: 버그

#1620 fix: 코인 동아리 QA 2차 반영
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubManagerDecideRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubUpdateRequest.java
Labels: 버그, Team Campus

#1622 fix: 코인 동아리 NotEmoji 에러 메시지 수정
  src/main/java/in/koreatech/koin/_common/exception/GlobalExceptionHandler.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubManagerDecideRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubUpdateRequest.java
Labels: 버그, Team Campus

#1624 feat: 특수문자 유효성 검증 어노테이션 추가
  src/main/java/in/koreatech/koin/_common/validation/NoSpecialCharacters.java
  src/main/java/in/koreatech/koin/_common/validation/NoSpecialCharactersValidator.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubManagerDecideRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubUpdateRequest.java
Labels: 기능

#1632 hotfix: TransactionalEventListener BEFORE_COMMIT readonly 오류 핫픽스 (main)
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/ArticleKeywordEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/CoopEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/NotificationEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/ShopEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/service/NotificationService.java
  src/main/java/in/koreatech/koin/domain/shop/cache/ShopsCacheRefreshListener.java
  src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
  src/main/java/in/koreatech/koin/infrastructure/email/eventlistener/EmailEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/naver/eventlistener/NaverSmsEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/s3/eventlistener/S3EventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/ClubEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/LostItemReportEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/OwnerEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/ReviewEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/StudentEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/UserEventListener.java
  src/main/java/in/koreatech/koin/socket/domain/notification/service/MessageReceivedEventListener.java
Labels: 버그

#1633 hotfix: TransactionalEventListener BEFORE_COMMIT readonly 오류 핫픽스 (develop)
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/ArticleKeywordEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/CoopEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/NotificationEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/ShopEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/service/NotificationService.java
  src/main/java/in/koreatech/koin/domain/shop/cache/ShopsCacheRefreshListener.java
  src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
  src/main/java/in/koreatech/koin/infrastructure/email/eventlistener/EmailEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/naver/eventlistener/NaverSmsEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/s3/eventlistener/S3EventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/ClubEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/LostItemReportEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/OwnerEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/ReviewEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/StudentEventListener.java
  src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/UserEventListener.java
  src/main/java/in/koreatech/koin/socket/domain/notification/service/MessageReceivedEventListener.java
Labels: 버그

#1637 hotfix: 상위 알림 구독 수정 (develop)
  src/main/java/in/koreatech/koin/domain/notification/repository/NotificationSubscribeRepository.java
  src/main/java/in/koreatech/koin/domain/notification/service/NotificationService.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
  src/main/java/in/koreatech/koin/socket/domain/notification/service/NotificationSubscribeReader.java
Labels: 버그

#1653 feat: 주문 가능 상점 정보 단건 조회 API 추가
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopController.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shopinfo/OrderableShopInfoDetailResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shopinfo/OrderableShopInfoSummaryResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopBaseInfo.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopDetailInfo.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopOpenStatus.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopsFilterCriteria.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopsResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopsSortCriteria.java
  src/main/java/in/koreatech/koin/domain/order/shop/exception/OrderableShopNotFoundException.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/domain/OrderableShopInfoSummary.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/domain/ShopBaseDeliveryTipRange.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/domain/ShopBaseDeliveryTips.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/domain/ShopMenuOrigins.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/OrderableShop.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/ShopBaseDeliveryTip.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/ShopOperation.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopListQueryRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/service/OrderableShopInformationService.java
  src/main/java/in/koreatech/koin/domain/order/shop/service/OrderableShopListService.java
  src/main/java/in/koreatech/koin/domain/shop/controller/OrderShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/OrderShopController.java
  src/main/java/in/koreatech/koin/domain/shop/model/menu/MenuOrigin.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
  src/main/java/in/koreatech/koin/web/config/SwaggerGroupConfig.java
  src/main/resources/db/migration/V163__alter_shops_add_column_introduction_notice.sql
  src/main/resources/db/migration/V164__add_shop_menu_origin.sql
Labels: 기능, Team Business

#1654 refactor: TEXT 타입 매핑 수정
  src/main/java/in/koreatech/koin/domain/shop/model/menu/MenuOrigin.java
  src/main/resources/db/migration/V165__update_shop_menu_origin_column_type.sql
Labels: 버그, Team Business

#1652 fix: 유저와 학생 회원가입 및 업데이트 유효성 검사 통일
  src/main/java/in/koreatech/koin/domain/student/dto/RegisterStudentRequestV2.java
  src/main/java/in/koreatech/koin/domain/student/dto/UpdateStudentRequestV2.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserRegisterRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserUpdateRequest.java
Labels: 버그, Team User

#1658 hotfix: 동아리 API 수정 (develop)
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubApi.java
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubController.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubManagerDecideRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminPendingClubRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubUpdateRequest.java
Labels: 버그

#1649 refactor: 인증 도메인 리팩터링 및 단위 테스트 추가
  src/main/java/in/koreatech/koin/_common/util/random/SimpleVerificationNumberGenerator.java
  src/main/java/in/koreatech/koin/_common/util/random/VerificationNumberGenerator.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerVerificationService.java
  src/main/java/in/koreatech/koin/domain/user/verification/config/VerificationProperties.java
  src/main/java/in/koreatech/koin/domain/user/verification/dto/SendVerificationResponse.java
  src/main/java/in/koreatech/koin/domain/user/verification/model/UserDailyVerificationCount.java
  src/main/java/in/koreatech/koin/domain/user/verification/model/UserVerificationStatus.java
  src/main/java/in/koreatech/koin/domain/user/verification/repository/UserVerificationStatusRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/verification/service/UserVerificationService.java
  src/test/java/in/koreatech/koin/acceptance/domain/UserApiTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/mock/DummyApplicationEventPublisher.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/mock/FakeUserDailyVerificationCountRedisRepository.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/mock/FakeUserVerificationStatusRedisRepository.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/mock/StubVerificationNumberHolder.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/model/UserDailyVerificationCountTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/model/UserVerificationStatusTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/service/UserVerificationServiceTest.java
  src/test/java/in/koreatech/koin/unit/fixutre/VerificationFixture.java
Labels: 리팩터링, Team User

#1657 hotfix: 동아리 API 수정 (main)
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubApi.java
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubController.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubManagerDecideRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminPendingClubRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubUpdateRequest.java
Labels: 버그

#1659 feat: 주문 가능 상점 메뉴 API 추가
  src/main/java/in/koreatech/koin/_common/cache/CacheConfig.java
  src/main/java/in/koreatech/koin/_common/cache/CacheKey.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopMenuApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopMenuController.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/menu/OrderableShopMenuGroupResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/menu/OrderableShopMenuPricesResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/menu/OrderableShopMenuResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/menu/OrderableShopMenusResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shopinfo/OrderableShopInfoDetailResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopsFilterCriteria.java
  src/main/java/in/koreatech/koin/domain/order/shop/exception/OrderableShopMenuNotFoundException.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/domain/ShopBaseDeliveryTips.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/delivery/ShopBaseDeliveryTip.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenu.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuGroup.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuGroupMap.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuImage.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuOption.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuOptionGroup.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuOptionGroupMap.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuPrice.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/OrderableShop.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/ShopOperation.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopListQueryRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/menu/OrderableShopMenuRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/service/OrderableShopMenuQueryService.java
  src/main/resources/db/migration/V166__add_orderable_shop_menu_group.sql
  src/main/resources/db/migration/V167__add_orderable_shop_menu.sql
  src/main/resources/db/migration/V168__add_orderable_shop_menu_group_map.sql
  src/main/resources/db/migration/V169__add_orderable_shop_menu_price.sql
  src/main/resources/db/migration/V170__add_orderable_shop_menu_images.sql
  src/main/resources/db/migration/V171__add_orderable_shop_menu_option_group.sql
  src/main/resources/db/migration/V172__add_orderable_shop_menu_option_group_map.sql
  src/main/resources/db/migration/V173__add_orderable_shop_menu_option.sql
Labels: 기능, Team Business

#1666 refactor: 동아리 조회수 갱신 로직을 redis 스케줄링 방식으로 변경
  src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/redis/ClubHitsRedisRepository.java
  src/main/java/in/koreatech/koin/domain/club/scheduler/ClubScheduler.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubScheduleService.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
Labels: 리팩터링, Team Campus

#1671 fix: 25-하계방학 생협시간표 업데이트
  src/main/resources/db/migration/V174__update_coopshop_timatable_25_summer.sql
Labels: 버그

#1673 feat: 25년 하계방학 계절학기 셔틀버스 추가
  src/main/resources/db/migration/V175__alter_versions_shuttle.sql
Labels: DB

#1669 feat: 장바구니 API 추가
  src/main/java/in/koreatech/koin/_common/exception/ErrorResponse.java
  src/main/java/in/koreatech/koin/_common/exception/GlobalExceptionHandler.java
  src/main/java/in/koreatech/koin/_common/exception/errorcode/BaseErrorCode.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartAddItemCommand.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartAddItemRequest.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartAmountSummaryResponse.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartMenuItemEditResponse.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartPaymentSummaryResponse.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartResponse.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartUpdateItemRequest.java
  src/main/java/in/koreatech/koin/domain/order/cart/exception/CartErrorCode.java
  src/main/java/in/koreatech/koin/domain/order/cart/exception/CartException.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/Cart.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/CartMenuItem.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/CartMenuItemOption.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/OrderableShopMenuOptions.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/OrderableShopMenus.java
  src/main/java/in/koreatech/koin/domain/order/cart/repository/CartRepository.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartService.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/menu/OrderableShopMenuGroupResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/menu/OrderableShopMenuPricesResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/domain/ShopBaseDeliveryTipRange.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/domain/ShopBaseDeliveryTips.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenu.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuOption.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuOptionGroup.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuPrice.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/OrderableShop.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/menu/OrderableShopMenuOptionRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/menu/OrderableShopMenuRepository.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
  src/main/java/in/koreatech/koin/web/config/SwaggerGroupConfig.java
  src/main/resources/db/migration/V176__add_cart.sql
  src/main/resources/db/migration/V177__add_cart_menu_item.sql
  src/main/resources/db/migration/V178__add_cart_menu_item_option.sql
  src/test/java/in/koreatech/koin/unit/domain/cart/CartTest.java
  src/test/java/in/koreatech/koin/unit/fixutre/CartFixture.java
  src/test/java/in/koreatech/koin/unit/fixutre/OrderableShopFixture.java
  src/test/java/in/koreatech/koin/unit/fixutre/OrderableShopMenuFixture.java
Labels: Team Business

#1675 feat: 도로명 주소 API 추가
  src/main/java/in/koreatech/koin/_common/exception/GlobalExceptionHandler.java
  src/main/java/in/koreatech/koin/domain/order/address/controller/AddressApi.java
  src/main/java/in/koreatech/koin/domain/order/address/controller/AddressController.java
  src/main/java/in/koreatech/koin/domain/order/address/dto/AddressSearchRequest.java
  src/main/java/in/koreatech/koin/domain/order/address/dto/AddressSearchResponse.java
  src/main/java/in/koreatech/koin/domain/order/address/dto/RoadNameAddressApiResponse.java
  src/main/java/in/koreatech/koin/domain/order/address/exception/AddressApiException.java
  src/main/java/in/koreatech/koin/domain/order/address/exception/AddressErrorCode.java
  src/main/java/in/koreatech/koin/domain/order/address/service/AddressService.java
  src/main/java/in/koreatech/koin/domain/order/address/service/client/RoadNameAddressClient.java
  src/test/resources/application.yml
Labels: 기능, Team Business

#1677 feat: 결제 & 주문 테이블 추가
  src/main/java/in/koreatech/koin/domain/order/model/Order.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderDelivery.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderMenu.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderMenuOption.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderTakeout.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderType.java
  src/main/java/in/koreatech/koin/domain/order/model/Payment.java
  src/main/java/in/koreatech/koin/domain/order/model/PaymentCancel.java
  src/main/java/in/koreatech/koin/domain/order/model/PaymentMethod.java
  src/main/java/in/koreatech/koin/domain/order/model/PaymentStatus.java
  src/main/resources/db/migration/V179__add_order.sql
  src/main/resources/db/migration/V180__add_order_delivery.sql
  src/main/resources/db/migration/V181__add_order_takeout.sql
  src/main/resources/db/migration/V182__add_payment.sql
  src/main/resources/db/migration/V183__add_payment_cancel.sql
  src/main/resources/db/migration/V184__add_order_menu.sql
  src/main/resources/db/migration/V185__add_order_menu_option.sql
Labels: DB, Team Business

#1697 feat: 결제 페이지 검증 & 상점 배달 정보 API 분리
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopController.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shopinfo/OrderableShopDeliveryResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/service/OrderableShopInformationService.java
Labels: 기능, Team Business

#1700 fix: 사용자 정보 수정 미반영 오류 수정
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
Labels: 버그, Team User

#1708 feat: sms/email 인증 기능 개선
  src/main/java/in/koreatech/koin/domain/user/verification/config/VerificationProperties.java
  src/main/java/in/koreatech/koin/domain/user/verification/controller/UserVerificationApi.java
  src/main/java/in/koreatech/koin/domain/user/verification/controller/UserVerificationController.java
  src/main/java/in/koreatech/koin/domain/user/verification/dto/SendVerificationResponse.java
  src/main/java/in/koreatech/koin/domain/user/verification/model/VerificationChannel.java
  src/main/java/in/koreatech/koin/domain/user/verification/model/VerificationCode.java
  src/main/java/in/koreatech/koin/domain/user/verification/model/VerificationCount.java
  src/main/java/in/koreatech/koin/domain/user/verification/repository/UserDailyVerificationCountRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/verification/repository/UserVerificationStatusRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/verification/repository/VerificationCodeRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/verification/repository/VerificationCountRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/verification/service/UserVerificationService.java
  src/test/java/in/koreatech/koin/acceptance/domain/UserApiTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/mock/FakeUserDailyVerificationCountRedisRepository.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/mock/FakeUserVerificationStatusRedisRepository.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/mock/FakeVerificationCodeRedisRepository.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/mock/FakeVerificationCountRedisRepository.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/model/VerificationCodeTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/model/VerificationCountTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/service/UserVerificationServiceTest.java
  src/test/java/in/koreatech/koin/unit/fixutre/VerificationFixture.java
Labels: 리팩터링, Team User

#1712 feat: 동아리 행사 테이블 추가
  src/main/java/in/koreatech/koin/domain/club/model/ClubEvent.java
  src/main/resources/db/migration/V194__add_club_event.sql
Labels: DB, Team Campus
