Repository BCSDLab/KOIN_API_V2, pull requests merged in 2025-05, with the labels that each got.

#1483 fix: 유저 회원가입 시 중복이메일을 체크한다.
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/main/java/in/koreatech/koin/admin/user/validation/AdminUserValidation.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerValidator.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
Labels: 버그, Team User

#1481 refactor: loginId 필드명 및 회원가입 API URI 수정
  src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentController.java
  src/main/java/in/koreatech/koin/domain/student/dto/StudentRegisterRequestV2.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserVerificationApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserVerificationController.java
  src/main/java/in/koreatech/koin/domain/user/dto/FindIdResponse.java
  src/main/java/in/koreatech/koin/domain/user/dto/GeneralUserRegisterRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/ResetPasswordByEmailRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/ResetPasswordBySmsRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/ExistsByUserIdRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/MatchUserIdWithEmailRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/MatchUserIdWithPhoneNumberRequest.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 리팩터링, Team User

#1486 feat: versions 테이블에 복합인덱스(type, is_previous)추가
  src/main/resources/db/migration/V147__add_versions_type_isprevious_index.sql
Labels: 기능, Team Campus

#1491 fix: 중복된 is_deleted 삭제
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
Labels: 버그, Team Campus

#1489 fix: 유저 회원가입 실패 시 인증 캐시를 소모하는 오류를 해결한다.
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/RegisterUserRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/CheckNicknameDuplicationRequest.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserVerificationService.java
Labels: 버그, Team User

#1493 feat: 마케팅 알림 구독 타입 추가
  src/main/java/in/koreatech/koin/integration/fcm/notification/model/NotificationSubscribeType.java
  src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
Labels: 기능, Team User

#1495 feat: 회원가입 시 마케팅 수신 동의 필드 추가
  src/main/java/in/koreatech/koin/_common/event/UserRegisterEvent.java
  src/main/java/in/koreatech/koin/domain/notification/controller/NotificationController.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/ArticleKeywordEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/CoopEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/NotificationEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/ShopEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/exception/NotificationNotPermitException.java
  src/main/java/in/koreatech/koin/domain/notification/repository/NotificationSubscribeRepository.java
  src/main/java/in/koreatech/koin/domain/notification/service/NotificationService.java
  src/main/java/in/koreatech/koin/domain/student/dto/RegisterStudentRequestV2.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/user/dto/RegisterUserRequest.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
  src/test/java/in/koreatech/koin/AcceptanceTest.java
Labels: 기능, Team User

#1500 refactor: new_articles 테이블에 is_deleted 단일 인덱스 추가
  src/main/resources/db/migration/V148__add_articles_isdeleted_index.sql
Labels: 기능, 리팩터링, Team Campus

#1505 feat: 전화번호 하이픈 삭제
  src/main/java/in/koreatech/koin/domain/student/model/redis/UnAuthenticatedStudentInfo.java
  src/main/resources/db/migration/V149__remove_phone_number_hyphens.sql
Labels: 기능

#1514 feat: 코인 동아리 테이블 추가
  src/main/java/in/koreatech/koin/domain/club/model/Club.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubAdmin.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubCategory.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubLike.java
  src/main/resources/db/migration/V150__add_club_category_table.sql
  src/main/resources/db/migration/V151__add_club_table.sql
  src/main/resources/db/migration/V152__add_club_admin.sql
  src/main/resources/db/migration/V153__add_club_like.sql
Labels: 기능, Team Campus

#1516 feat: club_qna 테이블 추가
  src/main/resources/db/migration/V154__add_club_qna_table.sql
Labels: 기능, Team Campus

#1502 feat: 이미지 삭제나 수정 시 s3 정합성을 위한 이벤트 로직 추가
  src/main/java/in/koreatech/koin/_common/event/ImageDeletedEvent.java
  src/main/java/in/koreatech/koin/_common/event/ImagesDeletedEvent.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopMenuService.java
  src/main/java/in/koreatech/koin/infrastructure/s3/client/S3Client.java
  src/main/java/in/koreatech/koin/infrastructure/s3/eventlistener/S3EventListener.java
Labels: 기능

#1518 docs: 깃허브 릴리즈노트 자동화
  .github/release-drafter.yml
  .github/workflows/flyway-dangerous-sql-validator.yml
  .github/workflows/flyway-version-validator.yml
  .github/workflows/pr-merge-slack-sender.yml
  .github/workflows/pr-reviewers-assigner.yml
  .github/workflows/pr-title-validator.yml
  .github/workflows/release-drafter.yml
  src/main/java/in/koreatech/koin/web/config/SwaggerConfig.java
Labels: 문서

#1522 feat: 코인 공지 테스트 API 추가
  src/main/java/in/koreatech/koin/domain/test/TestApi.java
  src/main/java/in/koreatech/koin/domain/test/TestController.java
Labels: 기능

#1528 feat: 동아리 QNA API
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/CreateQnaRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/QnasResponse.java
  src/main/java/in/koreatech/koin/domain/club/exception/ClubNotFoundException.java
  src/main/java/in/koreatech/koin/domain/club/exception/ClubQnaNotFoundException.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubQna.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubAdminRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubQnaRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
  src/main/java/in/koreatech/koin/web/config/SwaggerGroupConfig.java
  src/main/resources/db/migration/V154__add_club_qna_table.sql
  src/test/java/in/koreatech/koin/unit/ClubTest.java
Labels: 기능, Team Campus

#1529 feat: 인기 동아리 조회 API
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubHotResponse.java
  src/main/java/in/koreatech/koin/domain/club/exception/ClubHotNotFoundException.java
  src/main/java/in/koreatech/koin/domain/club/model/Club.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubHot.java
  src/main/java/in/koreatech/koin/domain/club/model/redis/ClubHotRedis.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubHotRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/redis/ClubHotRedisRepository.java
  src/main/java/in/koreatech/koin/domain/club/scheduler/ClubScheduler.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubScheduleService.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
  src/main/resources/db/migration/V155__add_club_last_week_hits_column.sql
  src/main/resources/db/migration/V156__add_club_hot.sql
Labels: 기능, Team Campus

#1525 feat: 어드민 동아리 CRU API 추가
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubApi.java
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubCategoryApi.java
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubCategoryController.java
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubController.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/CreateAdminClubRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/ModifyAdminClubRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubCategoriesResponse.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubResponse.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubsResponse.java
  src/main/java/in/koreatech/koin/admin/club/exception/ClubCategoryNotFound.java
  src/main/java/in/koreatech/koin/admin/club/exception/ClubNotFound.java
  src/main/java/in/koreatech/koin/admin/club/repository/AdminClubAdminRepository.java
  src/main/java/in/koreatech/koin/admin/club/repository/AdminClubCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/club/repository/AdminClubRepository.java
  src/main/java/in/koreatech/koin/admin/club/service/AdminClubCategoryService.java
  src/main/java/in/koreatech/koin/admin/club/service/AdminClubService.java
  src/main/java/in/koreatech/koin/admin/history/enums/DomainType.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminUserRepository.java
  src/main/java/in/koreatech/koin/domain/club/enums/SNSType.java
  src/main/java/in/koreatech/koin/domain/club/model/Club.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubSNS.java
  src/main/resources/db/migration/V157__add_club_sns_table.sql
Labels: 기능, Team Campus

#1533 fix: 1차 QA 이슈 해결
  src/main/java/in/koreatech/koin/domain/student/dto/RegisterStudentRequestV2.java
  src/main/java/in/koreatech/koin/domain/student/dto/UpdateStudentRequestV2.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/user/dto/RegisterUserRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/UpdateUserRequest.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
Labels: 버그, Team User

#1536 feat: 어드민 동아리 관리 API추가
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubApi.java
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubController.java
  src/main/java/in/koreatech/koin/admin/club/dto/ClubAdminCondition.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/ChangeAdminClubActiveRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/DecideAdminClubAdminRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubAdminsResponse.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminNewClubResponse.java
  src/main/java/in/koreatech/koin/admin/club/repository/AdminClubAdminRepository.java
  src/main/java/in/koreatech/koin/admin/club/repository/AdminClubRepository.java
  src/main/java/in/koreatech/koin/admin/club/service/AdminClubService.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/CreateClubRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
  src/main/java/in/koreatech/koin/domain/club/model/Club.java
  src/main/java/in/koreatech/koin/domain/club/model/redis/ClubCreateRedis.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubAdminRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
Labels: 기능, Team Campus

#1549 feat: 동아리 QNA 기획 수정사항 반영
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/QnasResponse.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubQna.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
Labels: 기능, Team Campus

#1554 fix: CloudFront path변환 UTF-8인코딩 및 공백보정, 슬래시 보정 추가
  src/main/java/in/koreatech/koin/infrastructure/s3/client/CloudFrontClientWrapper.java
Labels: 버그

#1556 fix: (Noraml) GET /clubs NPE 해결
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
Labels: 버그, Team Campus

#1560 feat: ClubHotRedis에 clubId추가
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubHotResponse.java
  src/main/java/in/koreatech/koin/domain/club/model/redis/ClubHotRedis.java
Labels: 기능, Team Campus

#1562 fix: 코인 동아리 활성화 여부 변수명 통일
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubManagersResponse.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubsResponse.java
  src/main/java/in/koreatech/koin/admin/club/service/AdminClubService.java
Labels: 버그, Team Campus

#1559 chore: 동아리 API SnakeCase 추가 및 형식 일치
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubApi.java
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubController.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubManagersResponse.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminPendingClubResponse.java
  src/main/java/in/koreatech/koin/admin/club/service/AdminClubService.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubManagerEmpowermentRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/QnaCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubCategoriesResponse.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
Labels: 리팩터링, Team Campus

#1565 feat: 동아리 카테고리 미 선택 시 동아리 전체 조회 추가
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
Labels: 기능, Team Campus

#1569 feat: 카테고리 별 동아리 조회 응답값 좋아요 수 필드 추가
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
Labels: 기능, Team Campus

#1570 hotfix: Timetable NPE 수정 (main)
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/LectureInfoResponse.java
Labels: 버그

#1573 fix: 코인 어드민 동아리 & 일반 동아리 API 변경사항 적용
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubResponse.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminPendingClubResponse.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/enums/ClubSortType.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
Labels: 버그, Team Campus

#1575 fix: 반환값 좋아요 여부 추가
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubLikeRepository.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
Labels: 버그

#1577 fix: 코인 어드민 동아리 수정사항 반영
  src/main/java/in/koreatech/koin/admin/club/controller/AdminClubApi.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubManagersResponse.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubResponse.java
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubsResponse.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubManager.java
Labels: 버그, Team Campus

#1579 feat: 코인 동아리 이미지 업로드 도메인 추가
  src/main/java/in/koreatech/koin/infrastructure/s3/model/ImageUploadDomain.java
Labels: 기능, Team Campus

#1583 feat: 동아리 상세조회에 업데이트 일자 추가
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
Labels: 기능, Team Campus

#1588 fix: 동아리 생성 요청/어드민 동아리 상세조회 역할 필드 추가
  src/main/java/in/koreatech/koin/admin/club/dto/response/AdminPendingClubResponse.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/model/redis/ClubCreateRedis.java
Labels: 버그

#1590 feat: GET /clubs 응답값 스네이크 케이스 적용
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
Labels: 기능, Team Campus

#1592 fix: shop 엔티티 db와 column name 불일치 해결
  src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
Labels: 버그

#1585 fix: 채팅방 조회 시 404 응답 오류 수정
  src/main/java/in/koreatech/koin/socket/domain/chatroom/service/LostItemChatRoomInfoService.java
  src/main/java/in/koreatech/koin/socket/domain/session/service/implement/UserReader.java
Labels: 버그
