Repository BCSDLab/KOIN_API_V2, pull requests merged in 2025-02, with the labels that each got.

#1214 refactor: legacy bus api 제거
  src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/dto/BusCourseResponse.java
  src/main/java/in/koreatech/koin/domain/bus/repository/BusRepository.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
Labels: 리팩터링

#1209 fix: 졸업학점 계산기 관련 flyway 수정
  src/main/java/in/koreatech/koin/domain/graduation/model/Catalog.java
  src/main/java/in/koreatech/koin/domain/graduation/model/CourseType.java
  src/main/java/in/koreatech/koin/domain/graduation/model/GeneralEducationAreaCourseTypeMap.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/resources/db/migration/V118__add_catalog.sql
  src/main/resources/db/migration/V122__alter_fk_general_education_area_id_on_timetable.sql
  src/main/resources/db/migration/V123__add_general_education_area_course_type_map.sql
Labels: 버그, Team User

#1215 Refactor : 버스 리팩토링
  src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
  src/main/java/in/koreatech/koin/domain/bus/service/CityBusService.java
  src/main/java/in/koreatech/koin/domain/bus/service/ExpressBusService.java
  src/main/java/in/koreatech/koin/domain/bus/service/ShuttleBusService.java
  src/main/java/in/koreatech/koin/domain/bus/util/BusCacheScheduler.java
  src/main/java/in/koreatech/koin/domain/bus/util/BusCacheService.java
  src/main/java/in/koreatech/koin/domain/bus/util/converter/BusStationEnumConverter.java
  src/main/java/in/koreatech/koin/domain/bus/util/converter/BusTypeEnumConverter.java
  src/main/java/in/koreatech/koin/global/config/WebConfig.java
  src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
Labels: 리팩터링

#1216 feat: 교통편 조회 의존성 변경
  src/main/java/in/koreatech/koin/domain/bus/model/enums/BusStation.java
  src/main/java/in/koreatech/koin/domain/bus/model/mongo/ShuttleBusRoute.java
  src/main/java/in/koreatech/koin/domain/bus/repository/BusRepository.java
  src/main/java/in/koreatech/koin/domain/bus/repository/ShuttleBusRepository.java
  src/main/java/in/koreatech/koin/domain/bus/service/route/CityBusRouteStrategy.java
  src/main/java/in/koreatech/koin/domain/bus/service/route/CommutingBusRouteStrategy.java
  src/main/java/in/koreatech/koin/domain/bus/service/route/ShuttleBusRouteStrategy.java
Labels: 리팩터링, Team Campus

#1191 feat: 분실물 게시글 쪽지(채팅) 기능
  build.gradle
  src/main/java/in/koreatech/koin/domain/community/article/repository/LostItemArticleRepository.java
  src/main/java/in/koreatech/koin/global/config/swagger/SwaggerGroupConfig.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationSubscribeType.java
  src/main/java/in/koreatech/koin/global/fcm/MobileAppPath.java
  src/main/java/in/koreatech/koin/global/socket/config/WebSocketConfig.java
  src/main/java/in/koreatech/koin/global/socket/config/auth/UserPrincipal.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/controller/ChatRestApi.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/controller/ChatRestController.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/dto/ChatRoomInfoResponse.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/dto/ChatRoomListResponse.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/exception/SelfChatNotAllowedException.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/model/LostItemChatMessageEntity.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/model/LostItemChatRoomInfoEntity.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/repository/LostItemChatRoomInfoRepository.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/LostItemChatRoomInfoService.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/ChatRoomInfoAppender.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/ChatRoomInfoReader.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/LostItemArticleReader.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/controller/ChatMessageSocketController.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/dto/ChatMessageResponse.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/exception/MessageProcessingException.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/model/ChatMessageCommand.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/model/ChatMessageEntity.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/model/redis/ChatMessageRedisEntity.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/repository/ChatMessageRedisRepository.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/service/ChatMessageService.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/service/MessageEventHandler.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/service/implement/MessageAppender.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/service/implement/MessageHelper.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/service/implement/MessageReader.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/service/implement/MessageUpdater.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/util/ChatMessageIdGenerator.java
  src/main/java/in/koreatech/koin/global/socket/domain/message/util/WebSocketSessionTracker.java
  src/main/java/in/koreatech/koin/global/socket/domain/notification/model/MessageReceivedEvent.java
  src/main/java/in/koreatech/koin/global/socket/domain/notification/service/MessageReceivedEventListener.java
  src/main/java/in/koreatech/koin/global/socket/domain/notification/service/NotificationSubscribeReader.java
  src/main/java/in/koreatech/koin/global/socket/domain/session/model/UserSession.java
  src/main/java/in/koreatech/koin/global/socket/domain/session/model/UserSessionStatus.java
  src/main/java/in/koreatech/koin/global/socket/domain/session/repository/UserSessionRedisRepository.java
  src/main/java/in/koreatech/koin/global/socket/domain/session/service/UserSessionService.java
  src/main/java/in/koreatech/koin/global/socket/domain/session/service/implement/UserReader.java
  src/main/java/in/koreatech/koin/global/socket/interceptor/ConnectInterceptor.java
  src/main/java/in/koreatech/koin/global/socket/interceptor/DisconnectInterceptor.java
  src/main/java/in/koreatech/koin/global/socket/interceptor/SubscribeInterceptor.java
  src/main/java/in/koreatech/koin/global/socket/interceptor/UnsubscribeInterceptor.java
  src/main/java/in/koreatech/koin/global/socket/util/SubscribeDestination.java
  src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
Labels: 기능, Team Campus

#1175 feat: 영양사 이미지 압축 다운로드
  build.gradle
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopApi.java
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopController.java
  src/main/java/in/koreatech/koin/domain/coop/dto/CompressFileResponseBuilder.java
  src/main/java/in/koreatech/koin/domain/coop/exception/DiningLimitDateException.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
  src/main/java/in/koreatech/koin/global/s3/S3Utils.java
  src/main/java/in/koreatech/koin/global/scheduler/CacheShopsScheduler.java
  src/test/java/in/koreatech/koin/global/domain/upload/UploadServiceTest.java
Labels: 기능, Team Campus

#1207 Refactor/영양사 엑셀 디자인 변경
  src/main/java/in/koreatech/koin/domain/coop/repository/DiningSoldOutCacheRepository.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/dining/exception/ExcelDiningPositionNotFoundException.java
  src/main/java/in/koreatech/koin/domain/dining/model/enums/ExcelDiningPosition.java
Labels: 리팩터링

#1221 fix : 웹 소켓 설정에서 sockjs 통신 설정 삭제
  src/main/java/in/koreatech/koin/global/socket/config/WebSocketConfig.java
Labels: 버그

#1164 feat : 생협 운영시간 id로 조회 로직 수정
  src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopSemesterResponse.java
  src/main/java/in/koreatech/koin/domain/coopshop/controller/CoopShopApi.java
  src/main/java/in/koreatech/koin/domain/coopshop/controller/CoopShopController.java
  src/main/java/in/koreatech/koin/domain/coopshop/dto/CoopShopResponse.java
  src/main/java/in/koreatech/koin/domain/coopshop/dto/CoopShopsResponse.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopName.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShop.java
  src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShopType.java
  src/main/java/in/koreatech/koin/domain/coopshop/repository/CoopNameRepository.java
  src/main/java/in/koreatech/koin/domain/coopshop/repository/CoopShopRepository.java
  src/main/java/in/koreatech/koin/domain/coopshop/service/CoopShopService.java
  src/main/resources/db/migration/V111__add_table_coop_names.sql
  src/main/resources/db/migration/V112__delete_column_coop_shop_name.sql
  src/main/resources/db/migration/V113__atler_coop_opens_dazzle.sql
  src/test/java/in/koreatech/koin/fixture/CoopShopFixture.java
Labels: 기능, Team Campus

#1223 feat: s3 접근에 필요한 자격 증명 방식 단일화
  src/main/java/in/koreatech/koin/global/config/S3Config.java
Labels: 기능

#1225 fix: 영양사 이미지 압축 다운로드 예외처리
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/global/s3/S3Utils.java
Labels: 버그, Team Campus

#1226 fix: 영양사 이미지 압축 다운로드 생략 기준 변경
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
Labels: 버그

#1231 feat: TrackType enum에 보안 트랙 추가
  src/main/java/in/koreatech/koin/admin/user/enums/TrackType.java
  src/main/java/in/koreatech/koin/admin/user/model/Admin.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
Labels: 기능, Team User

#1208 refactor: 졸업 학점 계산 Catalog 테이블 학과 공통 처리 및 major 우선 로직 반영
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
Labels: 기능

#1224 feat: 분실물 API 2차 기능 추가(습득물, 학생 작성)
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticleRequest.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticleResponse.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticlesResponse.java
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/article/model/LostItemArticle.java
  src/main/java/in/koreatech/koin/domain/community/article/model/LostItemImage.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/LostItemArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/main/resources/db/migration/V115__add_lost_item_column_is_council.sql
Labels: 기능, Team Campus

#1233 feat : 졸학계 엑셀파일 집어넣기 최신판(졸학계)
  src/main/java/in/koreatech/koin/domain/graduation/model/Catalog.java
  src/main/java/in/koreatech/koin/domain/graduation/model/GeneralEducationAreaCourseTypeMap.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CourseTypeRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/LectureRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableLectureRepositoryV2.java
  src/main/resources/db/migration/V115__add_lost_item_column_is_council.sql
  src/main/resources/db/migration/V116__add_course_type.sql
  src/main/resources/db/migration/V117__add_department.sql
  src/main/resources/db/migration/V118__add_major.sql
  src/main/resources/db/migration/V119__add_standard_graduation_requirements.sql
  src/main/resources/db/migration/V120__add_student_course_calculation.sql
  src/main/resources/db/migration/V121__add_general_education_area.sql
  src/main/resources/db/migration/V122__alter_fk_course_type_on_timetable.sql
  src/main/resources/db/migration/V123__add_catalog.sql
  src/main/resources/db/migration/V124__add_detect_graduation_calculation.sql
  src/main/resources/db/migration/V125__alter_student_department_fk.sql
  src/main/resources/db/migration/V126__alter_student_add_column_major.sql
  src/main/resources/db/migration/V127__alter_fk_general_education_area_id_on_timetable.sql
  src/main/resources/db/migration/V128__add_general_education_area_course_type_map.sql
  src/main/resources/db/migration/V129__add_indexes_to_catalog.sql
Labels: Team User

#1234 rafactor & docs : 엑셀 관련 로직 설명 추가 및 리팩토링
  src/main/java/in/koreatech/koin/domain/graduation/model/Catalog.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
Labels: 리팩터링

#1229 feat : 분실물 게시글 쪽지(채팅) 사용자 차단 기능
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/controller/ChatRestApi.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/controller/ChatRestController.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/exception/UserBlockException.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/model/LostItemChatUserBlockEntity.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/repository/LostItemChatUserBlockRepository.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/LostItemChatRoomInfoService.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/LostItemChatRoomUserBlockService.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/ChatRoomInfoReader.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/UserBlockAppender.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/UserBlockReader.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/UserBlockUpdater.java
Labels: 기능, Team Campus

#1238 chore: 게시글 목록 조회 응답에 is_reported 필드 추가
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/ArticlesResponse.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticlesResponse.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
Labels: Team Campus

#1240 feat : 졸학계 엑셀 / 강의조회 로직 내 GeneralEducationArea 추가(졸학계)
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationApi.java
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationController.java
  src/main/java/in/koreatech/koin/domain/graduation/exception/GeneralEducationAreaNotFoundException.java
  src/main/java/in/koreatech/koin/domain/graduation/model/CatalogResult.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/GeneralEducationAreaRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
Labels: 기능, Team User

#1232 refactor: 비밀번호 초기화 토큰을 레디스로 이동
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/user/model/PasswordResetToken.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserPasswordResetTokenRepository.java
Labels: 버그, 리팩터링, Team User

#1219 refactor: 가장 빠른 교통편 조회 DB 의존성 변경
  src/main/java/in/koreatech/koin/domain/bus/service/model/route/ShuttleBusRouteStrategy.java
  src/main/java/in/koreatech/koin/domain/bus/service/shuttle/ShuttleBusRepository.java
  src/main/java/in/koreatech/koin/domain/bus/service/shuttle/model/ShuttleBusRoute.java
  src/main/java/in/koreatech/koin/domain/bus/service/shuttle/model/ShuttleBusSimpleRoute.java
Labels: 리팩터링, Team Campus

#1245 feat: 사장님 회원가입 요청 시 가게 전화번호 관련 추가
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerRegisterByPhoneRequest.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerShop.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerEmailService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerSmsService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerUtilService.java
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopRepository.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
Labels: 기능, Team Business

#1252 feat: 사장님 회원가입 시 redis에 임시 저장한 가게정보 조회 API
  src/main/java/in/koreatech/koin/admin/owner/service/AdminOwnerService.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/dto/OwnerRegisteredInfoResponse.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminOwnerApiTest.java
Labels: 기능, Team Business

#1254 fix: GET user/student/me NPE 해결
  src/main/java/in/koreatech/koin/domain/student/dto/StudentResponse.java
  src/main/resources/db/migration/V129__update_department_name.sql
Labels: 버그, Team User

#1259 fix: 대화가 없는 채팅방 정보도 출력
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/model/LostItemChatRoomInfoEntity.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/LostItemChatRoomInfoService.java
  src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/ChatRoomInfoAppender.java
Labels: 버그

#1261 fix: major 테이블의 데이터 수정
  src/main/java/in/koreatech/koin/admin/student/dto/AdminStudentResponse.java
  src/main/java/in/koreatech/koin/admin/student/dto/AdminStudentUpdateResponse.java
  src/main/java/in/koreatech/koin/admin/student/dto/AdminStudentsResponse.java
  src/main/java/in/koreatech/koin/domain/dept/service/DeptService.java
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationApi.java
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationController.java
  src/main/java/in/koreatech/koin/domain/student/model/Major.java
  src/main/resources/db/migration/V130__delete_major_data.sql
  src/main/resources/db/migration/V131__update_student_department.sql
  src/main/resources/db/migration/V132__alter_major_auto_increment.sql
  src/main/resources/db/migration/V133__insert_major_and_department_data.sql
Labels: 버그, Team User

#1263 refactor: articles의 author 필드 값 null 대체
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
Labels: 버그, 리팩터링, Team Campus

#1260 feat: 분실물 게시글 검색 api 추가
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
Labels: Team Campus

#1264 fix: 학생 정보 수정 오류 수정
  src/main/java/in/koreatech/koin/domain/student/model/Major.java
  src/main/java/in/koreatech/koin/domain/student/model/Student.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/test/java/in/koreatech/koin/acceptance/AbtestApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ArticleApiTest.java
  src/test/java/in/koreatech/koin/acceptance/BenefitApiTest.java
  src/test/java/in/koreatech/koin/acceptance/KeywordApiTest.java
  src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
  src/test/java/in/koreatech/koin/acceptance/SemesterApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
  src/test/java/in/koreatech/koin/acceptance/StudentApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiV3Test.java
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureV3ApiTest.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminShopReviewApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminStudentApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminTrackApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
  src/test/java/in/koreatech/koin/fixture/MajorFixture.java
  src/test/java/in/koreatech/koin/fixture/UserFixture.java
Labels: 버그, Team User

#1267 fix: 사업자 등록번호 잘못된 요청 매핑 어노테이션 수정
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
Labels: 버그, Team Business

#1269 fix: 학과를 입력하지 않고 회원가입을 할 경우 발생한 오류 해결
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
Labels: 버그, Team User

#1257 fix: 인증시간 재인증시 실패하는 오류 해결
  src/main/java/in/koreatech/koin/domain/owner/controller/EmailBasedOwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/EmailBasedOwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/controller/SmsBasedOwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/OwnerEmailVerifyRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/OwnerPasswordResetVerifyEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/OwnerPasswordUpdateEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/OwnerRegisterRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/OwnerSendEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/dto/email/VerifyEmailRequest.java
  src/main/java/in/koreatech/koin/domain/owner/exception/DuplicationCertificationException.java
  src/main/java/in/koreatech/koin/domain/owner/exception/OwnerAttachmentNotFoundException.java
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
  src/main/java/in/koreatech/koin/domain/owner/model/redis/OwnerVerificationStatus.java
  src/main/java/in/koreatech/koin/domain/owner/repository/OwnerAttachmentRepository.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerEmailService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerValidator.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerVerificationService.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
Labels: 버그, Team Business

#1272 fix: 특정 사장님 수정 gender null체크 추가
  src/main/java/in/koreatech/koin/admin/owner/dto/AdminOwnerUpdateResponse.java
Labels: 버그, Team Business

#1265 feat: timetable API dto 유효성 검증 어노테이션 추가
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableCustomLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableCustomLectureUpdateRequest.java
Labels: 기능, Team User

#1276 fix: 분실물 게시글 오류 수정
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/resources/db/migration/V134__alter_lost_item_author_cascade.sql
Labels: 버그

#1275 feat: 졸업학점 계산기 적용 학생 정보 수정 API 추가
  src/main/java/in/koreatech/koin/domain/graduation/repository/StudentCourseCalculationRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentController.java
  src/main/java/in/koreatech/koin/domain/student/dto/StudentAcademicInfoUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/student/dto/StudentAcademicInfoUpdateResponse.java
  src/main/java/in/koreatech/koin/domain/student/model/Student.java
  src/main/java/in/koreatech/koin/domain/student/repository/MajorRepository.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentValidationService.java
  src/main/resources/db/migration/V135__update_student_major.sql
  src/test/java/in/koreatech/koin/acceptance/StudentApiTest.java
Labels: 기능, Team User

#1270 chore: 분실물 게시글의 foundPlace 빈 값일 경우 "장소 미상"으로 저장하도록 수정
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
Labels: Team Campus

#1274 feat: 현재 이수한 교양 강의 API
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationApi.java
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationController.java
  src/main/java/in/koreatech/koin/domain/graduation/dto/EducationLectureResponse.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
Labels: 기능

#1280 fix: 가게 가입시 슬랙 알림에 가게이름 안나오는 오류 수정
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
  src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotificationFactory.java
Labels: 버그, Team Business

#1278 fix: 졸업학점 계산 agree api 유저 중복 해결
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
Labels: 버그

#1286 fix: 학생 정보 수정 NPE 해결
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
  src/main/java/in/koreatech/koin/domain/student/dto/StudentUpdateResponse.java
  src/main/java/in/koreatech/koin/domain/student/model/StudentDepartment.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
Labels: 버그, Team User

#1289 fix: 졸학계 aop 수정
  src/main/java/in/koreatech/koin/domain/graduation/aop/GraduationAspect.java
Labels: 버그

#1291 fix: 자신이 들은 학점 빈칸으로 보여주던 문제 해결
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/StandardGraduationRequirementsRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
Labels: 버그

#1296 fix: timetable NPE 해결
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/LectureInfoResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV3/utils/ClassTimeUtils.java
Labels: 버그, Team User

#1294 feat: 이메일 재전송 로직 추가
  src/main/java/in/koreatech/koin/global/domain/email/model/SesMailSender.java
Labels: 기능, Team User

#1298 fix: 사업자 등록번호 중복 검증 필드 미인식 문제 해결
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
Labels: 버그, Team Business

#1301 refactor: QA에서 이벤트를 최신순으로 정렬해서 보여달라는 의견 수렴
  src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerEventApi.java
  src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopEventsResponse.java
Labels: 리팩터링, Team Business

#1303 fix : 학생 학적 정보 수정 오류 해결 & feat : 학생 정보 조회(학적 포함)
  src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentController.java
  src/main/java/in/koreatech/koin/domain/student/dto/StudentWithAcademicResponse.java
  src/main/java/in/koreatech/koin/domain/student/repository/MajorRepository.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
Labels: 버그

#1305 fix : 분실물 게시판 2차 QA 이슈 해결
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEvent.java
  src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEventListener.java
  src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
  src/main/java/in/koreatech/koin/domain/community/util/KeywordExtractor.java
Labels: 버그, Team Campus
