Repository BCSDLab/KOIN_API_V2, pull requests merged in 2025-07, with the labels that each got.

#1714 feat: swagger 에러코드 문서화를 자동화
  src/main/java/in/koreatech/koin/_common/auth/JwtProvider.java
  src/main/java/in/koreatech/koin/_common/code/ApiResponseCode.java
  src/main/java/in/koreatech/koin/_common/code/ApiResponseCodes.java
  src/main/java/in/koreatech/koin/_common/code/ApiResponseCodesOperationCustomizer.java
  src/main/java/in/koreatech/koin/_common/exception/CustomException.java
  src/main/java/in/koreatech/koin/_common/exception/ErrorResponse.java
  src/main/java/in/koreatech/koin/_common/exception/GlobalExceptionHandler.java
  src/main/java/in/koreatech/koin/_common/exception/errorcode/ErrorCode.java
  src/main/java/in/koreatech/koin/admin/student/repository/AdminStudentRepository.java
  src/main/java/in/koreatech/koin/admin/student/service/AdminStudentService.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminUserRepository.java
  src/main/java/in/koreatech/koin/admin/user/validation/AdminUserValidation.java
  src/main/java/in/koreatech/koin/domain/student/repository/StudentRepository.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentValidationService.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserValidationApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserValidationController.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/model/UserGender.java
  src/main/java/in/koreatech/koin/domain/user/repository/RefreshTokenRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserPasswordResetTokenRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/RefreshTokenService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
  src/main/java/in/koreatech/koin/domain/user/verification/model/VerificationCode.java
  src/main/java/in/koreatech/koin/domain/user/verification/model/VerificationCount.java
  src/main/java/in/koreatech/koin/domain/user/verification/service/UserVerificationService.java
  src/main/java/in/koreatech/koin/socket/domain/chatroom/service/LostItemChatRoomInfoService.java
  src/main/java/in/koreatech/koin/web/config/SwaggerGroupConfig.java
  src/test/java/in/koreatech/koin/acceptance/domain/UserApiTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/model/UserTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/model/VerificationCodeTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/model/VerificationCountTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/service/UserVerificationServiceTest.java
Labels: 기능, 공통

#1719 feat: 교외 배달 주소 검증 API 추가
  src/main/java/in/koreatech/koin/_common/code/ApiResponseCode.java
  src/main/java/in/koreatech/koin/_common/exception/GlobalExceptionHandler.java
  src/main/java/in/koreatech/koin/domain/order/delivery/controller/DeliveryApi.java
  src/main/java/in/koreatech/koin/domain/order/delivery/controller/DeliveryController.java
  src/main/java/in/koreatech/koin/domain/order/delivery/dto/UserOffCampusDeliveryAddressValidateRequest.java
  src/main/java/in/koreatech/koin/domain/order/delivery/service/DeliveryAddressValidator.java
  src/main/java/in/koreatech/koin/domain/order/delivery/service/DeliveryService.java
  src/test/java/in/koreatech/koin/unit/domain/address/DeliveryAddressValidatorTest.java
Labels: Team Business

#1705 feat: 장바구니 조회 API 이미지 응답값 추가
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/OrderableShop.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/OrderableShopImage.java
  src/main/resources/db/migration/V193__add_orderable_shop_image_table.sql
Labels: 기능, Team Business

#1716 feat: 동아리 검색 기능 추가
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubQnaCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubQnasResponse.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubRelatedKeywordResponse.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubEvent.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
  src/main/resources/db/migration/V195__add_club_name_index.sql
Labels: 기능, Team Campus

#1726 feat: 부장 전용 동아리 모집 API 추가
  src/main/java/in/koreatech/koin/_common/code/ApiResponseCode.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubRecruitmentCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubRecruitmentModifyRequest.java
  src/main/java/in/koreatech/koin/domain/club/exception/ClubRecruitmentNotFoundException.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubRecruitment.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubRecruitmentRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
  src/main/resources/db/migration/V194__add_club_recruitment.sql
Labels: 기능, Team Campus

#1731 feat: 장바구니 포장/배달 응답 분리
  src/main/java/in/koreatech/koin/_common/code/ApiResponseCode.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartPaymentSummaryResponse.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartResponse.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/Cart.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
Labels: 기능, Team Business

#1738 feat: 동아리 행사 알림 배치 스케줄링 및 행사알림 구독/구독취소 API
  src/main/java/in/koreatech/koin/_common/code/ApiResponseCode.java
  src/main/java/in/koreatech/koin/_common/model/MobileAppPath.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubEvent.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubEventRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubEventSubscriptionRepository.java
  src/main/java/in/koreatech/koin/domain/club/scheduler/ClubScheduler.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubScheduleService.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
  src/main/java/in/koreatech/koin/domain/notification/model/NotificationFactory.java
  src/main/java/in/koreatech/koin/domain/notification/model/NotificationSubscribeType.java
  src/main/resources/db/migration/V199__alter_club_event_column_index.sql
Labels: 기능, Team Campus

#1739 feat: 동아리 모집 알림 추가 및 특정 동아리 모집알림 구독/구독취소 API
  src/main/java/in/koreatech/koin/_common/event/ClubRecruitmentChangeEvent.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubRecruitmentSubscriptionRepository.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/ClubRecruitmentEventListener.java
  src/main/java/in/koreatech/koin/domain/notification/model/NotificationFactory.java
Labels: 기능, Team Campus

#1727 feat: 동아리 조회 시 모집 필터 추가
  src/main/java/in/koreatech/koin/_common/code/ApiResponseCode.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
  src/main/java/in/koreatech/koin/domain/club/enums/ClubRecruitmentStatus.java
  src/main/java/in/koreatech/koin/domain/club/enums/ClubSortType.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubBaseInfo.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubListQueryRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
Labels: 기능, Team Campus

#1737 feat: 동아리 모집 조회 API
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubRecruitmentResponse.java
  src/main/java/in/koreatech/koin/domain/club/enums/ClubRecruitmentStatus.java
  src/main/java/in/koreatech/koin/domain/club/model/Club.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubBaseInfo.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubRecruitment.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
Labels: 기능, Team Campus

#1742 feat: 동아리 행사 API 추가
  src/main/java/in/koreatech/koin/_common/code/ApiResponseCode.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubEventCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubEventModifyRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubEventResponse.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubHotStatusResponse.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
  src/main/java/in/koreatech/koin/domain/club/enums/ClubEventStatus.java
  src/main/java/in/koreatech/koin/domain/club/enums/ClubEventType.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubEvent.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubEventImage.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubEventImageRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubEventRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubHotRepository.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
  src/main/resources/db/migration/V195__add_club_event.sql
  src/main/resources/db/migration/V200__add_club_event_image.sql
Labels: Team Campus

#1745 fix: 에러코드 명세 수정
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/resources/db/migration/V195__add_club_event.sql
  src/main/resources/db/migration/V198__add_club_event_subscription.sql
  src/main/resources/db/migration/V199__add_club_event_image.sql
  src/main/resources/db/migration/V199__alter_club_event_column_index.sql
Labels: 버그, 기능, Team Campus

#1746 feat: 특정 동아리 행사 전체조회 반환값에 구독여부 추가 및 모집 알림 scheme 변경
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubEventsResponse.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubEventSubscriptionRepository.java
  src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
  src/main/java/in/koreatech/koin/domain/notification/model/NotificationFactory.java
Labels: 기능, Team Campus

#1752 fix: 동아리 조회 API 오류 수정
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubBaseInfo.java
Labels: 버그, Team Campus

#1754 fix: pr 충돌 해결
  src/main/java/in/koreatech/koin/_common/exception/GlobalExceptionHandler.java
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
Labels: 버그, 공통

#1755 feat: 상점 요약 정보 조회 API 이미지 목록 반환 & 주석 삭제
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/menu/OrderableShopMenusResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shopinfo/OrderableShopInfoSummaryResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/domain/OrderableShopInfoSummary.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/service/OrderableShopInformationService.java
Labels: Team Business

#1757 feat: 상점 메뉴 조회 API 품절 응답값 추가
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopMenuApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/menu/OrderableShopMenusResponse.java
Labels: Team Business

#1759 chore: snakecase 누락추가
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubEventResponse.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubHotStatusResponse.java
Labels: 문서, Team Campus

#1774 fix: 동아리 행사 조회 응답값 수정
  src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubEventResponse.java
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubEventsResponse.java
Labels: 버그, Team Campus

#1780 feat: 동아리 대표 전화번호 검증 추가
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubUpdateRequest.java
Labels: 기능, Team Campus

#1781 fix: 인자 순서 변경
  src/main/java/in/koreatech/koin/domain/user/verification/controller/UserVerificationController.java
Labels: 버그, Team User

#1788 hotfix: 시간표 강의 추가 동시성 방지 어노테이션 추가 (develop)
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
Labels: 버그, Team User

#1792 refactor: 비즈니스 주문 도메인 공통 에러 코드 적용
  src/main/java/in/koreatech/koin/_common/code/ApiResponseCode.java
  src/main/java/in/koreatech/koin/_common/exception/GlobalExceptionHandler.java
  src/main/java/in/koreatech/koin/domain/order/address/controller/AddressApi.java
  src/main/java/in/koreatech/koin/domain/order/address/exception/AddressErrorCode.java
  src/main/java/in/koreatech/koin/domain/order/address/exception/AddressException.java
  src/main/java/in/koreatech/koin/domain/order/address/repository/CampusDeliveryAddressRepository.java
  src/main/java/in/koreatech/koin/domain/order/address/service/client/RoadNameAddressApiErrorCodeConverter.java
  src/main/java/in/koreatech/koin/domain/order/address/service/client/RoadNameAddressClient.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/exception/CartErrorCode.java
  src/main/java/in/koreatech/koin/domain/order/cart/exception/CartException.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/Cart.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/CartMenuItem.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/OrderableShopMenuOptions.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/OrderableShopMenus.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartService.java
  src/main/java/in/koreatech/koin/domain/order/delivery/controller/DeliveryApi.java
  src/main/java/in/koreatech/koin/domain/order/delivery/exception/DeliveryErrorCode.java
  src/main/java/in/koreatech/koin/domain/order/delivery/exception/DeliveryException.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopMenuApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/exception/OrderableShopMenuNotFoundException.java
  src/main/java/in/koreatech/koin/domain/order/shop/exception/OrderableShopNotFoundException.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenu.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuOptionGroup.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/OrderableShop.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/menu/OrderableShopMenuRepository.java
  src/test/java/in/koreatech/koin/unit/domain/address/DeliveryAddressValidatorTest.java
Labels: 리팩터링, Team Business

#1804 fix: 동아리 행사 생성/수정 시작-종료날짜 입력 오류 수정
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubEventCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/dto/request/ClubEventModifyRequest.java
Labels: 버그, Team Campus

#1810 feat: 주문 가능 상점 이벤트 API
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopEventApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopEventController.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/event/OrderableShopEventsResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopBaseInfo.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopsResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/OrderableShop.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopListQueryRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/service/OrderableShopEventService.java
  src/main/java/in/koreatech/koin/domain/shop/model/event/EventArticle.java
  src/test/java/in/koreatech/koin/unit/domain/shop/EventArticleDurationTest.java
Labels: 기능, Team Business

#1813 fix: 익명 닉네임 초기화 및 영양사 정보 유지
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/resources/db/migration/V203__seperate_user_table.sql
Labels: 버그, Team User

#1821 fix: 동아리 전제 조회 시 모집 D-day 계산 로직 수정
  src/main/java/in/koreatech/koin/domain/club/model/ClubBaseInfo.java
Labels: 버그, Team Campus

#1823 fix: 동아리 전체 조회 시 정렬 로직 수정
  src/main/java/in/koreatech/koin/domain/club/dto/response/ClubRecruitmentResponse.java
  src/main/java/in/koreatech/koin/domain/club/enums/ClubRecruitmentStatus.java
  src/main/java/in/koreatech/koin/domain/club/enums/ClubSortType.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubBaseInfo.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubRecruitment.java
  src/main/java/in/koreatech/koin/domain/club/model/ClubRecruitmentDday.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubListQueryRepository.java
Labels: 버그, Team Campus

#1834 refactor: SQL 검증 실패 시 파일위치 및 SQL문 출력, 에러 스택 트레이스 추가, Swagger 성공 응답값 표시
  .github/workflows/flyway-dangerous-sql-validator.yml
  src/main/java/in/koreatech/koin/_common/code/ApiResponseCodesOperationCustomizer.java
  src/main/java/in/koreatech/koin/_common/exception/CustomException.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
  src/main/java/in/koreatech/koin/domain/user/verification/model/VerificationCode.java
  src/main/java/in/koreatech/koin/domain/user/verification/model/VerificationCount.java
  src/main/java/in/koreatech/koin/infrastructure/config/FcmConfig.java
  src/main/resources/logback-spring.xml
Labels: 리팩터링, 공통

#1833 fix: 주문 관련 테이블 수정
  src/main/java/in/koreatech/koin/domain/order/model/Order.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderDelivery.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderMenu.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderMenuOption.java
  src/main/java/in/koreatech/koin/domain/order/model/OrderTakeout.java
  src/main/resources/db/migration/V205__alter_order_nullable.sql
  src/main/resources/db/migration/V206__add_option_group_name_column.sql
  src/main/resources/db/migration/V207__alter_order_menu_table.sql
Labels: 버그, DB, Team Business

#1838 feat: 장바구니 상품 추가 API 중복 요청 멱등성 검증 처리
  src/main/java/in/koreatech/koin/_common/duplicate/DuplicateGuard.java
  src/main/java/in/koreatech/koin/_common/duplicate/DuplicateGuardAspect.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
Labels: 버그, Team Business

#1850 refactor: 동아리 검색&연관검색 기능 개선
  src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
  src/main/java/in/koreatech/koin/domain/club/model/Club.java
  src/main/java/in/koreatech/koin/domain/club/model/redis/ClubCreateRedis.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubListQueryRepository.java
  src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
Labels: 리팩터링, Team Campus

#1847 refactor: 비즈니스 1차 QA (API 명세 수정, 쿼리 튜닝)
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopController.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopCategoryFilterCriteria.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopDetailInfo.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopsFilterCriteria.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopsResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopListQueryRepository.java
  src/main/java/in/koreatech/koin/domain/order/shop/service/OrderableShopListService.java
  src/main/resources/db/migration/V209__alter_table_shop_operation_add_index.sql
  src/main/resources/db/migration/V210__alter_table_shop_reviews_add_index.sql
Labels: 기능, 리팩터링, Team Business

#1846 feat: 장바구니(CartService) 단위 테스트 작성 + 담긴 상품 수량 정보 API 등
  src/main/java/in/koreatech/koin/_common/exception/CustomException.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartAddItemCommand.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartAddItemRequest.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartItemsCountSummaryResponse.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartUpdateItemRequest.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/Cart.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/CartMenuItem.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartService.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopController.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopCategoryFilterCriteria.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuOptionGroup.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuOptionGroupMap.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/ShopOperation.java
  src/main/java/in/koreatech/koin/domain/order/shop/usecase/OrderableShopSearchUseCase.java
  src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
  src/test/java/in/koreatech/koin/unit/domain/cart/CartServiceTest.java
  src/test/java/in/koreatech/koin/unit/domain/cart/CartTest.java
  src/test/java/in/koreatech/koin/unit/domain/order/ShopOpenScheduleServiceTest.java
  src/test/java/in/koreatech/koin/unit/fixutre/CartFixture.java
  src/test/java/in/koreatech/koin/unit/fixutre/CartMenuItemFixture.java
  src/test/java/in/koreatech/koin/unit/fixutre/OrderableShopFixture.java
  src/test/java/in/koreatech/koin/unit/fixutre/OrderableShopMenuFixture.java
  src/test/java/in/koreatech/koin/unit/fixutre/OrderableShopOpenInfoFixture.java
Labels: Team Business, 테스트

#1851 fix: 비즈니스 QA 수정
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartItemsCountSummaryResponse.java
  src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
  src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopCategoryFilterCriteria.java
Labels: 버그, Team Business

#1858 docs: issue, pr template 수정
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/DEFAULT.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: 문서, 공통

#1856 refactor: 테스트 병목 유발하는 불필요한 Spring Context 로딩 제거
  .github/workflows/backend-ci.yml
  README.md
  src/test/java/in/koreatech/koin/KoinApplicationTest.java
  src/test/java/in/koreatech/koin/acceptance/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminBannerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminBannerCategoryApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminBenefitApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminCoopShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminLandApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminMemberApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminNoticeApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminOwnerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminShopReviewApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminStudentApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminTrackApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminUserApiTest.java
  src/test/java/in/koreatech/koin/acceptance/admin/AdminVersionApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/AbtestApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/ActivityApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/ArticleApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/AuthApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/BannerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/BannerCategoryApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/BenefitApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/BusApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/CircuitBreakerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/CoopShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/DeptApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/DiningApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/KeywordApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/LandApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/LectureApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/MemberApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/NotificationApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/OwnerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/SemesterApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/ShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/ShopReviewApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/ShopSearchApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/StudentApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/TimetableApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/TimetableFrameApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/TimetableFrameApiV3Test.java
  src/test/java/in/koreatech/koin/acceptance/domain/TimetableLectureApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/TimetableLectureV3ApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/TrackApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/UserApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/VersionApiTest.java
  src/test/java/in/koreatech/koin/config/TestJpaConfig.java
  src/test/java/in/koreatech/koin/config/TestRedisConfig.java
  src/test/java/in/koreatech/koin/unit/domain/shop/EventArticleDurationTest.java
Labels: 리팩터링, 공통, 테스트
