Repository BCSDLab/KOIN_API_V2, pull requests merged in 2025-01, with the labels that each got.

#1155 feat: 졸업학점 자신이 들은 학점 보여주는 기능 구현
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationController.java
  src/main/java/in/koreatech/koin/domain/graduation/dto/GraduationCourseCalculationResponse.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/StandardGraduationRequirementsRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/StudentCourseCalculationRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
  src/main/java/in/koreatech/koin/domain/student/exception/DepartmentNotFoundException.java
  src/main/java/in/koreatech/koin/domain/student/exception/StudentNumberNotFoundException.java
  src/main/java/in/koreatech/koin/domain/student/util/StudentUtil.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableFrameService.java
Labels: 기능

#1154 feat: 졸업학점 계산 동의 API 및 학과, 시간표 수정 대응
  src/main/java/in/koreatech/koin/domain/graduation/aop/GraduationAspect.java
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationApi.java
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationController.java
  src/main/java/in/koreatech/koin/domain/graduation/dto/GraduationCourseCalculationResponse.java
  src/main/java/in/koreatech/koin/domain/graduation/model/DetectGraduationCalculation.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/DetectGraduationCalculationRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/StandardGraduationRequirementsRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/StudentCourseCalculationRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
  src/main/java/in/koreatech/koin/domain/student/exception/DepartmentNotFoundException.java
  src/main/java/in/koreatech/koin/domain/student/exception/StudentNumberNotFoundException.java
  src/main/java/in/koreatech/koin/domain/student/model/Student.java
  src/main/java/in/koreatech/koin/domain/student/repository/DepartmentRepository.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/student/util/StudentUtil.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableFrameService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
  src/test/java/in/koreatech/koin/acceptance/StudentApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
  src/test/java/in/koreatech/koin/fixture/DepartmentFixture.java
Labels: 기능

#1149 feat: Semester api v3
  src/main/java/in/koreatech/koin/domain/timetable/model/Semester.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/SemesterApiV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/SemesterControllerV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/SemesterCheckResponseV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/SemesterResponseV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/model/Term.java
  src/main/java/in/koreatech/koin/domain/timetableV3/repository/SemesterRepositoryV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/repository/TimetableFrameRepositoryV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/SemesterServiceV3.java
  src/main/resources/db/migration/V109__alter__semester.sql
  src/test/java/in/koreatech/koin/acceptance/SemesterApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
  src/test/java/in/koreatech/koin/fixture/SemesterFixture.java
Labels: 기능

#1158 feat: 스웨거 그룹 timetableV3 추가
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/SemesterControllerV3.java
  src/main/java/in/koreatech/koin/global/config/swagger/SwaggerGroupConfig.java
Labels: 기능

#1156 feat: lecture, timetableLecture API v3
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/LectureApiV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/LectureControllerV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableCustomLectureApiV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableCustomLectureControllerV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableLectureApiV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableLectureControllerV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableRegularLectureApiV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableRegularLectureControllerV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/LectureInfoRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableCustomLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableCustomLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/LectureInfoResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/LectureResponseV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/TimetableLectureResponseV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/model/Term.java
  src/main/java/in/koreatech/koin/domain/timetableV3/repository/LectureRepositoryV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/repository/SemesterRepositoryV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/repository/TimetableFrameRepositoryV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/repository/TimetableLectureRepositoryV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/LectureServiceV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableCustomLectureServiceV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableLectureServiceV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/utils/ClassTimeUtils.java
  src/test/java/in/koreatech/koin/acceptance/LectureApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableLectureV3ApiTest.java
Labels: 기능, Team User

#1160 feat: timetable frame v3
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableFrameApiV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableFrameControllerV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableFrameCreateRequestV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableFrameUpdateRequestV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/TimetableFrameResponseV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/TimetableFramesResponseV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/exception/InvalidTermFormatException.java
  src/main/java/in/koreatech/koin/domain/timetableV3/model/Term.java
  src/main/java/in/koreatech/koin/domain/timetableV3/repository/TimetableFrameRepositoryV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableFrameServiceV3.java
  src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiV3Test.java
Labels: 기능, Team User

#1166 fix: 커스텀 강의 생성 유효성 검증 추가
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/LectureInfoRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableCustomLectureCreateRequest.java
Labels: 버그, Team User

#1168 hotfix: timetableV2 온라인 강의 응답 오류 수정 (main)
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableLectureResponse.java
Labels: 버그, Team User

#1162 docs: reviewer.json 최신화
  .github/workflows/reviewer.json
Labels: 문서, 기능

#1169 hotfix: timetableV2 온라인 강의 응답 오류 수정 (develop)
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableLectureResponse.java
Labels: 버그, Team User

#1172 fix: 2025년 1학기 업데이트 쿼리 추가
  src/main/resources/db/migration/V109__alter__semester.sql
Labels: 버그

#1170 feat : 분실물 게시글 API 구현
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticleRequest.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticleResponse.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticlesRequest.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticlesResponse.java
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/article/model/LostItemArticle.java
  src/main/java/in/koreatech/koin/domain/community/article/model/LostItemImage.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/LostItemArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEventListener.java
  src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
  src/main/java/in/koreatech/koin/domain/user/model/UserType.java
  src/main/resources/db/migration/V110__add_lost_item_image_table.sql
Labels: 기능, Team Campus

#1173 fix: 권한 추가 및 분실물 게시글 작성 response 수정
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/main/java/in/koreatech/koin/domain/community/keyword/controller/KeywordApi.java
  src/main/java/in/koreatech/koin/domain/community/keyword/controller/KeywordController.java
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopReviewApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopReviewController.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentController.java
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
  src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/SemesterApiV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/SemesterControllerV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableCustomLectureApiV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableCustomLectureControllerV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableFrameApiV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableFrameControllerV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableLectureApiV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableLectureControllerV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableRegularLectureApiV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableRegularLectureControllerV3.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/global/domain/notification/controller/NotificationApi.java
  src/main/java/in/koreatech/koin/global/domain/notification/controller/NotificationController.java
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
  src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadController.java
Labels: 버그, Team Campus

#1152 fix: 시내버스 시간표 한기대 출발 시간 보정
  src/main/java/in/koreatech/koin/domain/bus/dto/CityBusTimetableResponse.java
  src/main/java/in/koreatech/koin/domain/bus/model/enums/CityBusDirection.java
  src/main/java/in/koreatech/koin/domain/bus/model/mongo/CityBusTimetable.java
  src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
Labels: 버그, Team Campus

#1177 fix: 사장님 회원가입 에러 수정
  src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
  src/main/java/in/koreatech/koin/domain/owner/model/dto/OwnerRegisterEvent.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerSmsService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerUtilService.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
Labels: 버그, Team Business

#1179 feat: timetable v3 졸업학점계산기 로직 추가
  src/main/java/in/koreatech/koin/domain/graduation/model/Catalog.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableLectureResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureUpdater.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/TimetableLectureResponseV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
  src/main/resources/db/migration/V111__add_course_type.sql
  src/main/resources/db/migration/V112__add_department.sql
  src/main/resources/db/migration/V113__add_standard_graduation_requirements.sql
  src/main/resources/db/migration/V114__add_student_course_calculation.sql
  src/main/resources/db/migration/V115__alter_fk_course_type_on_timetable.sql
  src/main/resources/db/migration/V116__add_catalog.sql
  src/main/resources/db/migration/V117__add_detect_graduation_calculation.sql
  src/main/resources/db/migration/V118__alter_student_department_fk.sql
Labels: 기능, Team User

#1182 fix: 새로운 사장님 조회 로직 버그 수정
  src/main/java/in/koreatech/koin/admin/owner/service/AdminOwnerService.java
Labels: 버그

#1186 fix: 분실물 게시판 QA 이슈 해결
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticleRequest.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticleResponse.java
  src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticlesRequest.java
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/article/model/LostItemArticle.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEventListener.java
  src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
  src/main/java/in/koreatech/koin/domain/community/util/KeywordExtractor.java
  src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
  src/test/java/in/koreatech/koin/acceptance/ArticleApiTest.java
Labels: 버그, Team Campus

#1189 feat: 미포함 API 스웨거 그룹화
  src/main/java/in/koreatech/koin/global/config/swagger/SwaggerGroupConfig.java
Labels: 기능

#1201 feat: gradle cache 활성화
  gradle.properties
Labels: 기능

#1184 feat : 학기와 이수구분으로 강의 찾기
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationApi.java
  src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationController.java
  src/main/java/in/koreatech/koin/domain/graduation/dto/CourseTypeLectureResponse.java
  src/main/java/in/koreatech/koin/domain/graduation/dto/LecturePortionResponse.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CourseTypeRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/DetectGraduationCalculationRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/StudentCourseCalculationRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/exception/NotFoundSemesterAndCourseTypeException.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/LectureRepositoryV2.java
  src/main/java/in/koreatech/koin/global/config/swagger/SwaggerGroupConfig.java
  src/main/resources/db/migration/V116__add_catalog.sql
  src/main/resources/db/migration/V117__add_detect_graduation_calculation.sql
Labels: 기능, Team User

#1192 Feat: major 요소 추가 및 로직수정
  src/main/java/in/koreatech/koin/domain/graduation/model/Catalog.java
  src/main/java/in/koreatech/koin/domain/graduation/model/StandardGraduationRequirements.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/StandardGraduationRequirementsRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
  src/main/java/in/koreatech/koin/domain/student/exception/MajorNotFoundException.java
  src/main/java/in/koreatech/koin/domain/student/model/Major.java
  src/main/java/in/koreatech/koin/domain/student/model/Student.java
  src/main/java/in/koreatech/koin/domain/student/repository/MajorRepository.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/resources/db/migration/V113__add_major.sql
  src/main/resources/db/migration/V114__add_standard_graduation_requirements.sql
  src/main/resources/db/migration/V115__add_student_course_calculation.sql
  src/main/resources/db/migration/V116__alter_fk_course_type_on_timetable.sql
  src/main/resources/db/migration/V117__add_catalog.sql
  src/main/resources/db/migration/V118__add_detect_graduation_calculation.sql
  src/main/resources/db/migration/V119__alter_student_department_fk.sql
  src/main/resources/db/migration/V120__alter_student_add_column_major.sql
Labels: 기능

#1205 feat: 교양 영역 테이블 추가
  src/main/java/in/koreatech/koin/domain/graduation/model/Catalog.java
  src/main/java/in/koreatech/koin/domain/graduation/model/GeneralEducationArea.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
  src/main/resources/db/migration/V116__add_general_education_area.sql
  src/main/resources/db/migration/V117__alter_fk_course_type_on_timetable.sql
  src/main/resources/db/migration/V118__add_catalog.sql
  src/main/resources/db/migration/V119__add_detect_graduation_calculation.sql
  src/main/resources/db/migration/V120__alter_student_department_fk.sql
  src/main/resources/db/migration/V121__alter_student_add_column_major.sql
Labels: 기능, Team User
