Repository BCSDLab/KOIN_API_V2, pull requests merged in 2025-03, with the labels that each got.

#1316 fix: 졸학계 로직 주석 처리
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
Labels: 버그, Team User

#1318 fix: 졸학계 로직 주석 처리 원복
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
Labels: 버그, Team User

#1320 fix: 분실물 게시글 조회 시 is_deleted 미적용 버그 수정
  src/main/java/in/koreatech/koin/domain/community/article/model/LostItemArticle.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
Labels: 버그, Team Campus

#1319 fix: 교양영역 및 NPE 버그 수정
  src/main/java/in/koreatech/koin/domain/graduation/enums/GeneralEducationAreaEnum.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
  src/main/java/in/koreatech/koin/domain/student/util/StudentUtil.java
Labels: 버그

#1326 fix: 졸학계 로직 주석 처리
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
Labels: 버그, Team User

#1327 fix: 졸학계 로직 주석 처리 원복
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
Labels: 버그, Team User

#1324 feat : 정규 강의 general_education_area 수정 추가
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
Labels: 기능, Team User

#1331 fix : 정규 강의 수정 lecture NPE 문제 해결
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureUpdateRequest.java
Labels: 버그, Team User

#1334 fix: 졸학계 계산 테이블 초기화 오류 수정
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
Labels: 버그

#1332 feat: 25-1학기 생협 운영장 시간 업데이트
  src/main/resources/db/migration/V136__update_coopshop_timatable_25_1.sql
Labels: 기능, Team Campus

#1336 fix: 졸학계 계산 테이블 유니크 제약조건 추가
  src/main/resources/db/migration/V136__alter_graduation_calculation_unique_cascade.sql
Labels: 버그

#1338 fix: V136 -> V137 flyway 버전 변경
  src/main/resources/db/migration/V137__alter_graduation_calculation_unique_cascade.sql
Labels: 버그

#1340 fix: 졸학계 계산 유니크 제약조건 임시 제거
  src/main/resources/db/migration/V138__alter_drop_graduation_calculation_unique.sql
Labels: 버그

#1328 fix: 졸업학점 계산 로직 에러 수정
  src/main/java/in/koreatech/koin/domain/graduation/model/StudentCourseCalculation.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/StandardGraduationRequirementsRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/repository/StudentCourseCalculationRepository.java
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableLectureRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV3/exception/ChangeMajorNotExistException.java
  src/main/resources/db/migration/V138__alter_drop_graduation_calculation_unique.sql
Labels: 버그

#1342 feat: 졸업학점 계산기 변경 감지 aop 포인트 컷 추가
  src/main/java/in/koreatech/koin/domain/graduation/aop/GraduationAspect.java
Labels: Team User

#1344 hotfix: 셔틀버스 도착 시각 수정 (main)
  src/main/java/in/koreatech/koin/domain/bus/service/model/route/ShuttleBusRouteStrategy.java
  src/main/java/in/koreatech/koin/domain/bus/service/shuttle/ShuttleBusRepository.java
Labels: 버그, Team Campus

#1346 fix : 학적 정보 중복 삽입 문제 해결
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
Labels: 버그, Team User

#1347 hotfix: 셔틀버스 도착 시각 수정 (develop)
  src/main/java/in/koreatech/koin/domain/bus/service/model/route/ShuttleBusRouteStrategy.java
  src/main/java/in/koreatech/koin/domain/bus/service/shuttle/ShuttleBusRepository.java
Labels: 버그, Team Campus

#1351 feat: 회원가입 인증 시 major 지정
  src/main/java/in/koreatech/koin/domain/student/model/redis/StudentTemporaryStatus.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/test/java/in/koreatech/koin/acceptance/StudentApiTest.java
Labels: 기능, Team User

#1321 refactor: 유저팀 리펙토링
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopApi.java
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopController.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerUtilService.java
  src/main/java/in/koreatech/koin/domain/student/model/redis/UnAuthenticatedStudentInfo.java
  src/main/java/in/koreatech/koin/domain/student/repository/StudentRedisRepository.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentValidationService.java
  src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureUpdateRequest.java
  src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableFrameUpdateResponse.java
  src/main/java/in/koreatech/koin/domain/timetableV2/exception/ExcelFileCheckException.java
  src/main/java/in/koreatech/koin/domain/timetableV2/exception/ExcelFileNotFoundException.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableFrameCreator.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableFrameUpdater.java
  src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureUpdater.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
  src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
  src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableFrameService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
  src/main/java/in/koreatech/koin/domain/timetableV2/validation/TimetableFrameValidate.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableCustomLectureServiceV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableFrameServiceV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableLectureServiceV3.java
  src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserPasswordResetTokenRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserTokenRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/RefreshTokenService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
  src/test/java/in/koreatech/koin/acceptance/AuthApiTest.java
  src/test/java/in/koreatech/koin/acceptance/StudentApiTest.java
Labels: 리팩터링, Team User

#1358 fix : (졸학계) F학점 수업 처리 추가
  src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
Labels: 버그

#1364 fix: eolf 수정
  src/main/resources/db/migration/V137__alter_graduation_calculation_unique_cascade.sql
Labels: 버그

#1366 fix: admin land NPE 해결
  src/main/java/in/koreatech/koin/admin/land/controller/AdminLandController.java
  src/main/java/in/koreatech/koin/admin/land/dto/AdminLandResponse.java
  src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
  src/main/java/in/koreatech/koin/domain/land/model/Land.java
Labels: 버그

#1368 refactor: 미사용 테이블 및 컬럼 삭제
  src/main/java/in/koreatech/koin/domain/timetable/model/Timetable.java
  src/main/java/in/koreatech/koin/domain/timetable/repository/TimetableRepository.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/resources/db/migration/V139__delete_legacy_table_and_column.sql
  src/test/java/in/koreatech/koin/acceptance/AuthApiTest.java
  src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
  src/test/java/in/koreatech/koin/fixture/TimetableFixture.java
  src/test/java/in/koreatech/koin/fixture/UserFixture.java
Labels: 리팩터링

#1370 hotfix: error code string으로 변경
  src/main/java/in/koreatech/koin/_common/exception/ErrorResponse.java
Labels: 버그

#1371 hotfix : 학적 정보 업데이트 NPE 해결 (main)
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
Labels: 버그, Team User

#1372 hotfix : 학적 정보 업데이트 NPE 해결 (develop)
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
Labels: 버그, Team User

#1375 fix: ArticleApi deleteLostItemArticle auth의 STUDENT 누락 추가
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
Labels: 버그

#1373 refactor: 플랫폼 별 리프레쉬 토큰 발급
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
  src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
  src/main/java/in/koreatech/koin/admin/user/repository/AdminTokenRepository.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopApi.java
  src/main/java/in/koreatech/koin/domain/coop/controller/CoopController.java
  src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
  src/main/java/in/koreatech/koin/domain/owner/controller/SmsBasedOwnerApi.java
  src/main/java/in/koreatech/koin/domain/owner/controller/SmsBasedOwnerController.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerSmsService.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerUtilService.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentController.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/model/RefreshToken.java
  src/main/java/in/koreatech/koin/domain/user/model/UserToken.java
  src/main/java/in/koreatech/koin/domain/user/repository/RefreshTokenRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserTokenRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/RefreshTokenService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/test/java/in/koreatech/koin/acceptance/AuthApiTest.java
  src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
  src/test/java/in/koreatech/koin/acceptance/StudentApiTest.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
  src/test/java/in/koreatech/koin/fixture/UserFixture.java
Labels: 리팩터링, Team User

#1379 fix: 단일 분실물 게시글 조회 NPE 수정
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
Labels: 버그, Team Campus

#1391 fix: 탈퇴한 사용자의 분실물 채팅에서 발생하는 버그 수정
  src/main/java/in/koreatech/koin/socket/domain/chatroom/service/LostItemChatRoomInfoService.java
Labels: 버그, Team Campus

#1389 feat: 배너 및 배너 카테고리 테이블 추가
  src/main/java/in/koreatech/koin/domain/banner/model/Banner.java
  src/main/java/in/koreatech/koin/domain/banner/model/BannerCategory.java
  src/main/resources/db/migration/V140__add_banner_category_table.sql
  src/main/resources/db/migration/V141__add_banners_table.sql
Labels: 기능, Team Campus

#1392 feat: 배너 어드민 CRD 작업을 한다
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerApi.java
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerCategoryApi.java
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerCategoryController.java
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerController.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerCreateRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannerCategoriesResponse.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannerResponse.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannersResponse.java
  src/main/java/in/koreatech/koin/admin/banner/exception/BannerCategoryNotFoundException.java
  src/main/java/in/koreatech/koin/admin/banner/exception/BannerNotFoundException.java
  src/main/java/in/koreatech/koin/admin/banner/repository/AdminBannerCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/banner/repository/AdminBannerRepository.java
  src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerCategoryService.java
  src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerService.java
  src/main/java/in/koreatech/koin/domain/banner/model/Banner.java
  src/main/resources/db/migration/V142__alter_banner_priority_nullable.sql
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBannerApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBannerCategoryApiTest.java
  src/test/java/in/koreatech/koin/fixture/BannerCategoryFixture.java
  src/test/java/in/koreatech/koin/fixture/BannerFixture.java
Labels: 기능, Team Campus

#1393 feat: 어드민 특정 배너의 우선순위 수정, 활성화 상태 수정, 상세 수정 API
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerApi.java
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerController.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerActiveChangeRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerModifyRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerPriorityChangeRequest.java
  src/main/java/in/koreatech/koin/admin/banner/enums/PriorityChangeType.java
  src/main/java/in/koreatech/koin/admin/banner/repository/AdminBannerRepository.java
  src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerService.java
  src/main/java/in/koreatech/koin/domain/banner/model/Banner.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBannerApiTest.java
Labels: 기능, Team Campus

#1399 feat: 상점 리뷰 하루 한번으로 제한하기
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopReviewApi.java
  src/main/java/in/koreatech/koin/domain/shop/exception/OneReviewPerDayException.java
  src/main/java/in/koreatech/koin/domain/shop/repository/review/ShopReviewRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
  src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
Labels: Team Business

#1397 feat: 어드민 배너 삭제 시 우선순위 조정 로직 구현
  src/main/java/in/koreatech/koin/admin/banner/repository/AdminBannerRepository.java
  src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerService.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBannerApiTest.java
Labels: 기능, Team Campus

#1401 fix: 스웨거 그룹화 설정 파일 수정
  src/main/java/in/koreatech/koin/web/config/SwaggerGroupConfig.java
Labels: 버그

#1061 refactor: 많이 조회한 게시글 키워드 구조 변경
  src/main/java/in/koreatech/koin/domain/community/article/model/ArticleSearchKeyword.java
  src/main/java/in/koreatech/koin/domain/community/article/model/ArticleSearchKeywordIpMap.java
  src/main/java/in/koreatech/koin/domain/community/article/model/KeywordRankingManager.java
  src/main/java/in/koreatech/koin/domain/community/article/model/redis/PopularKeywordTracker.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleSearchKeywordRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/scheduler/ArticleScheduler.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleSyncService.java
Labels: 리팩터링

#1407 feat: 일반인 유저타입 추가
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
  src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
  src/main/java/in/koreatech/koin/domain/community/article/controller/LostItemReportApi.java
  src/main/java/in/koreatech/koin/domain/community/article/controller/LostItemReportController.java
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
  src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
  src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/model/UserType.java
  src/main/java/in/koreatech/koin/integration/fcm/notification/controller/NotificationApi.java
  src/main/java/in/koreatech/koin/integration/fcm/notification/controller/NotificationController.java
  src/main/java/in/koreatech/koin/integration/s3/controller/UploadApi.java
  src/main/java/in/koreatech/koin/integration/s3/controller/UploadController.java
  src/main/java/in/koreatech/koin/socket/domain/chatroom/controller/ChatRestApi.java
  src/main/java/in/koreatech/koin/socket/domain/chatroom/controller/ChatRestController.java
Labels: 기능, Team User

#1412 feat: 배너 테이블 컬럼 추가 및 업로드 API 도메인 추가
  src/main/java/in/koreatech/koin/_common/callcontroller/CallControl.java
  src/main/java/in/koreatech/koin/_common/callcontroller/CallController.java
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerCategoryApi.java
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerCategoryController.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerCategoryDescriptionModifyRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerCreateRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerModifyRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannerCategoriesResponse.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannerCategoryResponse.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannerResponse.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannersResponse.java
  src/main/java/in/koreatech/koin/admin/banner/exception/BannerMobileFieldPairNotMatchException.java
  src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerCategoryService.java
  src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerService.java
  src/main/java/in/koreatech/koin/domain/banner/dto/response/BannersResponse.java
  src/main/java/in/koreatech/koin/domain/banner/model/Banner.java
  src/main/java/in/koreatech/koin/domain/banner/model/BannerCategory.java
  src/main/java/in/koreatech/koin/domain/bus/service/cache/BusCacheService.java
  src/main/java/in/koreatech/koin/domain/bus/service/express/client/PublicExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/service/express/client/StaticExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/service/express/client/TmoneyExpressBusClient.java
  src/main/java/in/koreatech/koin/integration/s3/model/ImageUploadDomain.java
  src/main/resources/db/migration/V140__add_banner_category_table.sql
  src/main/resources/db/migration/V141__add_banners_table.sql
  src/main/resources/db/migration/V142__alter_banner_priority_nullable.sql
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBannerApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBannerCategoryApiTest.java
  src/test/java/in/koreatech/koin/fixture/BannerCategoryFixture.java
  src/test/java/in/koreatech/koin/fixture/BannerFixture.java
Labels: 기능, Team Campus

#1415 feat: 배너 광고 기능 추가
  src/main/java/in/koreatech/koin/_common/callcontroller/CallControl.java
  src/main/java/in/koreatech/koin/_common/callcontroller/CallController.java
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerApi.java
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerCategoryApi.java
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerCategoryController.java
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerController.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerActiveChangeRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerCategoryDescriptionModifyRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerCreateRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerModifyRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerPriorityChangeRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannerCategoriesResponse.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannerCategoryResponse.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannerResponse.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannersResponse.java
  src/main/java/in/koreatech/koin/admin/banner/enums/PriorityChangeType.java
  src/main/java/in/koreatech/koin/admin/banner/exception/BannerCategoryNotFoundException.java
  src/main/java/in/koreatech/koin/admin/banner/exception/BannerMobileFieldPairNotMatchException.java
  src/main/java/in/koreatech/koin/admin/banner/exception/BannerNotFoundException.java
  src/main/java/in/koreatech/koin/admin/banner/repository/AdminBannerCategoryRepository.java
  src/main/java/in/koreatech/koin/admin/banner/repository/AdminBannerRepository.java
  src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerCategoryService.java
  src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerService.java
  src/main/java/in/koreatech/koin/domain/banner/controller/BannerApi.java
  src/main/java/in/koreatech/koin/domain/banner/controller/BannerController.java
  src/main/java/in/koreatech/koin/domain/banner/dto/response/BannersResponse.java
  src/main/java/in/koreatech/koin/domain/banner/enums/PlatformType.java
  src/main/java/in/koreatech/koin/domain/banner/exception/PlatformTypeNotFoundException.java
  src/main/java/in/koreatech/koin/domain/banner/model/Banner.java
  src/main/java/in/koreatech/koin/domain/banner/model/BannerCategory.java
  src/main/java/in/koreatech/koin/domain/banner/repository/BannerRepository.java
  src/main/java/in/koreatech/koin/domain/banner/service/BannerService.java
  src/main/java/in/koreatech/koin/domain/bus/service/cache/BusCacheService.java
  src/main/java/in/koreatech/koin/domain/bus/service/express/client/PublicExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/service/express/client/StaticExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/service/express/client/TmoneyExpressBusClient.java
  src/main/java/in/koreatech/koin/integration/s3/model/ImageUploadDomain.java
  src/main/java/in/koreatech/koin/web/config/SwaggerGroupConfig.java
  src/main/resources/db/migration/V140__add_banner_category_table.sql
  src/main/resources/db/migration/V141__add_banners_table.sql
  src/test/java/in/koreatech/koin/acceptance/BannerApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBannerApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBannerCategoryApiTest.java
  src/test/java/in/koreatech/koin/fixture/BannerCategoryFixture.java
  src/test/java/in/koreatech/koin/fixture/BannerFixture.java
Labels: 기능, Team Campus

#1411 feat: 중복 전화번호를 검증한다.
  .github/assign_label_reviewers.yml
  src/main/java/in/koreatech/koin/_common/apiloadbalancer/ApiLoadBalance.java
  src/main/java/in/koreatech/koin/_common/apiloadbalancer/ApiLoadBalancer.java
  src/main/java/in/koreatech/koin/domain/bus/service/cache/BusCacheService.java
  src/main/java/in/koreatech/koin/domain/bus/service/express/client/PublicExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/service/express/client/StaticExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/bus/service/express/client/TmoneyExpressBusClient.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/PhoneCheckExistsRequest.java
  src/main/java/in/koreatech/koin/domain/user/exception/DuplicationPhoneNumberException.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
  src/main/java/in/koreatech/koin/integration/email/exception/DuplicationEmailException.java
  src/test/java/in/koreatech/koin/acceptance/UploadServiceTest.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
  src/test/java/in/koreatech/koin/fixture/UserFixture.java
Labels: 기능, Team User

#1418 feat: Normal 배너 조회 API 추가
  src/main/java/in/koreatech/koin/domain/banner/controller/BannerCategoryApi.java
  src/main/java/in/koreatech/koin/domain/banner/controller/BannerCategoryController.java
  src/main/java/in/koreatech/koin/domain/banner/dto/response/BannerCategoriesResponse.java
  src/main/java/in/koreatech/koin/domain/banner/repository/BannerCategoryRepository.java
  src/main/java/in/koreatech/koin/domain/banner/service/BannerCategoryService.java
  src/main/java/in/koreatech/koin/integration/s3/controller/UploadApi.java
  src/test/java/in/koreatech/koin/acceptance/BannerCategoryApiTest.java
Labels: 기능, Team Campus

#1381 refactor: 인기게시글 목록 조회 n+1, 지연로딩 문제해결
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
Labels: 리팩터링, Team Campus

#1420 fix: 누락된 import추가
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
Labels: 버그, Team Campus

#1422 fix: 인기 게시글 조회 로직 롤백
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
Labels: 버그, Team Campus

#1414 feat: CI를 통해 개발 효율성을 높인다.
  .github/assign_label_reviewers.yml
  .github/auto_assign_team_business.yml
  .github/auto_assign_team_campus.yml
  .github/auto_assign_team_user.yml
  .github/workflows/backend-ci.yml
  .github/workflows/pr-check-title.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/pr-reviewers-by-label.yml
  .github/workflows/reviewer.json
Labels: 기능

#1427 fix: pr title refactor 제한 추가
  .github/workflows/pr-check-title.yml
Labels: 버그, 기능

#1424 refactor: 인기 게시글 조회 새 로직 적용
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
Labels: 리팩터링, Team Campus

#1416 feat: 회원 전화번호를 인증 및 검증한다.
  src/main/java/in/koreatech/koin/_common/auth/ExtractAuthenticationInterceptor.java
  src/main/java/in/koreatech/koin/_common/auth/JwtProvider.java
  src/main/java/in/koreatech/koin/_common/auth/SmsAuthed.java
  src/main/java/in/koreatech/koin/_common/auth/SmsAuthedArgumentResolver.java
  src/main/java/in/koreatech/koin/_common/auth/SmsAuthedContext.java
  src/main/java/in/koreatech/koin/_common/event/UserSmsRequestEvent.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/SendSmsVerificationRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/VerifySmsCodeRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/VerifySmsCodeResponse.java
  src/main/java/in/koreatech/koin/domain/user/exception/UserVerificationDailyLimitExceededException.java
  src/main/java/in/koreatech/koin/domain/user/model/UserDailyVerifyCount.java
  src/main/java/in/koreatech/koin/domain/user/model/UserEventListener.java
  src/main/java/in/koreatech/koin/domain/user/model/UserVerificationStatus.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserVerificationLimitRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserVerificationStatusRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/UserSmsService.java
  src/main/java/in/koreatech/koin/integration/slack/model/SlackNotificationFactory.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 기능, Team User

#1429 feat: 어드민 히스토리 PATCH 요청 추가 및 도메인 추가
  src/main/java/in/koreatech/koin/admin/history/aop/AdminActivityHistoryAspect.java
  src/main/java/in/koreatech/koin/admin/history/enums/DomainType.java
  src/main/java/in/koreatech/koin/admin/history/enums/HttpMethodType.java
Labels: 기능, Team Campus

#1435 fix: 리뷰어 자동 지정이 PR이 열렸을 때도 동작되도록 수정한다.
  .github/workflows/pr-reviewers-by-label.yml
  src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/socket/domain/session/service/UserSessionService.java
  src/main/java/in/koreatech/koin/socket/interceptor/ConnectInterceptor.java
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 버그

#1437 feat: Normal Banner API 배너 이름 응답값 추가
  src/main/java/in/koreatech/koin/domain/banner/dto/response/BannersResponse.java
  src/test/java/in/koreatech/koin/acceptance/BannerApiTest.java
Labels: 기능, Team Campus
