Repository BCSDLab/KOIN_API_V2, pull requests merged in 2025-10, with the labels that each got.

#2007 feat: ClubEvent 서비스 단위 테스트 작성 (1차)
  src/main/java/in/koreatech/koin/domain/club/event/model/ClubEvent.java
  src/main/java/in/koreatech/koin/domain/student/model/Student.java
  src/test/java/in/koreatech/koin/unit/domain/club/service/ClubEventServiceTest.java
  src/test/java/in/koreatech/koin/unit/fixture/StudentFixture.java
Labels: Team Campus, 테스트

#2020 feat: logback 롤링 도입
  src/main/resources/logback-spring.xml
Labels: 공통

#2024 feat: 진행 중인 주문 조회 시 주문 가능한 상점 ID를 응답하도록 변경
  src/main/java/in/koreatech/koin/domain/order/order/controller/OrderApi.java
  src/main/java/in/koreatech/koin/domain/order/order/dto/response/InprogressOrderResponse.java
Labels: Team Business

#2030 refactor: order swagger description LAST_6_MONTHS 수정
  src/main/java/in/koreatech/koin/domain/order/order/controller/OrderApi.java
Labels: 리팩터링, Team Business
