Repository BCSDLab/KOIN_API_V2, pull requests merged in 2025-08, with the labels that each got.

#1860 refactor: 비즈니스 2차 QA (장바구니 상품 수정 API)
  src/main/java/in/koreatech/koin/domain/community/lostitem/chatroom/service/LostItemChatRoomInfoService.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartMenuItemEditResponse.java
  src/main/java/in/koreatech/koin/domain/order/cart/dto/CartUpdateItemRequest.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/CartMenuItem.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartService.java
  src/test/java/in/koreatech/koin/unit/domain/cart/CartServiceTest.java
Labels: 리팩터링, Team Business

#1863 feat: 분실물 채팅방 생성 및 조회 서비스 테스트 코드 작성
  src/test/java/in/koreatech/koin/unit/domain/community/lostitem/chatroom/service/LostItemChatRoomInfoServiceTest.java
  src/test/java/in/koreatech/koin/unit/fixutre/LostItemArticleFixture.java
  src/test/java/in/koreatech/koin/unit/fixutre/LostItemChatFixture.java
Labels: 테스트

#1868 fix: 비즈니스 3차 QA - 장바구니 검증 API 주문 타입 조건 추가
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
  src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
  src/main/java/in/koreatech/koin/domain/order/cart/model/Cart.java
  src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
  src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/OrderableShop.java
Labels: 버그, Team Business

#1873 refactor: fixutre 디렉토리명 fixture로 수정
  src/test/java/in/koreatech/koin/unit/domain/address/DeliveryAddressValidatorTest.java
  src/test/java/in/koreatech/koin/unit/domain/cart/CartServiceTest.java
  src/test/java/in/koreatech/koin/unit/domain/cart/CartTest.java
  src/test/java/in/koreatech/koin/unit/domain/community/lostitem/chatroom/service/LostItemChatRoomInfoServiceTest.java
  src/test/java/in/koreatech/koin/unit/domain/order/ShopOpenScheduleServiceTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/model/UserTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/model/VerificationCodeTest.java
  src/test/java/in/koreatech/koin/unit/domain/user/verification/model/VerificationCountTest.java
  src/test/java/in/koreatech/koin/unit/fixture/AddressFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/AdminFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/CartFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/CartMenuItemFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/LostItemArticleFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/LostItemChatFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/OrderableShopFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/OrderableShopMenuFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/OrderableShopOpenInfoFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/OwnerFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/StudentFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/UserFixture.java
  src/test/java/in/koreatech/koin/unit/fixture/VerificationFixture.java
Labels: 리팩터링, 공통

#1879 hotfix: 키워드 알림 중복 발송 문제 해결 (main)
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/main/java/in/koreatech/koin/domain/community/keyword/model/UserNotificationStatus.java
  src/main/java/in/koreatech/koin/domain/community/keyword/repository/UserNotificationStatusRepository.java
  src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
  src/main/java/in/koreatech/koin/domain/notification/eventlistener/ArticleKeywordEventListener.java
Labels: 버그, Team Campus

#1878 refactor: 인수 테스트 과정에서 불필요한 DB 초기화 쿼리 실행 개선
  src/test/java/in/koreatech/koin/acceptance/AcceptanceTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/BusApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/DiningApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/KeywordApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/OwnerShopApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/ShopReviewApiTest.java
  src/test/java/in/koreatech/koin/acceptance/domain/StudentApiTest.java
  src/test/java/in/koreatech/koin/acceptance/support/DBInitializer.java
Labels: 리팩터링, 공통, 테스트

#1888 refactor: 모든 상점 이벤트 조회 쿼리 개선
  src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopRepository.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopEventService.java
Labels: 리팩터링, Team Business
