Repository BCSDLab/KOIN_API_V2, pull requests merged in 2025-04, with the labels that each got.

#1433 feat: 배너 생성, 수정 DTO 패턴 검증 추가 및 수정 로직 내 값 추가
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerCreateRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerModifyRequest.java
  src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerService.java
  src/main/java/in/koreatech/koin/domain/banner/model/Banner.java
  src/test/java/in/koreatech/koin/acceptance/BannerApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBannerApiTest.java
  src/test/java/in/koreatech/koin/fixture/BannerFixture.java
Labels: 버그, Team Campus

#1439 feat: Admin Banner API 배포 여부 컬럼 추가
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerApi.java
  src/main/java/in/koreatech/koin/admin/banner/controller/AdminBannerController.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerCreateRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/request/AdminBannerModifyRequest.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannerResponse.java
  src/main/java/in/koreatech/koin/admin/banner/dto/response/AdminBannersResponse.java
  src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerService.java
  src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerValidator.java
  src/main/java/in/koreatech/koin/domain/banner/controller/BannerApi.java
  src/main/java/in/koreatech/koin/domain/banner/dto/response/BannersResponse.java
  src/main/java/in/koreatech/koin/domain/banner/model/Banner.java
  src/main/resources/db/migration/V142__add_banner_column_is_release.sql
  src/test/java/in/koreatech/koin/admin/acceptance/AdminBannerApiTest.java
  src/test/java/in/koreatech/koin/fixture/BannerFixture.java
Labels: 기능, Team Campus

#1430 feat: 일반인/학생 회원가입 플로우 분리
  src/main/java/in/koreatech/koin/admin/user/dto/CreateAdminRequest.java
  src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
  src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerRegisterByPhoneRequest.java
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerSmsService.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentController.java
  src/main/java/in/koreatech/koin/domain/student/dto/StudentRegisterRequestV2.java
  src/main/java/in/koreatech/koin/domain/student/model/redis/UnAuthenticatedStudentInfo.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/GeneralUserRegisterRequest.java
  src/main/java/in/koreatech/koin/domain/user/model/User.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/resources/db/migration/V143__add_column_user_id.sql
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminOwnerApiTest.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminStudentApiTest.java
  src/test/java/in/koreatech/koin/fixture/UserFixture.java
Labels: 기능, Team User

#1445 feat: 모든상점조회V2 이벤트 기반 캐시 갱신 도입
  src/main/java/in/koreatech/koin/_common/event/ShopsCacheRefreshEvent.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopMenuService.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopReviewService.java
  src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerEventService.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerMenuService.java
  src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
  src/main/java/in/koreatech/koin/domain/shop/cache/ShopsCacheRefreshListener.java
  src/main/java/in/koreatech/koin/domain/shop/cache/aop/RefreshShopsCache.java
  src/main/java/in/koreatech/koin/domain/shop/cache/aop/RefreshShopsCacheAspect.java
  src/main/java/in/koreatech/koin/domain/shop/scheduler/CacheShopsScheduler.java
  src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
Labels: 버그

#1446 feat: 코인 공지사항 테이블 추가
  src/main/java/in/koreatech/koin/admin/notice/controller/AdminNoticeController.java
  src/main/java/in/koreatech/koin/admin/notice/dto/AdminNoticeResponse.java
  src/main/java/in/koreatech/koin/admin/notice/dto/AdminNoticesResponse.java
  src/main/java/in/koreatech/koin/admin/notice/model/KoinNotice.java
  src/main/java/in/koreatech/koin/admin/notice/repository/AdminKoinArticleRepository.java
  src/main/java/in/koreatech/koin/admin/notice/repository/AdminKoinNoticeRepository.java
  src/main/java/in/koreatech/koin/admin/notice/repository/AdminKoreatechArticleRepository.java
  src/main/java/in/koreatech/koin/admin/notice/service/AdminNoticeService.java
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/article/model/Board.java
  src/main/resources/db/migration/V144__add_koin_notice.sql
  src/main/resources/db/migration/V145__insert_koin_notice_data.sql
  src/main/resources/db/migration/V146__delete_koin_notice_in_koin_article.sql
  src/test/java/in/koreatech/koin/admin/acceptance/AdminNoticeApiTest.java
  src/test/java/in/koreatech/koin/fixture/ArticleFixture.java
  src/test/java/in/koreatech/koin/fixture/BoardFixture.java
  src/test/java/in/koreatech/koin/fixture/KoinNoticeFixture.java
Labels: 기능, Team Campus

#1441 feat: 코인 아이디/비밀번호 찾기 API 구현
  src/main/java/in/koreatech/koin/_common/auth/ExtractAuthenticationInterceptor.java
  src/main/java/in/koreatech/koin/_common/auth/JwtProvider.java
  src/main/java/in/koreatech/koin/_common/auth/SmsAuthed.java
  src/main/java/in/koreatech/koin/_common/auth/SmsAuthedArgumentResolver.java
  src/main/java/in/koreatech/koin/_common/auth/SmsAuthedContext.java
  src/main/java/in/koreatech/koin/_common/event/UserEmailVerificationSendEvent.java
  src/main/java/in/koreatech/koin/_common/event/UserSmsVerificationSendEvent.java
  src/main/java/in/koreatech/koin/_common/exception/GlobalExceptionHandler.java
  src/main/java/in/koreatech/koin/_common/exception/custom/TooManyRequestsException.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentController.java
  src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserVerificationApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserVerificationController.java
  src/main/java/in/koreatech/koin/domain/user/dto/FindIdByEmailRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/FindIdBySmsRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/FindIdResponse.java
  src/main/java/in/koreatech/koin/domain/user/dto/ResetPasswordByEmailRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/ResetPasswordBySmsRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/VerifySmsCodeRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/VerifySmsCodeResponse.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/CheckEmailDuplicationRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/CheckNicknameDuplicationRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/CheckPhoneDuplicationRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/CheckUserPasswordRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/ExistsByEmailRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/ExistsByPhoneRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/ExistsByUserIdRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/MatchUserIdWithEmailRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/MatchUserIdWithPhoneNumberRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/verification/SendEmailVerificationRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/verification/SendSmsVerificationRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/verification/SendVerificationResponse.java
  src/main/java/in/koreatech/koin/domain/user/dto/verification/VerifyEmailVerificationRequest.java
  src/main/java/in/koreatech/koin/domain/user/dto/verification/VerifySmsVerificationRequest.java
  src/main/java/in/koreatech/koin/domain/user/exception/UserVerificationDailyLimitExceededException.java
  src/main/java/in/koreatech/koin/domain/user/model/UserDailyVerificationCount.java
  src/main/java/in/koreatech/koin/domain/user/model/UserDailyVerifyCount.java
  src/main/java/in/koreatech/koin/domain/user/model/UserEventListener.java
  src/main/java/in/koreatech/koin/domain/user/model/UserVerificationStatus.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserDailyVerificationCountRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserVerificationLimitRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserVerificationStatusRedisRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserSmsService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserVerificationService.java
  src/main/java/in/koreatech/koin/integration/email/form/UserEmailVerificationData.java
  src/main/java/in/koreatech/koin/integration/slack/model/SlackNotificationFactory.java
  src/main/resources/mail/user_email_verification.html
  src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
Labels: 기능, Team User

#1455 refactor: fetch join에 koinNotice 추가
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
Labels: 리팩터링, Team Campus

#1457 refactor: fetch join에 koinNotice 추가2
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
Labels: 리팩터링, Team Campus

#1464 feat: 통합 로그인 API 구현
  src/main/java/in/koreatech/koin/domain/owner/service/OwnerSmsService.java
  src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/UserLoginRequestV2.java
  src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
  src/main/java/in/koreatech/koin/domain/user/service/UserService.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
Labels: 기능, Team User

#1469 refactor: 게시글 단건 조회 Lazy Loading, N+1 문제 해결 및 로직 수정
  src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
  src/test/java/in/koreatech/koin/admin/acceptance/AdminNoticeApiTest.java
Labels: 리팩터링, Team Campus

#1470 fix: flyway sql 체크 버그 수정
  .github/workflows/flyway-check-dangerous-sql.yml
Labels: 버그

#1466 fix: 인증 완료 후 잘못된 코드 요청 시 400 반환
  src/main/java/in/koreatech/koin/domain/user/model/UserVerificationStatus.java
  src/main/java/in/koreatech/koin/domain/user/service/UserVerificationService.java
Labels: 버그, Team User

#1471 feat: 회원가입 시 아이디 중복 확인 api 추가
  src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
  src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
  src/main/java/in/koreatech/koin/domain/user/dto/validation/CheckLoginIdDuplicationRequest.java
  src/main/java/in/koreatech/koin/domain/user/exception/DuplicationLoginIdException.java
  src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
Labels: 기능, Team User

#1472 refactor: 게시글 전체 조회 Lazy Loading, N+1 문제 해결, 로직 오류 수정 및 모듈화
  src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
  src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
Labels: 리팩터링, Team Campus

#1474 fix: Department 스웨거 문서 추가
  src/main/java/in/koreatech/koin/domain/user/dto/validation/CheckLoginIdDuplicationRequest.java
  src/main/java/in/koreatech/koin/web/config/SwaggerGroupConfig.java
Labels: 버그, Team User
